### ISSUE TITLE
Config elite double load l4d2_noghostcheat.smx

### ISSUE THREAD

**Issue by Electr0** [SirPlease/L4D2-Competitive-Rework#10]
cfg\cfgogl\pmelite\confogl_plugins.cfg:
`sm plugins load optional/elite/l4d2_noghostcheat.smx
`
generalfixes.cfg:
`sm plugins load l4d2_noghostcheat.smx`

**Comment by SirPlease** [comment]
Fixed in [Update v0.3](https://github.com/SirPlease/L4D2-Competitive-Rework/commit/befc3bfddf2044fd9295d68059bc2a78a985ccb8)
