### ISSUE TITLE
Zonemod 1v1/2V2/3V3 don't have set the Versus gamemode

### ISSUE THREAD

**Issue by Target5150** [SirPlease/L4D2-Competitive-Rework#106]
Hi,Sir, a small issue

confogl_addcvar mp_gamemode "versus"  // Force Versus for the config.
confogl_addcvar z_difficulty "normal" // Force normal Difficulty to prevent co-op difficulty impacting the config.

are not writed in 1v1/2v2 and 3v3 config

**Comment by SirPlease** [comment]
Sloppy, will close the issue when fixed!
