### ISSUE TITLE
Cleaning

### ISSUE THREAD

**Issue by lechuga16** [SirPlease/L4D2-Competitive-Rework#109]
I think this is not being used:

https://github.com/SirPlease/L4D2-Competitive-Rework/blob/954522e6b292c266cb3b008d7950abbac11b96af/cfg/generalfixes.cfg#L27

https://github.com/SirPlease/L4D2-Competitive-Rework/blob/954522e6b292c266cb3b008d7950abbac11b96af/cfg/cfgogl/zonemod/shared_cvars.cfg#L38

https://github.com/SirPlease/L4D2-Competitive-Rework/blob/954522e6b292c266cb3b008d7950abbac11b96af/cfg/cfgogl/pmelite/confogl.cfg#L49

https://github.com/SirPlease/L4D2-Competitive-Rework/blob/954522e6b292c266cb3b008d7950abbac11b96af/cfg/cfgogl/nextmodpug/shared_cvars.cfg#L36

https://github.com/SirPlease/L4D2-Competitive-Rework/blob/954522e6b292c266cb3b008d7950abbac11b96af/cfg/cfgogl/nextmod/shared_cvars.cfg#L36

https://github.com/SirPlease/L4D2-Competitive-Rework/blob/954522e6b292c266cb3b008d7950abbac11b96af/cfg/cfgogl/eq/shared_cvars.cfg#L38

https://github.com/SirPlease/L4D2-Competitive-Rework/blob/954522e6b292c266cb3b008d7950abbac11b96af/cfg/cfgogl/apex/shared_cvars.cfg#L39

**Comment by SirPlease** [comment]
You're absolutely right, I forgot to remove it from the loading list after I removed it yesterday.
Also, I was certain I removed those cvars.. 🤔 

I'll close the issue when it's removed, thanks for reporting!
