### ISSUE TITLE
l4d2_sound_manipulation strange check

### ISSUE THREAD

**Issue by Electr0** [SirPlease/L4D2-Competitive-Rework#12]
in callback public Action:SoundHook(clients[64], &numClients, String:sample[256], &entity)

if (StrContains(sample, "World", true) == -1 
&& StrContains(sample, "look", false) == -1 
&& StrContains(sample, "ask", false) == -1 
&& StrContains(sample, "followme", false) == -1 
&& StrContains(sample, "gettingrevived", false) == -1 
&& StrContains(sample, "alertgiveitem", false) == -1 
&& StrContains(sample, "imwithyou", false) == -1 
&& StrContains(sample, "laughter", false) == -1 
&& StrContains(sample, "name", false) == -1 
&& StrContains(sample, "leadon", false) == -1 
&& StrContains(sample, "moveon", false) == -1 
&& StrContains(sample, "friendlyfire", false) == -1 
&& StrContains(sample, "splat", false) == -1)
{
	return Plugin_Stop;
}

may be this should be:
if (StrContains(sample, "World", true) == -1 
|| StrContains(sample, "look", false) == -1 
|| StrContains(sample, "ask", false) == -1 
|| StrContains(sample, "followme", false) == -1 
|| StrContains(sample, "gettingrevived", false) == -1 
|| StrContains(sample, "alertgiveitem", false) == -1 
|| StrContains(sample, "imwithyou", false) == -1 
|| StrContains(sample, "laughter", false) == -1 
|| StrContains(sample, "name", false) == -1 
|| StrContains(sample, "leadon", false) == -1 
|| StrContains(sample, "moveon", false) == -1 
|| StrContains(sample, "friendlyfire", false) == -1 
| StrContains(sample, "splat", false) == -1)
{
	return Plugin_Stop;
}

because "&&" required pass all checks and in this check it looks weird

**Comment by SirPlease** [comment]
As you've decompiled the plugin with Lysis, this is an issue on their part as the local file has never used "&&", because as you stated, it would never pass all of them in the same soundfile.
