### ISSUE TITLE
Heartbeat sound and bots 

### ISSUE THREAD

**Issue by Kajax3** [SirPlease/L4D2-Competitive-Rework#121]
*Fixed the playermanagement plugin causing issues with creating bots and leaving the server full with bots called "k9Q6CK42 "
I'm still having this problem on my server, and the heartbeat sound.

**Comment by SirPlease** [comment]
I can confirm that the bots started coming in every now and then again after the update, I'll look into that.
The heartbeat sound is a side effect of me removing the sound manipulation plugin, I'll get to that 👍

**Comment by SirPlease** [comment]
I haven't seen the bots anymore after recent pushes to the github, and I'll close the issue with the next commit that'll fix the heartbeat sound. :)
