### ISSUE TITLE
Dark Carnival: Map 2 Forklift.

### ISSUE THREAD

**Issue by SirPlease** [SirPlease/L4D2-Competitive-Rework#122]
The darn thing isn't adding glows to it properly, look into what happens after the initial punch as it seems to convert.
Also, it does not dissapear after Tank death.

**Comment by honkthebonk2** [comment]
Just adding that this has always been the case with the globe on Dead Air Map 4. Like the forklifts, an extra outline of its previous body spawns at 0,0,0.

**Comment by SirPlease** [comment]
Fixed with the incoming Zonemod 2.0 push.
