### ISSUE TITLE
Death Toll map 2 event is substantially shorter

### ISSUE THREAD

**Issue by nippletwister69** [SirPlease/L4D2-Competitive-Rework#124]
after the update the event barely lasts one attack on Death toll map 2.

**Comment by SirPlease** [comment]
This is not related to the competitive rework, if it however is different then they've changed the script for it as it would simply call 2 Alarm Car hordes.
I'll test it out regardless and post back with a definite answer.

**Comment by SirPlease** [comment]
I can confirm this to be the case, when asking the update team they said they haven't done anything to the horde on that map.
When checking the Stripper:Source dump for the map, they haven't changed.
I will consider this as a non-issue, possibly something for config developers to add back themselves.
