### ISSUE TITLE
Hunter/charger getups

### ISSUE THREAD

**Issue by nippletwister69** [SirPlease/L4D2-Competitive-Rework#125]
hunter getups seem longer following the update. Also have seen instant getups from chargers after the update after a jockeyed or pulled person is charged

**Comment by SirPlease** [comment]
A quick glance over the plugins seems like they're working fine.
I've also asked the Update Team if they changed anything to the animations (duration or sequence) and they said no.

Regardless, I'll check this one out but as it stands it'll be low priority.
