### ISSUE TITLE
Missing/outdated includes

### ISSUE THREAD

**Issue by devilesk** [SirPlease/L4D2-Competitive-Rework#127]
I went through and tried to compile all the sources included in the scripting folder and found a few that failed to compile due to missing includes or some sort of error in the include file.

Missing include files:
- l4d2_penalty_bonus.inc
  - holdout_bonus.sp
- godframecontrol.inc
  - l4d2_charger_getup_fix.sp
- rounds.inc
  - l4d2lib.sp
- smlib/general - looks like there's a whole smlib include subfolder https://github.com/bcserv/smlib/tree/master/scripting/include/smlib
  - l4d_rock_lagcomp.sp
- readyup.inc
  - caster_addons.sp
  - caster_assister.sp
  - l4d_tank_control_eq.sp
  - l4d2_antibaiter.sp
  - l4d2_fix_spawn_order.sp
  - l4d2_playstats.sp
  - si_class_announce.sp

Plugins that include dhooks.inc are failing with the error `error 139: could not find type "SDKFuncConfSource"` Looks like it's missing this line https://github.com/peace-maker/DHooks2/commit/86bfea505adb5a75f550863920e6c0491a035ff5
  - l4d_pounceprotect.sp
  - l4d2_jockey_jumpcap_patch.sp
  - l4d2_jockeyed_charger_fix.sp
  - l4d2_nobackjumps.sp

Plugins that include l4d2util are failing with the following error coming from l4d2util_constants.inc
`error 050: constant 'WEPID_CHAINSAW' already defined`
There's also two warnings
`warning 203: symbol is never used: "MeleeWeaponModels"`
`warning 203: symbol is never used: "MeleeWeaponNames"`

  - current.sp
  - l4d_tank_rush.sp
  - l4d2_getup_slide_fix.sp
  - l4d2_godframes_control_merge.sp
  - l4d2_m2_control_eq.sp
  - l4d2_nosey_parker.sp
  - l4d2_penalty_bonus.sp
  - witch_and_tankifier.sp

**Comment by keyCat** [comment]
> Plugins that include dhooks.inc are failing with the error error 139: could not find type "SDKFuncConfSource" Looks like it's missing this line peace-maker/DHooks2@86bfea5

The source of `SDKFuncConfSource` enum is [`sdktools.inc`](https://sm.alliedmods.net/new-api/sdktools/SDKFuncConfSource). So, whenever DHooks is used in a plugin, SDKTools must be included also.

**Comment by SirPlease** [comment]
My man, saving me the time to go through it.
I'll update the required and up to date includes when I get home after work. :)

**Comment by devilesk** [comment]
Thanks for the update. There's only a couple new errors when I compile now.

Missing pause.inc
* holdout_bonus.sp
* l4d2_antibaiter.sp

l4d_tank_control_eq.sp
`error 050: constant 'L4D2Team_Spectator' already defined`
It looks like there's an enum named `L4D2Team` in the plugin and an enum named `L4D2_Team` in l4d2util_constants.inc that define the same values L4D2Team_Spectator, L4D2Team_Survivor, L4D2Team_Infected. The enum in the plugin defines L4D2Team_None = 0 as well but that isn't used at all.
Removing the redundant L4D2Team enum in the plugin so the enum in l4d2util_constants is used and renaming tag references from L4D2Team to L4D2_Team should fix it.

**Comment by devilesk** [comment]
Everything compiles now :thumbsup:
