### ISSUE TITLE
Little update for readyup's server_namer Support

### ISSUE THREAD

**Issue by AshesBeneath** [SirPlease/L4D2-Competitive-Rework#129]
https://github.com/SirPlease/L4D2-Competitive-Rework/blob/ba27bf64fe1e8ac0adac1ef4c452942e240e40d0/addons/sourcemod/scripting/readyup.sp#L149

I doubt that somebody would put it in **optional** folder so could be better to change the line with
`bHostName = (FindPluginByFile("server_namer.smx") != INVALID_HANDLE);`

Also you seem to put it in main plugins folder in SirPlease servers as well
![ss](https://i.ibb.co/zbvCKtR/20200929003940-1.jpg)

**Comment by SirPlease** [comment]
Totally forgot I added this to the plugin to be honest, and yeah as the patch came I moved my servers in-line with the Github.
I'll adjust it accordingly!
