### ISSUE TITLE
Missing source for `spechud.smx`

### ISSUE THREAD

**Issue by ProdigySim** [SirPlease/L4D2-Competitive-Rework#130]
`plugins/optional/spechud.smx` doesn't appear to have source available.

[Decompiled](https://gist.github.com/ProdigySim/1ba555884b9a7ff3ffec4baaf9f40cbc), it looks like a customized version of [Visor's spechud](https://github.com/Attano/smplugins/blob/master/spechud/spechud.sp) with hybrid scoremod support.

([104 plugins](https://gist.github.com/ProdigySim/7247a6ed1f06e2e7491b3442fbd2f3b6) appear to be missing source, but I want to verify each one before opening an issue--in case filenames are different)

**Comment by SirPlease** [comment]
The include file needs to be updated so I'll get to the source for this soon.

**Comment by lunatixxx** [comment]
Any idea how do they get this hud in really big tournament ? Because i have nothing of that with this plugin.

**Comment by SirPlease** [comment]
You're probably thinking of the casthud, which is an addon.
Every tournament vanille sets up a different one and it's shared on the casting signups.

**Comment by SirPlease** [comment]
Added!
