### ISSUE TITLE
Plugin and config Issues

### ISSUE THREAD

**Issue by jensewe** [SirPlease/L4D2-Competitive-Rework#136]
Most from Nextmod PUG.

- **Missing plugins:**
  - [readyup_old.smx](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/f17a7535a25264f29e98682bd2d5a94ff89021da/cfg/cfgogl/nextmodpug/shared_plugins.cfg#L139)
    > Probably the version used in this repository
  - [l4d2_no_hunter_m2_nextmod.smx](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/f17a7535a25264f29e98682bd2d5a94ff89021da/cfg/cfgogl/nextmodpug/shared_plugins.cfg#L94)
    > The same as l4d2_hunter_no_deadstops.smx
  - Unknown command "no_witch_vote_map"
    > i can't find the source :((((((((((((

- **Plugins failed to load:**
  - [l4d2_health_temp_bonus.smx](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/f17a7535a25264f29e98682bd2d5a94ff89021da/cfg/cfgogl/nextmodpug/shared_plugins.cfg#L103)
    > Still using "left4downtown"; source can be found [here](https://github.com/LuckyServ/sourcemod-plugins/blob/master/source/l4d2_health_temp_bonus.sp))
  - l4d2_nobackjump.smx
    > [Another typo](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/f17a7535a25264f29e98682bd2d5a94ff89021da/addons/sourcemod/scripting/l4d2_nobackjumps.sp#L19) :(

- **Duplicate plugin loads**
  - l4d2_playstats.smx
    > https://github.com/SirPlease/L4D2-Competitive-Rework/blob/f17a7535a25264f29e98682bd2d5a94ff89021da/cfg/cfgogl/nextmodpug/confogl_plugins.cfg#L19 https://github.com/SirPlease/L4D2-Competitive-Rework/blob/f17a7535a25264f29e98682bd2d5a94ff89021da/cfg/cfgogl/nextmodpug/shared_plugins.cfg#L143 

  - l4d2_dominatorscontrol.smx
    > https://github.com/SirPlease/L4D2-Competitive-Rework/blob/f17a7535a25264f29e98682bd2d5a94ff89021da/cfg/cfgogl/nextmodpug/confogl_plugins.cfg#L21 https://github.com/SirPlease/L4D2-Competitive-Rework/blob/f17a7535a25264f29e98682bd2d5a94ff89021da/cfg/cfgogl/nextmodpug/shared_plugins.cfg#L117

- **The following will ruin next match-load**
https://github.com/SirPlease/L4D2-Competitive-Rework/blob/f17a7535a25264f29e98682bd2d5a94ff89021da/cfg/cfgogl/nextmodpug/shared_cvars.cfg#L37

**Comment by jensewe** [comment]
In addition, please remove "sm_restartmap" from nextmodpug/confogl_off.cfg.

**Comment by SirPlease** [comment]
Very tempted to just remove Nextmod (or at least Pug) unless Spoon cares to get back to updating it @spoon-l4d2 
Regardless, thanks for reporting.

**l4d2_nobackjump.smx** is not a typo, as it's properly called in every plugin.
I'll just rename the sourcefile.

**Comment by jensewe** [comment]
Well it's not typo of the sourcefile. I would say that is within the sourcefile, at Line 19 where the plugin try to load a gamedata called "l4d2_nobackjumps", and there's a typo so the compiled plugin will fail to load.

https://github.com/SirPlease/L4D2-Competitive-Rework/blob/f17a7535a25264f29e98682bd2d5a94ff89021da/addons/sourcemod/scripting/l4d2_nobackjumps.sp#L19

and @spoon-l4d2 xd

**Comment by devilesk** [comment]
> Gamedata path: _addons/sourcemod/gamedata/l4d2_nobackjump.txt_

Sir, I think you missed renaming this in the latest commit.

**Comment by SirPlease** [comment]
> > Gamedata path: _addons/sourcemod/gamedata/l4d2_nobackjump.txt_
> 
> Sir, I think you missed renaming this in the latest commit.

I don't wanna talk about it.
Added in [https://github.com/SirPlease/L4D2-Competitive-Rework/commit/6baa9acce942fac1101fd9285869f3100f74e0c1](commit 6baa9)

**Comment by grehorn-servers** [comment]
Hey, Sir!

fix please:  
`sm plugins load optional/l4d2_nobackjump.smx` to `sm plugins load optional/l4d2_nobackjumps.smx` 

in configs:
- eq1v1\confogl_plugins.cfg
- eq2v2\confogl_plugins.cfg
- eq3v3\confogl_plugins.cfg
- nextmod1v1\confogl_plugins.cfg
- zm1v1\confogl_plugins.cfg
- zm2v2\confogl_plugins.cfg
