### ISSUE TITLE
Plugins still relying on left4downtown

### ISSUE THREAD

**Issue by larrybrains** [SirPlease/L4D2-Competitive-Rework#139]
Should the following plugins be recompiled with left4dhooks?

[l4d2_boomer_shenanigans.sp](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/l4d2_boomer_shenanigans.sp
)

[l4d2_no_post_jockey_deadstops.sp](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/l4d2_no_post_jockey_deadstops.sp)

[l4d2_fix_spawn_order.sp](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/l4d2_fix_spawn_order.sp)

[l4d2_godframes_control_merge.sp](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/l4d2_godframes_control_merge.sp)

[l4d2_horde_equaliser.sp](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/l4d2_horde_equaliser.sp)

[l4d2_hybrid_scoremod_zone.sp](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/l4d2_hybrid_scoremod_zone.sp)

[l4d2_hybrid_scoremod.sp](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/l4d2_hybrid_scoremod.s)

[l4d2_tank_support.sp](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/l4d2_tank_support.sp)

**Comment by SirPlease** [comment]
Yes, fixed in [last commit](https://github.com/SirPlease/L4D2-Competitive-Rework/commit/e34a6bccb08dd2592cc4470027c4f2336ad111c5)
