### ISSUE TITLE
EQ 1v1, 2v2, 3v3 broken plugin paths in confogl_plugins.cfg

### ISSUE THREAD

**Issue by Electr0** [SirPlease/L4D2-Competitive-Rework#14]
https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/cfg/cfgogl/eq1v1/confogl_plugins.cfg

// EQ 1v1
sm plugins load optional/1v1_skeetstats.smx
sm plugins load optional/1v1eq.smx
sm plugins load optional/l4d_notank.smx
sm plugins load optional/l4d2_character_fix.smx
sm plugins load optional/l4d2_director_commonlimit_block.smx
sm plugins load optional/l4d_mapbased_cvars.smx
sm plugins load optional/l4d2_meleecontrol.smx
sm plugins load optional/l4d2_nobackjump.smx
sm plugins load optional/l4d2_sound_manipulation.smx

should be:
// EQ 1v1
sm plugins load optional/eq/1v1_skeetstats.smx
sm plugins load optional/eq/1v1eq.smx
sm plugins load optional/eq/l4d_notank.smx
sm plugins load optional/eq/l4d2_character_fix.smx
sm plugins load optional/eq/l4d2_director_commonlimit_block.smx
sm plugins load optional/eq/l4d_mapbased_cvars.smx
sm plugins load optional/eq/l4d2_meleecontrol.smx
sm plugins load optional/eq/l4d2_nobackjump.smx
sm plugins load optional/eq/l4d2_sound_manipulation.smx

same in eq  2v2 and eq 3v3

**Comment by SirPlease** [comment]
Pulled my EQ rework from a much older local rework, thought it was fully checked. Turns out I can't rely on the past me. I'll set it straight when I get home.

**Comment by SirPlease** [comment]
Fixed in [Update v0.4](https://github.com/SirPlease/L4D2-Competitive-Rework/commit/ea05d57ebed772462ba1a2865142a2bccabb981a)
Thanks for reporting! 👍
