### ISSUE TITLE
[SUG] Confoglcompmod Transitional syntax update

### ISSUE THREAD

**Issue by keyCat** [SirPlease/L4D2-Competitive-Rework#148]
Hello again.

We have been recently working on transferring plugins for our servers into SP Transitional syntax and one of the biggest humps to get over was, of course, Confogl. I've decided to share my work on it publicly, so if you'd like you can use it:

https://github.com/keyCat/confoglcompmod

We are currently testing it on our servers and have had no issues so far.

I realise that there's quite a lot of changes to go through, so a few notes:

- I took the original Confogl and I didn't incorporate any of your changes (BuiltinVotes, shared cfg)
- sm_forcematch can be run even if there's match already running (+ quite bad quickfix for confogl_cvars not resetting due to issue #142)
- Fixed sizes for cvar values in CvarSettings and ClientSettings modules. I decided to go with 128 cells for buffers, even though it would make the most sense to have their size set to 256. But it is too much memory wasted IMO and the longest value I have seen actually used was the `l4d_melee_weapons` cvar
- Removed obsolete modules: CheckVersion, SpectatorHud and UnreserveLobby. I would argue that UnprohibitBosses should also be deleted, since the same effect is achieved by using `bossspawningfix` plugin.
- I tried not to mess with the logic at all, but there are a few minor things I have changed because it felt right to clean up a bit
- I use spaces as indents in all my sources (I know, heresy), so be aware of possibility of receiving a crapton of "losse indentation" warnings :)

Hope you find it useful. Cheers.

**Comment by ProjectSky** [comment]
Nice work!

**Comment by SirPlease** [comment]
I appreciate you sharing your work, my apologies for not getting back to this in the longest time ever.
After a recent PR I think this is no longer needed (https://github.com/SirPlease/L4D2-Competitive-Rework/pull/538)
