### ISSUE TITLE
Plugin sources info

### ISSUE THREAD

**Issue by devilesk** [SirPlease/L4D2-Competitive-Rework#151]
To help with adding missing sources I wrote a script that looks at information generated from decompiling the plugins in this repo and I put the results into a spreadsheet. The spreadsheet is sorted so plugins that are missing sources are at the top.

https://docs.google.com/spreadsheets/d/1a3pXqv4Spm8ULOtkmeKeM6NSGJbRdMbsC0nxFFn5Xp4/edit?usp=sharing

For any sources that had a matching [L4D2-Competitive-Framework](https://github.com/Attano/L4D2-Competitive-Framework) source, the script compiles those Attano sources with the 1.6.3 compiler, decompiles them, and compares them on plugin name, description, author, and version.

No rework source and no L4D2-Competitive-Framework source:
- ~l4d2_no_hunter_m2 (not used in any config)~
- ~sceneprocessor~
- ~l4d2util~
- ~l4d2_antimelee~
- ~l4d2_smg_reload_tweak~
- ~fix_engine~
- l4d2_stats
- ~l4d2_byedoor~
- ~specrates~
- ~slots_vote~
- ~l4d2_smoker_drag_damage_interval_zone~
- ~changelog~
- ~l4d2_sounds_blocker~
- ~l4d_blackandwhite~
- ~l4d2_health_temp_bonus~

No rework source, L4D2-Competitive-Framework source mismatch, indicating this repo has a different version:
- ~l4d_thirdpersonshoulderblock~ reconstructed
- ~pill_passer~ reconstructed
- ~l4d2_jockey_skeet~ reconstructed
- ~ghost_hurt~
- ~simple_witch_bonus~
- ~si_fire_immunity~
- ~l4d2_tank_damage_cvars~ reconstructed
- ~double_getup~ reconstructed
- spechud
- ~l4d2_saferoom_item_remove~

The other 46 that are missing a rework source but have a matching L4D2-Competitive-Framework source means those sources can probably be used, but I plan to inspect the decompilations of each plugin in more detail by hand to make sure.

**Comment by lechuga16** [comment]
I found the source in the epimilic repository, decompile the one with sir and it's almost the same (or just not), I hope it helps you with something.

https://github.com/epilimic/sourcemod-plugins/tree/master/pill_passer

**Comment by devilesk** [comment]
I submitted pull requests for every missing source except l4d2_stats and spechud. I didn't look at spechud since it looks like it will be updated https://github.com/SirPlease/L4D2-Competitive-Rework/issues/130

l4d2_stats is the only plugin I couldn't reconstruct. The lysis decompiler throws an error on the Event_PlayerDeath function so there's no output for it. And comparing the disassembly of the original with [this source](https://github.com/SirPlease/SirCoding/blob/master/PublicSourceSP/Old%20(2014%20and%20Earlier)/l4d2_stats.sp) from Sir's SirCoding repo shows significant differences in the Event_PlayerDeath function. I don't understand assembly instructions enough to reconstruct the code based off that.

**Comment by SirPlease** [comment]
Thanks for restronsructing all the sources @devilesk, saved me a bunch of time looking around the place to gather them. 👍 
I will get to Spechud later, as promised in other issue reports and I should be able to push L4D2 Stats shortly.
