### ISSUE TITLE
hittable godframes

### ISSUE THREAD

**Issue by nippletwister69** [SirPlease/L4D2-Competitive-Rework#157]
hittables do not incap survivors after an SI cap has been cleared on a survivor for some amount of frames. fairly consistent issue

**Comment by SirPlease** [comment]
Please make sure you updated to the [latest version](https://github.com/SirPlease/L4D2-Competitive-Rework/commit/87ebc1e98c73485d08b9346942f0792e67e12d3b).

**Comment by nippletwister69** [comment]
The issue occurred on your ny server just 8 hours ago. I'm assuming you've updated your servers to the latest version. I believe luckylock is referring to the same issue in the link u just gave me claiming the issue hasn't been resolved

**Comment by nippletwister69** [comment]
https://clips.twitch.tv/FilthyTameDonkeySoBayed

**Comment by SirPlease** [comment]
Reopened #149
