### ISSUE TITLE
Damage pounce not registering 

### ISSUE THREAD

**Issue by nippletwister69** [SirPlease/L4D2-Competitive-Rework#159]
This happened twice on adams stream yesterday. No damage from a dp. Clip for reference 

https://clips.twitch.tv/ScrumptiousImpartialTermiteBrokeBack

**Comment by SirPlease** [comment]
Tested it with the poor lad it happened to, unfortunately we couldn't reproduce it.
In the clips it appears as if he's pouncing twice, negating the height of the "first pounce".
