### ISSUE TITLE
CLagCompensationManager Crash

### ISSUE THREAD

**Issue by AlexPrud** [SirPlease/L4D2-Competitive-Rework#163]
https://crash.limetech.org/ybdhuya6ifbx

**Comment by SirPlease** [comment]
Same crash as the one in the bottom of issue #19 
Crash hasn't happened to me personally, but the explanation of what would cause it is further down the page.
I'll mark this under Crash Reports and look into what could possibly be causing this for now, but as long as it's a crash that barely happens, it will be fairly low priority.

**Comment by ProjectSky** [comment]
Same crash happened my server https://crash.limetech.org/vlx335beqno7

**Comment by SirPlease** [comment]
> Same crash happened my server https://crash.limetech.org/vlx335beqno7

That is not the same crash, as the reported crash happens on firing their primary weapon.
Your crash looks a lot more like something that is not a part of this github.

**Comment by ProjectSky** [comment]
> > Same crash happened my server https://crash.limetech.org/vlx335beqno7
> 
> That is not the same crash, as the reported crash happens on firing their primary weapon.
> Your crash looks a lot more like something that is not a part of this github.

```CLagCompensationManager::StartLagCompensation with NULL CUserCmd!!!```

**Comment by SirPlease** [comment]
> `CLagCompensationManager::StartLagCompensation with NULL CUserCmd!!!`

What's important is the stack trace, while the eventual error is the same, it's a different cause.
Hence why I said it's not likely to be anything in this github.
