### ISSUE TITLE
Independent Unloader <-> L4D2 Weapon Attributes issue (Crash)

### ISSUE THREAD

**Issue by SirPlease** [SirPlease/L4D2-Competitive-Rework#169]
Reportedly when you load a config and then load a config again, your weapons will not damage common infected, it's like they don't even get hit.
Usually firing an Uzi into a common will cause a server crash (without Accelerator log)

It's literally 6:35am and I need some rest before I look into this, perhaps anyone else has experience with the reported issue?

**Note:** I added L4D2 Weapon Attributes because it's supposed to revert weapon attributes on unload of the plugin.

**Comment by A1oneR** [comment]
Sorry for bothering,there is a more issue about this plugin.
The weapon attributes change fine in map1 but it will return to vanila stat after the map1.The attributes will not be changed unless another new chapter start.And doing this again.
I don't know why this happen,if you can find out the problem,I will appreciate it.

Sorry for my poor English.

**Comment by SirPlease** [comment]
> Sorry for bothering,there is a more issue about this plugin.
> The weapon attributes change fine in map1 but it will return to vanila stat after the map1.The attributes will not be changed unless another new chapter start.And doing this again.
> I don't know why this happen,if you can find out the problem,I will appreciate it.
> 
> Sorry for my poor English.

I can't reproduce this, works fine when I test it.

**Comment by SirPlease** [comment]
As mentioned in the commit to Weapon Attributes, for some reason it thinks the `bullets` have changed to "1" for both Uzis and it will **revert** them to `1050924810` for the SMG and `1053609165` for the Silenced SMG.

**Comment by devilesk** [comment]
Sounds a problem described in this [alliedmods forum post](https://forums.alliedmods.net/showpost.php?p=2143224&postcount=3) where the Float tag is missing from a GetArrayCell call.
https://github.com/SirPlease/L4D2-Competitive-Rework/blob/77ea2ec832f17e9ae7bc6124b3a30074f22387b1/addons/sourcemod/scripting/l4d2_weapon_attributes.sp#L156

**Comment by devilesk** [comment]
Starting to actually test it myself and it's not the line I linked above, but there does seem to be a float value stored.
`weapon_smg - 'bullets' set to 1050924810 INTEGER, 0.319999 FLOAT`

Looking at the config, the only place I see a 0.32 is here `sm_weapon smg_silenced spreadpershot 0.32` so I'm wondering if there's some sort of mixup going on. I'll keep investigating.
