### ISSUE TITLE
Some includes for provided source files are missing

### ISSUE THREAD

**Issue by AshesBeneath** [SirPlease/L4D2-Competitive-Rework#17]
In case someone would like to recompile plugins, these following includes are missing:

socket.inc for confoglcompmod.sp
l4d2lib.inc for l4d2_tank_support.sp

It would be good if you provide them i guess.

**Comment by SirPlease** [comment]
These can be found online, but I'll include them when I get back. I'll close the issue when it's done, for now I'll give it the SoonTM label so won't forget. :D

**Comment by SirPlease** [comment]
Done in [Update v0.4](https://github.com/SirPlease/L4D2-Competitive-Rework/commit/ea05d57ebed772462ba1a2865142a2bccabb981a)
Thanks for reporting! 👍
