### ISSUE TITLE
Unable to !match after a failed !forcematch

### ISSUE THREAD

**Issue by LuckyServ** [SirPlease/L4D2-Competitive-Rework#18]
Like the title says, admins are unable to either `!match` or `!forcematch` after a failed `!forcematch`.

**Comment by Electr0** [comment]
may be because if forcematch failed match _vote not loaded at this time?  check it.

i am was see what promod elite not fully load, after i move loading plugins in shared_plugins.cfg (in 
 eq and zonemod style) it load fine.

**Comment by Electr0** [comment]
also check what in confoglcompmod::ReqMatch.sp  => public Action:RM_Cmd_ForceMatch(client, args)  => IsBuiltinVoteInProgress() not true at this moment by debug in chat for example: PrintToChatAll("RM_Cmd_ForceMatch::IsBuiltinVoteInProgress() %i", IsBuiltinVoteInProgress());

**Comment by SirPlease** [comment]
You left out a couple of details, I'm assuming you meant `!forcematch` wasn't working while a vote was up and then you tried it again after the vote was over?

`!match` is handled by match_vote
`!forcematch` is handled by confoglcompmod's module ReqMatch
AFAIK there's no admin check in match_vote's regular match request, so this wouldn't be limited to admins. Considering both "plugins" rely on builtinvotes, and thus both relying on a vote delay, I assume you were simply trying !match and such too quick after checking out if forcematch worked during a vote.

Considering I currently don't have access to the files, I'll label this as SoonTM and check it out when I get home. Thanks for the report, you're welcome to test and possibly shine more light on the issue.

**Comment by LuckyServ** [comment]
When we `!forcematch` a config name that doesn't exist, for example `forcematch notAConfig`, we're unable to `!match` or `!forcematch` to an existing config after. I didn't really look into it further since there are other more important issues right now.

**Comment by SirPlease** [comment]
Fixed in [Update v0.4](https://github.com/SirPlease/L4D2-Competitive-Rework/commit/ea05d57ebed772462ba1a2865142a2bccabb981a)
Thanks for reporting! 👍
