### ISSUE TITLE
SIG SG 552 zoomed in reload bug

### ISSUE THREAD

**Issue by larrybrains** [SirPlease/L4D2-Competitive-Rework#180]
When reloading while zoomed in with the newly added SIG SG 552, you get stuck in slow mo and the screen will have intense jitter for a few seconds while reloading.

I also tested this on a listen server without any plugins/addons and it doesn't happen.

**Comment by SirPlease** [comment]
I'll mark it under Low Priority and Suggestion as it doesn't fall under what we use in this repo, but on the other hand it might be interesting to see what is causing this.

**Comment by larrybrains** [comment]
Apparently this is an issue with 100 tick servers and there is already a fix for it. https://forums.alliedmods.net/showthread.php?p=2687318
