### ISSUE TITLE
Remove hex characters on some PrintToServer messages

### ISSUE THREAD

**Issue by MartLegion** [SirPlease/L4D2-Competitive-Rework#181]
Hi, as you can follow in this link: https://forums.alliedmods.net/showthread.php?t=328076

Someone requested to remove the Hex from some .sp files in the scripting folder

The files that I found with "PrintToServer("\x01"... are the listed below:

1v1_skeetstats.sp
l4d2_penalty_bonus.sp
l4d2_playstats.sp
survivor_mvp.sp

I think that the console doesn't interpret hex tags.

The PrintToServer was also requested to remove, since it already prints to the Chat (and probably also shows up in the console).

Is a simple edit, so I will let up to you if its valid or not.

You can close this issue if is not valid.

Thanks!

**Comment by SirDontPlease** [comment]
Thanks for the fix but it was CanadianJeff who found these problems as seen on the alliedmodders thread

**Comment by MartLegion** [comment]
Yes I know, you can read that in the _second line_ "**Someone request to remove...**"
That diff is not understandable and I also had no time to interpret a badly formatted post.
I did more than I should. You can credit him I really don't care, don't want, neither play zonemod stuff.
