### ISSUE TITLE
M60 Weapon Spawn has Multiple Pickups Instead of One

### ISSUE THREAD

**Issue by larrybrains** [SirPlease/L4D2-Competitive-Rework#183]
The M60 weapon spawns all allow multiple survivors to pickup an M60 (looks like each spawn can be picked up 5 times before it disappears. )

I added a bandaid fix on my server for this by adding an exclusion for M60 in addons\sourcemod\scripting\modules\WeaponInformation.sp starting on line 808:
```

        if((Weapon_Attributes[iWeaponIndex][WeaponID] == WEAPON_RIFLE_M60_ID))
        {
            DispatchKeyValue(iEntity, "count", "1");
        }
        else
        {
            DispatchKeyValue(iEntity, "count", "5");
        }
```

But I am pretty sure this isn't the right way to do it. 

Anyway, I know this isn't a high priority for you since the M60 is removed from the configs in this repo, but please take a look when you have some time, thanks.

**Comment by SirPlease** [comment]
Like we've talked about this before, and what you've just mentioned, this is not going to be a priority for the repo.
However, after looking at it briefly, I think the best way to approach this to make an array and allow for config devs to exclude certain static spawns.

At the same time, I only think this would be an issue for items such as the grenade launcher and M60 which should be single spawns.

**Comment by Derpduck** [comment]
You could try adding the following code to your Stripper global filters, this can be used to replace the designated weapon_x_spawn entities with weapon_spawn before the map is loaded, preventing the plugin from interacting with them in this way:
```
modify:
{
	match:
	{
		"classname" "weapon_rifle_m60_spawn"
	}
	replace:
	{
		"weapon_selection" "weapon_rifle_m60"
		"count" "1"
	}
}
```

The same could be applied to `weapon_grenade_launcher_spawn` and `weapon_chainsaw_spawn`.

**Comment by SirPlease** [comment]
A workaround has been provided, and you have a bandaid solution for yourself.
I'll close this as not planned.
