### ISSUE TITLE
Dark Carnival 4: 1v1 Issue.

### ISSUE THREAD

**Issue by SirPlease** [SirPlease/L4D2-Competitive-Rework#184]
Survivors can get stuck behind the added props in the saferoom.
Normally this isn't a problem, but in 1v1 they can't teleport to another survivor so they end up dying.

**Comment by honkthebonk2** [comment]
#185 Stripper:Source-based fix.

**Comment by SirPlease** [comment]
Closed with #185's fix, I'll be adding it to the other configs as this wasn't done in the PR 😄
