### ISSUE TITLE
Autoloading config on server startup / Allow readyup.smx to initiate game with less then 2 players

### ISSUE THREAD

**Issue by occasionallycasual** [SirPlease/L4D2-Competitive-Rework#186]
Pretty much the title, i know there was back in the days something called confogl autoload or something like that but being absent from hosting for years this seems to have changed, what is now used to initiate a default confogl mode on startup? (E.g not having to vote for manually do !forcematch). I have my own version of zonemod adapted for pubs and could we allow the readyup.smx plugin to allow for only 2 players to be ready or not needing to ready up at all, i looked at the sourcecode and it doesn't appear to exist any options for this, maybe i missed something?

Thanks

**Comment by SirPlease** [comment]
If your goal is to have one config loaded at all times, you can simply place `sm_forcematch <config name>` somewhere in your `server.cfg`.

As for readyup, it doesn't have an option for what you're asking (unless you use `!forcestart` of course)
If you're comfortable enough with modifying and compiling it yourself, you could modify it so it only checks if at least one player on each side is ready. (You'd have to modify code in `UpdatePanel()`)

**Comment by occasionallycasual** [comment]
Cheers, solved all the issues I had and i'll close the issue now as there's nothing more from my side!
