### ISSUE TITLE
(SM) Invalid convar handle in match_vote.smx

### ISSUE THREAD

**Issue by occasionallycasual** [SirPlease/L4D2-Competitive-Rework#188]
I have quite a lot of the following errors in the logs and thought i'd add them here for backlog, maybe you already know about it.

> L 11/03/2020 - 17:34:04: [SM] Exception reported: Invalid convar handle 184017d (error 3)
> L 11/03/2020 - 17:34:04: [SM] Blaming: match_vote.smx
> L 11/03/2020 - 17:34:04: [SM] Call stack trace:
> L 11/03/2020 - 17:34:04: [SM]   [0] SetConVarInt
> L 11/03/2020 - 17:34:04: [SM]   [1] Line 68, C:\Users\Sir\Documents\NewNewScripting\match_vote.sp::OnPluginEnd

**Comment by occasionallycasual** [comment]
Additionally, the following addons doesn't seem to load.

> L 11/03/2020 - 18:50:56: Info (map "c1m1_hotel") (file "/home/game/serverfiles/left4dead2/addons/sourcemod/logs/errors_20201103.log")
> L 11/03/2020 - 18:50:56: [confoglcompmod.smx] [Confogl] CvarSettings: Could not find CVar specified (l4d_ready_enabled)
> L 11/03/2020 - 18:50:56: [confoglcompmod.smx] [Confogl] CvarSettings: Could not find CVar specified (l4d_ready_minimum_players)
> L 11/03/2020 - 18:50:56: [confoglcompmod.smx] [Confogl] CvarSettings: Could not find CVar specified (l4d_ready_survivor_freeze)
> L 11/03/2020 - 18:50:56: [confoglcompmod.smx] [Confogl] CvarSettings: Could not find CVar specified (l4d_ready_delay)
> L 11/03/2020 - 18:50:56: [confoglcompmod.smx] [Confogl] CvarSettings: Could not find CVar specified (l4d_ready_enable_sound)
> L 11/03/2020 - 18:50:56: [confoglcompmod.smx] [Confogl] CvarSettings: Could not find CVar specified (l4d_ready_chuckle)
> L 11/03/2020 - 18:50:56: [confoglcompmod.smx] [Confogl] CvarSettings: Could not find CVar specified (l4d_ready_live_sound)
> L 11/03/2020 - 18:50:56: [confoglcompmod.smx] [Confogl] CvarSettings: Could not find CVar specified (tankcontrol_print_all)
> L 11/03/2020 - 18:50:56: [confoglcompmod.smx] [Confogl] CvarSettings: Could not find CVar specified (l4d2_antibaiter_delay)
> L 11/03/2020 - 18:50:56: [confoglcompmod.smx] [Confogl] CvarSettings: Could not find CVar specified (l4d2_antibaiter_horde_timer)
> L 11/03/2020 - 18:50:56: [confoglcompmod.smx] [Confogl] CvarSettings: Could not find CVar specified (l4d2_antibaiter_progress)
> L 11/03/2020 - 18:50:56: [confoglcompmod.smx] [Confogl] CvarSettings: Could not find CVar specified (l4d_global_percent)
> L 11/03/2020 - 18:50:56: [confoglcompmod.smx] [Confogl] CvarSettings: Could not find CVar specified (l4d_tank_percent)
> L 11/03/2020 - 18:50:56: [confoglcompmod.smx] [Confogl] CvarSettings: Could not find CVar specified (l4d_witch_percent)
> L 11/03/2020 - 18:50:56: [confoglcompmod.smx] [Confogl] CvarSettings: Could not find CVar specified (l4d_boss_vote)
> L 11/03/2020 - 18:51:00: Error log file session closed.

I have verified that they are in the plugins folders, is there a way to diagnose why?

**Comment by SirPlease** [comment]
Line 68: `SetConVarInt(g_hSvMaxPlayers, GetConVarInt(g_hMaxPlayers));`
sv_maxplayers is unlocked by `L4DToolZ`, which is a part of this setup, not having it installed or setup properly (+combined with your other errors) would indicate something is wrong with your setup

**Comment by occasionallycasual** [comment]
My setup is mostly identical to the one in this repo, other then having a personalized version of zonemod with is executed by forcematch in the server.cfg, would the cvars other then readyup fail to load due dependency on readyup being disabled? (it was disabled at the moment which i totally forgot about since i was adding functionality for readying up with less players.. derp). I'll be enabling that first and let you know.

**Comment by SirPlease** [comment]
Have you resolved the issue?
Like I said, the ConVar handle you're reporting simply looks for `sv_maxplayers` which is setup properly within the repository.
