### ISSUE TITLE
Server crashes

### ISSUE THREAD

**Issue by LuckyServ** [SirPlease/L4D2-Competitive-Rework#19]
I will post here crash logs as they happen.

Server files: [Here](https://github.com/LuckyServ/l4d2_luckylock_server_install_public)

**Comment by LuckyServ** [comment]
## SetRes
Config: Promod Elite 1.1
Crash log: https://crash.limetech.org/6lnszcku54y7

**Comment by Electr0** [comment]
try recompile all these plugins with 1.9 compilier (if they used) :
double_getup
l4d2_sound_manipulation
l4d2_melee_shenanigans
l4d2_nosey_parker
si_fire_immunity
l4d2_slowdown_control
l4d2_melee_fix

i was have same crash

**Comment by SirPlease** [comment]
According to A1m, as he reported it to me through Steam, The issue is related to l4d2_melee_fix. I can't currently check if it's just Promod's elite version, but he provided me with a fix for it made by sheo: http://pastebin.com/9YcpGbym

I'll look into it when I get home.

**Comment by keyCat** [comment]
@SirPlease Except for usage of `natives_and_forwards` for `IsSi()` method, this looks like the same code that [was already applied as a fix for SM 1.7](https://github.com/Attano/L4D2-Competitive-Framework/pull/18/commits/5fc20dcbd52b3bcae0741eccdeca6863a0817c58).

Like @Electr0 said above, recompiling it with SM 1.9 is what most likely helps.

**Comment by LuckyServ** [comment]
Config: NextMod (based on Zonemod 1.9.3)
https://crash.limetech.org/qmz6cvqxva4d

**Comment by Electr0** [comment]
https://github.com/Attano/Left4Downtown2/blob/944994f916617201680c100d372c1074c5f6ae42/extension.cpp#L236 

Detours::TerrorWeaponHit::OnTerrorWeaponHit =>g_pFwdOnTerrorWeaponHit => L4D2_OnEntityShoved

its around this stuff used this native L4D2_OnEntityShoved

**Comment by SirPlease** [comment]
I'll mark this as resolved for now, thank you very much for your elaborate comment @Electr0

**Comment by LuckyServ** [comment]
https://crash.limetech.org/fsorjrfnmboj

**Comment by LuckyServ** [comment]
Yes, it is this:

```
CLagCompensationManager::StartLagCompensation with NULL CUserCmd!!!
```

**Comment by Electr0** [comment]
i am was have this issue on fun servers using this plugin https://forums.alliedmods.net/showthread.php?p=1548627 before rewrite this plugin, crashes was because this shit was not have checks what prop they equip to player after switch weapons, this crash easy repduce just equip non weapon prop to player and they crash server, i don't know what in your case
