### ISSUE TITLE
Adrenaline health?

### ISSUE THREAD

**Issue by Krevik** [SirPlease/L4D2-Competitive-Rework#192]
Adrenaline gives no health (normal versus without any matchmode loaded), and I cannot find a proper var anywhere in files to change it. It happens only sometimes but when happens, it lasts for the whole campaign (I was playing the parish).

**Comment by SirPlease** [comment]
Are you running any other plugins in the default/fixes/anticheat folder that get loaded while matchmodes aren't active?
In the install, the only plugin that interacts with the adrenaline health value is `optional/l4dhots.smx` as it'll return the value for `adrenaline_health_buffer` back to what it was at the time of config load.
I scoured the files for any cfg that would mess with adrenaline and couldn't find any.

**Comment by Krevik** [comment]
Hm seems kinda weird. No, I am not running any other plugins than these default ones. Must be some problem on my side then.

**Comment by A1mDev** [comment]
Maybe ou have an old one installed and it does not reset values after upload. Check

**Comment by A1mDev** [comment]
had the same problem with the old plugin

**Comment by A1mDev** [comment]
Check the convar 'adrenaline_health_buffer', default value 25. If changed see which plugin changes the value.

**Comment by Krevik** [comment]
> Maybe ou have an old one installed and it does not reset values after upload. Check
 - No way I have old version of plugin I was downloading newest ones from this repo :O


> Check the convar 'adrenaline_health_buffer', default value 25. If changed see which plugin changes the value.

yep it's 25

**Comment by jensewe** [comment]
`optional/l4dhots.smx` internally overrides values of ConVars `pain_pills_health_value` and `adrenaline_health_buffer`, which control how much light health items heal, and it defaults them to 0 for own features.
I'd like to assume that you're playing versus in your local server, just leaving a server with this plugin enabled, because this game always "copies" the server-side settings, including those ConVars.
