### ISSUE TITLE
clip_removal

### ISSUE THREAD

**Issue by oethanx** [SirPlease/L4D2-Competitive-Rework#193]
I've noticed it doesn't auto remove the clips, have to manually type in the command. Tested on c2m1

**Comment by SirPlease** [comment]
It does automatically remove clips, but looking at the sourcefile the automatic method doesn't disable `env_physics_blockers` while the admin command does.

Before I make a change to disable env_physics_blockers automatically, I'd like to see if that impacts anything negatively first.

**Comment by oethanx** [comment]
Also, notice removed clips gets added back on team change

**Comment by SirPlease** [comment]
After finally getting to it, it's easy to notice that this plugin doesn't even serve a purpose anymore.
Instead it just breaks things, addressed in the most recent [push](https://github.com/SirPlease/L4D2-Competitive-Rework/commit/99320f383f4c3ef31e28f01bd31012236c8b2fc6)

Thanks for reporting!
