### ISSUE TITLE
Drop secondary bug

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#195]
If the survivor who dies have a melee weapon, firstly he does not drop it but keep it on him and then you can't collect his primary weapon it disappears.

**Comment by SirPlease** [comment]
I've confirmed that the secondary doesn't drop even though we do make use of `l4d2_drop_secondary.smx`.
I'll take a look at the plugin.

As for Primary weapons not dropping, this only happens when the same weapon is nearby.
