### ISSUE TITLE
Tank damage announce error

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#197]
It spammed this in the chat the whole round after the human tank left when he died.
https://ibb.co/x5HgL09

Log sourcemod 
L 11/17/2020 - 18:03:36: [SM] Exception reported: Client 8 is not connected
L 11/17/2020 - 18:03:36: [SM] Blaming: l4d_tank_damage_announce.smx
L 11/17/2020 - 18:03:36: [SM] Call stack trace:
L 11/17/2020 - 18:03:36: [SM]   [0] GetClientName
L 11/17/2020 - 18:03:36: [SM]   [1] Line 240, plugin.sp::PrintTankDamage
L 11/17/2020 - 18:03:36: [SM]   [2] Line 201, plugin.sp::Timer_CheckTank

**Comment by SirPlease** [comment]
Do you load frozen_tank_fix?
I suspect the Timer is getting called and called again due to the Tank being stuck in its dying animation and it firing over and over.

**Comment by lunatixxx** [comment]
Yes i have this plugin installed.

**Comment by SirPlease** [comment]
After reviewing the code, I don't quite understand how it'd keep printing it to chat unless `g_bIsTankInPlay` is set to true, which only happens on Tank Spawn (but you'd hear a bell sound when this happens, which you'd probably report along with the issue).

This leads us to the possibility of `Timer_CheckTank` simply not resetting the boolean to `false`.
However, unless you have a ton more of those logs (which you'd likely report) it's bound to get to the boolean reset eventually as it'd keep triggering for AI.

Quite the mystery, haven't seen this happen ever.

**Comment by lunatixxx** [comment]
This happened just two times on over hundred games but i thought that it was worth reporting, not a big deal.
