### ISSUE TITLE
The map "Cold Stream" map 2 bright sun and static tank , map 4 escape tank

### ISSUE THREAD

**Issue by Target5150** [SirPlease/L4D2-Competitive-Rework#198]
I know that was not popular map in L4D2 matchmode , but the problem existed.

[Kimchi's stream record](https://www.youtube.com/watch?v=WZSQsK2tLqQ)  time:1:20:15(map 2 bright sun) 1:21:40(map 2 tank) and 1:51:25(map 4 escape tank)

the map 2 bright sun:  is it my misunderstand? Look like bright sun had been removed, but not effect.
```
fliter:
……
; --- remove bright sun
{
	"classname" "env_sun"
}
```

the map 2 no tank spawn:
Can found this in stripper:  not only in Zonemod, other mode also had this problem except nextmod.
```
filter:
……
; --- Remove static tank
{
	"targetname" "quake_trigger"
}
```
and all config had set:
`static_tank_map c13m2_southpinestream`

So...Should it remove static tank, or keep static tank?

And, the map 4 escape tank should it remove like Parish finale escape tank?(I don't know is it existed on old version L4D2 matchmode)

**Comment by SirPlease** [comment]
> map 2 bright sun

I cant find `fliter:` in the files, so I'm assuming this is something on your end that went wrong, unless you went out of your way to type it over manually rather than copy paste 😄 

> So...Should it remove static tank, or keep static tank?
Every config has it set to remove the static tank, but NextMod (which I'm not going to touch with a stick until after @spoon-l4d2 updates it) hasn't removed the `quake_trigger` so I'll keep the static tank in there.

**Comment by larrybrains** [comment]
Is the intention to remove the bright blinding light in the tunnel at the beginning or to just remove the sun in general?

If it's intended for the blinding tunnel light, then it should be changed to: 

```
filter:
{
	"classname" "env_lightglow"
}
```

It's the only env_lightglow on the map. Tested on my server and it works.

**Comment by Target5150** [comment]
> > map 2 bright sun
> 
> I cant find `fliter:` in the files, so I'm assuming this is something on your end that went wrong, unless you went out of your way to type it over manually rather than copy paste 😄
> 
> > So...Should it remove static tank, or keep static tank?
> 
> Every config has it set to remove the static tank, but NextMod (which I'm not going to touch with a stick until after @spoon-l4d2 updates it) hasn't removed the `quake_trigger` so I'll keep the static tank in there.

```
filter:

; --- remove ash particle effects
{
	"classname" "func_precipitation"
}

; --- Remove static tank
{
	"targetname" "quake_trigger"
}

; ---remove the event
{
	"targetname" "bridge_clip"
}
{
	"targetname" "barrier"
}
{
	"targetname" "bridge_murette"
}

; --- remove bright sun
{
	"classname" "env_sun"
}

; --- allow tanks to spawn anywhere

{
	"hammerid" "3172954"
}
```

fliter on the top, I've add "..." between fliter and the "targetname/classname/hammerid" on purpose.

![image](https://user-images.githubusercontent.com/42076548/99635869-93918c00-2a7d-11eb-9f1a-bf88b062dbef.png)

Btw, I see the new commit , the nextmodpug also using nextmod stripper, I think it should doesn't need remove _static_tank_map c13m2_southpinestream_.

**Comment by Target5150** [comment]
> Is the intention to remove the bright blinding light in the tunnel at the beginning or to just remove the sun in general?
> 
> If it's intended for the blinding tunnel light, then it should be changed to:
> 
> ```
> filter:
> {
> 	"classname" "env_lightglow"
> }
> ```
> 
> It's the only env_lightglow on the map. Tested on my server and it works.

I forgot describe my doubt, same with you. Is that just removed the sun in genaral or remove the blinding sun in tunnel.

**Comment by SirPlease** [comment]
I was referring to the misspelled `fliter` in the issue report, which made me look for wrongfully spelled filters.
I assume the original intent was to remove the blinding light, I'm guessing no proper testing was done 😄 

I've gone ahead and removed NextModPug entirely as it'll be removed in the upcoming NextMod update either way.
