### ISSUE TITLE
i think i should clean this

### ISSUE THREAD

**Issue by lechuga16** [SirPlease/L4D2-Competitive-Rework#199]
https://github.com/SirPlease/L4D2-Competitive-Rework/blob/440daf4aa25417f3dd847dd4d24980d570314d67/addons/sourcemod/configs/matchmodes.txt#L28-L31

cfg/sourcemod/left4dhooks.cfg

**Comment by jensewe** [comment]
unused plugins btw

[l4d2_tank_attack_control_nextmod.smx](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/plugins/optional/l4d2_tank_attack_control_nextmod.smx)
[l4d2_health_temp_bonus.smx](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/plugins/optional/l4d2_health_temp_bonus.smx)

**Comment by lechuga16** [comment]
the following lines are not used either

https://github.com/SirPlease/L4D2-Competitive-Rework/blob/440daf4aa25417f3dd847dd4d24980d570314d67/cfg/cfgogl/nextmod/shared_settings.cfg#L30

https://github.com/SirPlease/L4D2-Competitive-Rework/blob/440daf4aa25417f3dd847dd4d24980d570314d67/cfg/cfgogl/pmelite/pmelite.cfg#L116

https://github.com/SirPlease/L4D2-Competitive-Rework/blob/440daf4aa25417f3dd847dd4d24980d570314d67/cfg/cfgogl/zm1v1/zm1v1.cfg#L29-L31

https://github.com/SirPlease/L4D2-Competitive-Rework/blob/440daf4aa25417f3dd847dd4d24980d570314d67/cfg/cfgogl/eq1v1/eq1v1.cfg#L23-L25

**Comment by SirPlease** [comment]
You guys are amateurs, forgot to correct the readme.md as well.
