### ISSUE TITLE
Map doesn't restart after unload of config

### ISSUE THREAD

**Issue by justtheletterjwithadot** [SirPlease/L4D2-Competitive-Rework#2]
**Issue:**
Performing !rmatch after loading into config does not restart map after unload as there is no plugin to perform the action.

> Server CVar Tracking Information Reset!
> [SM] The loading lock is no longer in effect.
> [SM] Plugin L4D2 Self Mute unloaded successfully.
> Set 39@0
> Set f3@1
> Set 7d@2
> Set 13@3
> [SM] All plugins have been unloaded.
> [Console Spam] patched 0 entries.
> [SM] The plugin list has been refreshed and reloaded.
> **Unknown command "sm_restartmap"**
> [SM] Changed cvar "z_common_limit" to "30".

**Resolution:**
Adding back [restartmap.smx](https://github.com/SirPlease/Server4Dead-Project/blob/master/Extensions%2C%20Gamedata%2C%20Competitive%20Preperation/addons/sourcemod/plugins/restartmap.smx) from [Server4Dead-Project](https://github.com/SirPlease/Server4Dead-Project) resolves the issue faced.

**Comment by SirPlease** [comment]
Restartmap isn't in there on purpose to prevent having to restart the map to vote/load another config.
Just didn't take out the command for it yet, thanks.
