### ISSUE TITLE
c8m4_interior.cfg in zonemod / elite / apex configs at line 122 have ] instead }

### ISSUE THREAD

**Issue by Electr0** [SirPlease/L4D2-Competitive-Rework#20]
bug found by [empathy](https://steamcommunity.com/profiles/76561198017350428/ )

**cfg\stripper\apex\maps\c8m4_interior.cfg**, line 122:
filter:
{
	"model" "models/props_equipment/light_floodlight.mdl"
**]**

**cfg\stripper\pmelite\maps\c8m4_interior.cfg**, line 122:
filter:
{
	"model" "models/props_equipment/light_floodlight.mdl"
**]**

**cfg\stripper\zonemod\maps\c8m4_interior.cfg**, line 122:
filter:
{
	"model" "models/props_equipment/light_floodlight.mdl"
**]**

**Comment by SirPlease** [comment]
Fixed in [Update v0.4](https://github.com/SirPlease/L4D2-Competitive-Rework/commit/ea05d57ebed772462ba1a2865142a2bccabb981a)
Thanks for reporting! 👍
