### ISSUE TITLE
Map Change during playtime?

### ISSUE THREAD

**Issue by Krevik** [SirPlease/L4D2-Competitive-Rework#200]
So today I had weird accident - wrong map has loaded. We were playing versus with no matchmode loaded. There seems nothing wrong in the logs, just wrong map has been loaded. The map that was loaded was c7m1, while we were playing c6m2. Is that problem on my side? I hadn't really been changing much settings... I am encountering a lot of problems any idea what might be main problem causer? There's no crash logs, problems, it just seems like plugins are not being loaded properly sometimes. Greetings!

**Comment by SirPlease** [comment]
The install comes with an addon that combines the passing with the sacrifice, after The Passing map 2, it'll load The Sacrifice map 1.

The addon is called `thesaccing.vpk`
