### ISSUE TITLE
Show player names of !mix users

### ISSUE THREAD

**Issue by ProdigySim** [SirPlease/L4D2-Competitive-Rework#207]
Feature request for CEDAPUG use cases. It would be nice to show the name of the players on each team who Requested and Accepted the `!mix`.

We have disallowed using !mix for official CEDAPUG games, but sometimes people still do so. Since the !mix command does not show who called it, it's a little hard to add accountability when players do mix. It would be nice if these commands printed the name of whoever Requested/Accepted the mix per team.

**Comment by SirPlease** [comment]
Doesn't have anything to do with the github.
