### ISSUE TITLE
C1M1 finale saferoom stuck spot

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#209]
I don't know if this is the place, but this is still possible to get stuck here depsite having the zonemod stripper.
{
	; block a stuck spot on top of the desk and chairs at end saferoom
	"origin" "1954 4308 1249"
	"mins" "-46 -20 -65"
	"maxs" "46 20 65"
	"initialstate" "1"
	"BlockType" "2"
	"classname" "env_physics_blocker"
}

**Comment by Derpduck** [comment]
The block type just needs to be changed from 2 to 0.

**Comment by SirPlease** [comment]
This is fixed in Zonemod 2.0, but I'll push it to the others shortly.
