### ISSUE TITLE
l4d2_unsilent_jockey plugin modifications

### ISSUE THREAD

**Issue by robex** [SirPlease/L4D2-Competitive-Rework#211]
As of right now, if my understanding is correct, this plugin checks whether a jockey is silent upon spawning by hooking all played sounds and checking if a "jockey/voice/" sound is played. If it is not, it forces playback of a random jockey sound. There is also the "musical_jockeys" plugin that plays a short tune when a jockey spawns (if you have music enabled), but that one is irrelevant to the question.

The plugin mentioned in the title fixes part of the problem, since the jockeys now make noise when spawning every time. However, players are still abusing silent jockeys (and sometimes doing it unintentionally) by spawning far enough away from the survivors for them to not hear the initial sound, then waiting for the interval between jockey sounds (which seems to be quite long sometimes, hence the problem) in order to attack.

My idea is to just ignore whether the jockey is silent or not initially, and simply override the sound every time and force the playback of a random jockey sound in a regular (or random, but within a more reasonable range) manner. I have modified the plugin and done some not very extensive tests and it seems to work fine, it would be a matter of tuning the parameters in order to have the sounds play at a reasonable frequency and volume. Nonetheless I'd rather wait for your opinion on this before polishing and testing the plugin too much, in the case that you find problems with the concept, because I don't want to waste my time.

Here is the prototype plugin (I have left the old convars for backwards compatibility): [l4d2_unsilent_jockey.sp](https://pastebin.com/raw/VvayKd2Y)

**Comment by SirPlease** [comment]
When attempting to review it once more (as I didn't save it locally) the pastebin expired, any chance you could post it again?

**Comment by robex** [comment]
Sure, here you are: [l4d2_unsilent_jockey.sp](https://pastebin.com/Zsc3p6NC)

I also realized there is a glitch where if you switch to survivor/spec and back to infected before the timer repeats the jockey sound will play forever. This is because I'm checking for team switches inside the timer function. I had to add this extra check because the `player_death` event doesn't fire when switching teams, even though the SI dies:

```
    // switched team while alive
    if (GetClientTeam(client) != TEAM_INFECTED) {
        KillTimer(hJockeySoundTimer[client], false);
        hJockeySoundTimer[client] = null;
    }
```

The proper way to do it would be to instead hook [`player_team`](https://wiki.alliedmods.net/Left_4_Dead_2_Events#player_team) and kill the timer there. It should be a rather trivial change, I'll test it later.

**Comment by robex** [comment]
Version with above bug (hopefully) fixed: [l4d2_unsilent_jockey.sp](https://pastebin.com/raw/G52LULQu)

**Comment by SirPlease** [comment]
I've gone ahead and finally tested this (9 months later) and it seems to work fairly well although it had a few issues.
The sound interval might be a bit too spammy, but we'll see.

I've made a few adjustments of my own:

- Updated the code to new syntax.
- Removed the "spotprey" sounds due to inconsistency.
- Fixed the sounds continuing if a player became Tank.
- Fixed the sounds continuing if a player went for a respawn (went for a left4dhooks include)
- Timer is now canceled the moment the jockey pounces someone, and continues if the Jockey is cleared but not killed.
- Converted the interval and debug to ConVars rather than hardcoded values.
