### ISSUE TITLE
firebulletsfix.smx not loaded in generalfixes.cfg

### ISSUE THREAD

**Issue by LuckyServ** [SirPlease/L4D2-Competitive-Rework#22]
The [firebulletsfix.smx](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/plugins/firebulletsfix.smx) plugin doesn't seem to be loaded anywhere. It seems that we should load it from [generalfixes.cfg](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/cfg/generalfixes.cfg).

**Comment by LuckyServ** [comment]
According to [A1m](https://steamcommunity.com/id/7708613343559852777/), the plugin affects tank hittable physics when crouched. We found this to be the case and applied a patch to only replace the origin vector of survivors. The source for this patch can be viewed [here](https://github.com/LuckyServ/l4d2_luckylock_server_install_public/blob/master/addons/sourcemod/scripting/firebulletsfix.sp).

**Comment by SirPlease** [comment]
Fixed in [Update v0.4](https://github.com/SirPlease/L4D2-Competitive-Rework/commit/ea05d57ebed772462ba1a2865142a2bccabb981a)
Thanks for reporting! 👍
