### ISSUE TITLE
Request: Allow props/walls to be broken before finale has started

### ISSUE THREAD

**Issue by Derpduck** [SirPlease/L4D2-Competitive-Rework#223]
Breakable walls and props (doors) within finale play areas are not breakable by special infected until the finale event is fully started.
This often leads to confusion on part of players when trying to attack and causes infected to get stuck inside rooms until the event is started.
It appears common infected can still break down walls, but not sure on that one.
This is not anything within the maps themselves, even breakable entities added into maps with Stripper in finale areas are unbreakable until the event is started.

This has gone mostly unnoticed for the majority of players due to how infrequently finales are played and most maps not using breakable walls.

It might be possible to fire an output on entities within the finale area to set them to be breakable.

**Comment by MartLegion** [comment]
I asked Psyk0tik to check this behaviour and from his analysis it is hardcoded in the engine.

Would need some detour patch here.

CPropDoorRotatingBreakable::OnTakeDamage calls CBreakableProp::OnTakeDamage
CBreakableProp::OnTakeDamage has this code:

if ( !(unsigned __int8)CDirector::IsFinale(TheDirector) && v64 != -1 )
{
  v20 = (CBaseEntity **)((char *)g_pEntityList + 16 * (v64 & 0xFFF));
  if ( v20 != (CBaseEntity **)-4 && *((_DWORD *)g_pEntityList + 4 * (v64 & 0xFFF) + 2) == v64 >> 12 )
  {
    if ( v20[1] )
    {
      if ( CBaseEntity::GetTeamNumber(v20[1]) == 3
        && v64 != -1
        && (char *)g_pEntityList + 16 * (v64 & 0xFFF) != (void *)-4
        && *((_DWORD *)g_pEntityList + 4 * (v64 & 0xFFF) + 2) == v64 >> 12 )
      {
        v21 = (CBaseEntity *)*((_DWORD *)g_pEntityList + 4 * (v64 & 0xFFF) + 1);
        if ( v21 )
        {
          if ( (*(unsigned __int8 (__cdecl **)(CBaseEntity *))(*(_DWORD *)v21 + 364))(v21)
            && !(*(unsigned __int8 (__cdecl **)(CBaseEntity *))(*(_DWORD *)v21 + 1912))(v21)
            && (CBaseEntity::GetTeamNumber(v21) != 3
             || (*(int (__cdecl **)(CBaseEntity *))(*(_DWORD *)v21 + 1348))(v21) != 8) )
          {
            if ( (*((_BYTE *)this + 333) & 8) != 0 )
              CBaseEntity::CalcAbsolutePosition(this);
            v22 = CNavMesh::GetNearestNavArea(TheNavMesh, (char *)this + 736, 0, 1176256512, 0, 1, 0);
            if ( v22 )
            {
              if ( (*(_BYTE *)(v22 + 300) & 0x40) != 0 && !*(_DWORD *)(dword_FC841C + 48) )
                return 0;
            }
          }
        }
      }
    }
  }
}

**Comment by MartLegion** [comment]
Good job @jensewe

**Comment by jensewe** [comment]
> Good job @jensewe

Thanks. Though I got another question about doors that can be used for survivor rescue, where I hold an impression that they are invulnerable to scratches. However I cannot reproduce this on local servers now. Would like that anyone can tell if it's true.

**Comment by Derpduck** [comment]
> Thanks. Though I got another question about doors that can be used for survivor rescue, where I hold an impression that they are invulnerable to scratches. However I cannot reproduce this on local servers now. Would like that anyone can tell if it's true.

This is set manually on specific doors only on certain maps, the doors also become breakable after being opened. This can be fixed with Stripper.
