### ISSUE TITLE
Certain SI won't be given ever if the last user despawned, and as ghost don't spawn before he becomes the tank

### ISSUE THREAD

**Issue by jensewe** [SirPlease/L4D2-Competitive-Rework#226]
Title, though this plugin seems being scheduled to be removed in the incoming 2.0.

**Comment by jensewe** [comment]
https://www.twitch.tv/videos/875670100
Maybe you can check this, beginning from 14min50s, where there's a despawned charger that didn't spawn and became the tank. Actually the Infected side no longer got chargers since tank spawned, until round ended.

**Comment by SirPlease** [comment]
Thanks for the report, issue is caused by PlayerSpawned[client] being set to true for the player because he did spawn once, which means the SI doesn't get pushed back into the Array.
I'll add an additional check for this, thanks for the report! Good find.

**Comment by SirPlease** [comment]
Should all be good with the latest push.
