### ISSUE TITLE
Hittable glow desync

### ISSUE THREAD

**Issue by Derpduck** [SirPlease/L4D2-Competitive-Rework#228]
![](https://steamuserimages-a.akamaihd.net/ugc/1774949040880948022/190D2C2D489F6FB8892C193B9AA9F84A79B34589/)

Not sure if it was due to server lag, but recording a demo fixed the glow.

**Comment by SirPlease** [comment]
You may have missed an update from the entity, as the glow is parented to the hittable and it relies on `OnTransmit`, so it'll only send an update of the entity's position if a client requests it.

**Comment by Derpduck** [comment]
It did look like the hittable was "low fps" on my screen for a bit, maybe due to the server forcing my rates to 30 from spec
