### ISSUE TITLE
Incorrect survivor spawn positions on intro maps

### ISSUE THREAD

**Issue by Derpduck** [SirPlease/L4D2-Competitive-Rework#229]
Due to the plugin that skips intro cutscenes, survivors positions are never set correctly when the round starts.

https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/readyup.sp#L937
This function that warps survivors to saferoom when the round starts will use the navmesh to determine where survivors start. On most maps this is fine, but certain maps like c7m1 the saferoom area is very large and has the potential for survivors to fall into a kill trigger when the round starts.

When a cutscene ends it sets the survivors positions by calling the following output on the info_director entity:
```
"OnTrigger" "director,ForceSurvivorPositions,,0,-1"
```
It might be worth trying to fire this output in the `ReturnTeamToSaferoom` function, should it hopefully return survivors to the correct positions.

The issue on c7m1 might also be caused by the wrong survivors being used, as the positions are defined by the L4D1 survivor names instead of the L4D2 names due to the passifice addon.

**Comment by SirPlease** [comment]
Fairly certain this is a non-issue, due to [Velocity being set to 0.](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/2ee2d5bf5ffdf7f8c5c97fafd3e3f186f6c4c507/addons/sourcemod/scripting/readyup.sp#L934)

**Comment by Derpduck** [comment]
https://www.twitch.tv/qeotabro/clip/OilyBlindingPorcupineThisIsSparta

**Comment by SirPlease** [comment]
That's the clip that triggered the fix, yes. ( #155 )
From my brief testing it appears the issue lies within the passifice method we're currently using, so other campaigns are fine from what I can tell.
