### ISSUE TITLE
Why in zonemod / apex used boss_equalizer.smx that try download static bosspercents from hardcoded host

### ISSUE THREAD

**Issue by Electr0** [SirPlease/L4D2-Competitive-Rework#23]
sm plugins load optional/zonemod/boss_equalizer.smx
sm plugins load optional/apex/boss_equalizer.smx

and this plugin try do it from:
#define DB_HOST "31.186.250.11"
#define DB_PATH "bosspercentdb.php"

this is  ip from one of rust server, wtf?

**Comment by SirPlease** [comment]
An old leftover from a time long long ago, was meant to make sure every team plays against the same tank in a tournament.
Visor's server and DB have long expired now.
