### ISSUE TITLE
Boss spawn bugs

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#232]
The tank coordinate are not always accurate too late or in advance for second round(not working ?), compared to witch spawns who are exactly the same except on the passing where she did not spawn for first round.

**Comment by SirPlease** [comment]
Please specify in what circumstances you're playing when reporting issues as I don't know if you're talking about a specific config or this repo on Vanilla.

**Comment by lunatixxx** [comment]
I'm talking about confoglpromod module boss spawn fix.

**Comment by lunatixxx** [comment]
By the way it is just a bug in the game with boss flow progression, it was confirmed by last stand devs a long time ago already.
