### ISSUE TITLE
Common head jump instant death

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#235]
Second time it happens, seems to be a very rare bug when you let yourself fall down on a common head. Related to gravity fix in tickrate fix plugin maybe or just vanilla problem? This is not map specific as the other time it happened in c1m2 at the container one drop.
https://streamable.com/fe93li

**Comment by lunatixxx** [comment]
fix_engine plugin could be guilty too with the no fall damage fix, we can clearly hear Nick screaming like if he was falling.

**Comment by SirPlease** [comment]
This is a game issue that also occurs on 30 tick vanilla servers (albeit very **VERY** rarely), but has a highly increased chance of happening on higher tickrates.

I remember trying to tackle this issue in the past with a plugin, but it wasn't very reliable, it's a good reminder to perhaps study my old code for it and try harder though.
Nobody likes common hopping to their deaths.

Just to be clear, fix_engine is not at fault.

**Comment by ProdigySim** [comment]
I'd love to have this issue fixed as well, if you have any other information about the issue I could try to help investigation. I don't really have a clue why this exacerbated common hop behavior happens.

**Comment by lunatixxx** [comment]
Just had a spitter ejection so i guess this is the same kind of bug, don't know what are the odd for that to happens. 
https://streamable.com/uvjmmb

**Comment by A1mDev** [comment]
@lunatixxx, this fix works, but I ran into problems, sometimes survivors die immediately when they touch the ground, despite the presence of this fix (it was with spit).

**Comment by lunatixxx** [comment]
> @lunatixxx, this fix works, but I ran into problems, sometimes survivors die immediately when they touch the ground, despite the presence of this fix (it was with spit).

It is a little early to say anything as i do not have it since a long time, but i did not notice something like that. My server is in 60 tickrate.

**Comment by lunatixxx** [comment]
Does the value "infected" is taking in count SI players or just commons and bots ? Even with this plugin a survivor got ejected by hunter who pounced under his feets. Does this plugin simply works? I did not see any common hop death since but it's so random that you can't really tell if it is fixed.

**Comment by lunatixxx** [comment]
It happened once again even with this plugin i linked.

**Comment by lunatixxx** [comment]
This was litterally a kamikaze, it just jumped under the survivor.
https://www.youtube.com/watch?v=IVlehCp7Djs

**Comment by SirPlease** [comment]
I've been running the plugin for a while and haven't seen any more instant deaths on my end, streams or reports. I'll add it to generalfixes. 👍
