### ISSUE TITLE
Remove from confoglcompmod.sp include #include <socket>

### ISSUE THREAD

**Issue by Electr0** [SirPlease/L4D2-Competitive-Rework#24]
this is not longer need require socket extension for this plugin since modules/CheckVersion.sp not longer used in confoglcompmod, and it was already included in CheckVersion.sp.

**Comment by SirPlease** [comment]
Done in [Update v0.4](https://github.com/SirPlease/L4D2-Competitive-Rework/commit/ea05d57ebed772462ba1a2865142a2bccabb981a)
Thanks for reporting! 👍
