### ISSUE TITLE
Repeated SI spawns (when round ends)

### ISSUE THREAD

**Issue by Derpduck** [SirPlease/L4D2-Competitive-Rework#240]
https://clips.twitch.tv/SlickGlutenFreeMinkTTours
https://clips.twitch.tv/AbrasiveInquisitiveHerdThisIsSparta

In both clips, the player had a jockey, then died, then the round ended due to a wipe, then got another spawn as a jockey.
In the first clip no other SI died.
In the second clip spitter died after the jockey, then both players got the same spawn.

Not sure if this is intended since the round is already over, or if there is some other cause and the round ending is just a coincidence.

**Comment by SirPlease** [comment]
Not a glitch, `round_end` is called which triggers [CleanSlate](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/0d3d928cb13bb5dd2a499732bf19d99bad294c7b/addons/sourcemod/scripting/l4d2_fix_spawn_order.sp#L368)
