### ISSUE TITLE
[Suggestion] Autoban on disconnect

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#242]
"This plugin will ban people that disconnect during a match before X seconds if they dont reconnect."

I didn't really look into it but it should be possible to make it compatible with readyup (and sub system of cedapug i guess), that will make players think two times before ragequitting and avoid the boredom of reporting.

https://forums.alliedmods.net/showthread.php?p=2672429

**Comment by SirPlease** [comment]
I'm rejecting this because it's beyond the purpose of this repository.
Not only that, there's way too many verifications that need to be done for bans to be accurate, there's too many situations where bits of code won't be able to react properly to the situation.

**Comment by lunatixxx** [comment]
Well i made it anyway and it will definitely not be perfect (probably some tweaks), but this is pretty much the same system that CS:GO by the way and from what i know false positives are very rare. In a perfect world it will not be needed for sure.
[autoban_matchdisconnect.txt](https://github.com/SirPlease/L4D2-Competitive-Rework/files/5899195/autoban_matchdisconnect.txt)
