### ISSUE TITLE
readyup does not work on my server

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#244]
What could cause that ? 

L 02/02/2021 - 12:19:38: [SM] Exception reported: Invalid convar handle 0 (error 4)
L 02/02/2021 - 12:19:38: [SM] Blaming: readyup.smx
L 02/02/2021 - 12:19:38: [SM] Call stack trace:
L 02/02/2021 - 12:19:38: [SM]   [0] GetConVarInt
L 02/02/2021 - 12:19:38: [SM]   [1] Line 646, plugin.sp::UpdatePanel
L 02/02/2021 - 12:19:38: [SM]   [2] Line 765, plugin.sp::InitiateReadyUp
L 02/02/2021 - 12:19:38: [SM]   [3] Line 548, plugin.sp::RoundStart_Event

**Comment by SirPlease** [comment]
`GetConVarInt(FindConVar("sv_maxplayers")`
sv_maxplayers is added by L4DToolz in this install, so you don't have it setup properly.

**Comment by lunatixxx** [comment]
Ah i think it is because the server i pay for is reseting the value or something like that, will see if i can fix it. thanks

**Comment by lunatixxx** [comment]
Hum I would like to use the vanilla tiebreaker score but it looks like it is broken with readyup plugin, does there is something i can change to fix it ?

**Comment by SirPlease** [comment]
Not related to readyup, the tiebreaker is only modified in the score plugins (Scoremod.sp module for confogl if you're using the module, l4d2_scoremod.smx, l4d2_hybrid_scoremod)
