### ISSUE TITLE
c1m4 unreachable gas cans

### ISSUE THREAD

**Issue by Derpduck** [SirPlease/L4D2-Competitive-Rework#245]
Blocks gas cans from being launched into _**most**_ unreachable locations:
* Entire 4th floor
* Behind the walls at gas can sets by the saferoom and elevator on the 3rd floor

Gas cans can still end up being unreachable in other locations, but this blocks most of them.

Up for debate as to if this should be added or not.

```
add:
; --- Block gas cans from reaching the 4th floor with func_clip_vphysics
{
	"classname" "func_clip_vphysics"
	"origin" "1088 -1248 832"
	"model" "*157"
	"filtername" "filter_gascan"
}
{
	"classname" "func_clip_vphysics"
	"origin" "-1024 -1248 832"
	"model" "*157"
	"filtername" "filter_gascan"
}
; --- Additional blocking behind the existing clips on the 3rd floor as gascans with enough speed can clip through them
{
	"classname" "func_clip_vphysics"
	"origin" "2192 -3168 600"
	"model" "*157"
	"filtername" "filter_gascan"
}
{
	"classname" "func_clip_vphysics"
	"origin" "-3864.5 -3284.55 104.87"
	"model" "*121"
	"filtername" "filter_gascan"
}
{
	"classname" "func_clip_vphysics"
	"origin" "-3752.5 -3284.55 104.87"
	"model" "*121"
	"filtername" "filter_gascan"
}
```

**Comment by SirPlease** [comment]
Do these not interfere with the current c1m4 changes?

**Comment by Derpduck** [comment]
No, the current changes only block gas cans from going behind or on top of some of the store fronts on floors 1-3. These changes can be added on to them, it basically just blocks the entire 4th floor.
