### ISSUE TITLE
Fix CCS weapons (Request)

### ISSUE THREAD

**Issue by oethanx** [SirPlease/L4D2-Competitive-Rework#246]
Hello, maybe fix the knife and awp that got really nerfed once they were officially implemented into the game along with the last stand update?

The awp feels really weak as compared it how it was. The same goes for the knife, it's hitbox is really weird and hard to hit even common infected + swing rate has been reduced

**Comment by SirPlease** [comment]
The project is not intended to "fix" Vanilla gameplay.
The AWP isn't used by anything in this Github.
The knife isn't that big of a deal, I don't think it's possible for us to modify its hitbox.

**Comment by Derpduck** [comment]
FYI It's possible to change the swing direction back to it's pre-update state by editing the weapon.txt file.
```
		"slash1"
		{
			"startdir"		"W"
			"enddir"		"E"
```
Was changed to:
```
		"slash1"
		{
			"startdir"		"W"
			"enddir"		"SE"
```
In the update.
