### ISSUE TITLE
confogl_addcvar confogl_blockinfectedbots "0"

### ISSUE THREAD

**Issue by Mobaxiaolvre** [SirPlease/L4D2-Competitive-Rework#248]
It's still 1v5

**Comment by SirPlease** [comment]
I have no idea what you're trying to say, please elaborate?

**Comment by Mobaxiaolvre** [comment]
I want to play a person's confrontation mode, AI special infection can't generate

**Comment by SirPlease** [comment]
This has nothing to do with this repository.
