### ISSUE TITLE
!setscores valves / print reversed depending on team order

### ISSUE THREAD

**Issue by Derpduck** [SirPlease/L4D2-Competitive-Rework#249]
When the "first" survivor team is losing in points after a map change, causing them to start a round as the infected first, the !setscores command sets the scores the wrong way around, but still prints it as if it set the values correctly.
An example scenario:
* Team A started as survivor on the first map, team B started as infected.
* Team B wins that map, so team A starts on infected next map.
* Member of team A votes to set the scores like so: `!setscores 500 100` - where the first value should be the current survivor team (team B) and the 2nd value is the current infected team (team A)
* The chat print will show as: `Scores set to 500  (Sur) - 100  (Inf) by Name.`
* The actual scores will be set to 100 points for current survivor team (team B), and 500 for infected team (team A).

**Comment by SirPlease** [comment]
The scores are set correctly, it requires a round switch for them to update properly.
