### ISSUE TITLE
Tank props should take a few more seconds to fade

### ISSUE THREAD

**Issue by ProdigySim** [SirPlease/L4D2-Competitive-Rework#251]
Feature request. After tank dies, props disappear pretty quickly even if they are still in motion. It would be nice to let them survive a little longer, or settle before being removed.

We got an example in a match perhaps!

https://clips.twitch.tv/GiftedGeniusHamsterSeemsGood-9dFzCUrO5DvcUXzq

**Comment by SirPlease** [comment]
Added with Zonemod 1.9.15 commit.
