### ISSUE TITLE
c4m1 ladder skip

### ISSUE THREAD

**Issue by Derpduck** [SirPlease/L4D2-Competitive-Rework#254]
It's possible to skip the ladder before the playground on Hard Rain 1 by jumping on the pickup truck on 100 tick.

Fix: https://github.com/Derpduck/L4D2-Comp-Stripper-Rework/blob/master/cfg/stripper/maps/c4m1_milltown_a.cfg#L274
Since the map is in RBTV it's worth adding the fix just in case, and just to stop it getting abused in pugs a lot too.

**Comment by SirPlease** [comment]
Done~
