### ISSUE TITLE
Tank HUD ping display is halved

### ISSUE THREAD

**Issue by Derpduck** [SirPlease/L4D2-Competitive-Rework#257]
https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/spechud.sp#L881

Ping value from GetClientAvgLatency is multiplied by 500 instead of 1000, resulting in all pings displayed on the HUD being halved.

**Comment by SirPlease** [comment]
Good catch, I didn't have time to go over it yet.. will do so now!
