### ISSUE TITLE
Rock hitbox is smaller in saferooms

### ISSUE THREAD

**Issue by Derpduck** [SirPlease/L4D2-Competitive-Rework#258]
Rock hitboxes do not have any "extended" range on their hitbox when going near survivors that are within saferooms, instead they only hit survivors when the actual model directly hits a survivor.
This can lead to a lot of unexpected rock misses and is a feature that often gets overlooked/forgotten about by players since it rarely comes into play.

I suspect this may exist to compensate for tanks not losing rage while survivors are in saferoom in vanilla.

**Comment by SirPlease** [comment]
It's probably related to the reason why spit puddles are so unreliable in saferooms as well. Probably projectile issues.
