### ISSUE TITLE
Error executing the script "sudo chmod + x /etc/init.d/srcds1"

### ISSUE THREAD

**Issue by chems315** [SirPlease/L4D2-Competitive-Rework#259]
Hello, I followed the steps of your guide to load the left in my VPS, but it gives me an error in this script:
_steam@·······:~$ sudo chmod +x /etc/init.d/srcds1 restart
chmod: cannot access 'restart': No such file or directory_

I followed all your guide to the letter, but still nothing, if you could help me I would appreciate it very much.

**Comment by x-xoxo** [comment]
`/etc/init.d/srcds1 restart` is NOT a file so you have to execute following code : `sudo chmod +x /etc/init.d/srcds1`

**Comment by chems315** [comment]
@x-xoxo So how do I apply reset, start and stop?

**Comment by SirPlease** [comment]
> @x-xoxo So how do I apply reset, start and stop?

`Chmod +x` sets permission rights on the file.
Restart, stop and start are commands, once you've set permissions on the file, then you can use the commands.

Once you've used `sudo chmod +x /etc/init.d/srcds1`, you can use `sudo /etc/init.d/srcds1 restart`.

**Comment by chems315** [comment]
I get this:
root@×××××:~# sudo chmod +x /etc/init.d/srcds1
root@×××××:~# sudo /etc/init.d/srcds1 start
sudo: unable to execute /etc/init.d/srcds1: No such file or directory
Hangup
