### ISSUE TITLE
About c7m3_port pipebomb spawn

### ISSUE THREAD

**Issue by Target5150** [SirPlease/L4D2-Competitive-Rework#26]
I have dump that 3 pipebomb ,use ent_dump command:
] ent_fire !picker addoutput "targetname 1"
] ent_dump 1
  count: 1
  classname: weapon_pipe_bomb_spawn
  effects: 16
  friction: 1.00
  glowbackfacemult: 1.00
  spawnflags: 32768

] ent_fire !picker addoutput "targetname 2"
] ent_dump 2
  count: 1
  classname: weapon_pipe_bomb_spawn
  effects: 16
  friction: 1.00
  glowbackfacemult: 1.00
  spawnflags: 32768

] ent_fire !picker addoutput "targetname 3"
] ent_dump 3
  count: 1
  classname: weapon_pipe_bomb_spawn
  effects: 16
  friction: 1.00
  glowbackfacemult: 1.00
  spawnflags: 32768

So I suggest add 1 fliter in c7m3_port stripper:
filter:
{
	"classname" "weapon_pipe_bomb_spawn"
}

But I'm not sure that stable or not ,just restart many times and slay survivor to Round 2 to test it.Then don't have saw the pipe spawn again.
(If no fliter,about 3-7 times restart maybe spawn the pipebomb)

And I saw the Nextmod put this fliter in global_fliter,if worry about other map have any same problem.it should put in global_fliter that I think.

**Comment by SirPlease** [comment]
Fixed in [Update v0.4](https://github.com/SirPlease/L4D2-Competitive-Rework/commit/ea05d57ebed772462ba1a2865142a2bccabb981a)
Thanks for reporting! 👍
