### ISSUE TITLE
scavenge bug

### ISSUE THREAD

**Issue by lechuga16** [SirPlease/L4D2-Competitive-Rework#261]
hi, i have been reconditioning the scavogl cfg and i have a problem that happens also in sirpls. When I start a game on the c7m2_barge map, the survivors start on the default saferoom of coop / versus.
this can be reproduced even in vanilla, without loading confogl.

I wanted to ask for a little help.

**Comment by SirPlease** [comment]
It's not a bug, it's the way the addon works.
In the project's current state we use thesaccing_v2.vpk to setup the a merge of The Passing and The Sacrifice, which impacts everything on the server.

Not ideal, and should be reworked with a modification of an old plugin.

**Comment by lechuga16** [comment]
thank you so much.

**Comment by Derpduck** [comment]
thesaccing_v2.vpk should support all gamemodes for all maps correctly. How are you starting the map, from the lobby or by voting in game?

**Comment by lechuga16** [comment]
I did 2 tests, first I started scaogl while on the server, thinking that maybe it is a cfg problem, I used lobby to connect to the server and the problem occurred without loading any game mode.

**Comment by Derpduck** [comment]
Did some testing, I think I know what the problem is.
Because the campaign is based on The Passing, it uses the L4D2 survivors. The spawn points for survivors are based on the survivor's name. Since the spawn points only name the L4D1 survivors the L4D2 survivors won't spawn there, the same issue happens on c7m1.

It should be fixable, though the ideal solution would be using a plugin for the map transition between c6m2 and c7m1 which would prevent any other issues like this.

**Comment by Derpduck** [comment]
Try adding the following to your Stripper:Source config for c7m1 and c7m2, this should fix the issue.

c7m1_docks.cfg
```
add:
; --- Fix scavenge spawn positions when using thesaccing addon, as the spawn points use the L4D1 survivor names but the addon spawns L4D2 survivors
{
	"classname" "info_survivor_position"
	"origin" "6089.54 342.04 146.017"
	"angles" "0 195 0"
	"targetname" "scavenge_position3"
	"SurvivorName" "Rochelle"
	"Order" "1"
	"GameMode" "scavenge"
}
{
	"classname" "info_survivor_position"
	"origin" "6077.26 256.76 149.017"
	"angles" "0 195 0"
	"targetname" "scavenge_position4"
	"SurvivorName" "Ellis"
	"Order" "1"
	"GameMode" "scavenge"
}
{
	"classname" "info_survivor_position"
	"origin" "6147.4 267.4 150.017"
	"angles" "0 180 0"
	"targetname" "scavenge_position2"
	"SurvivorName" "Nick"
	"Order" "1"
	"GameMode" "scavenge"
}
{
	"classname" "info_survivor_position"
	"origin" "6139.4 315.4 149.017"
	"angles" "0 180 0"
	"targetname" "scavenge_position1"
	"SurvivorName" "Coach"
	"Order" "1"
	"GameMode" "scavenge"
}
```

c7m2_barge.cfg
```
add:
; --- Fix scavenge spawn positions when using thesaccing addon, as the spawn points use the L4D1 survivor names but the addon spawns L4D2 survivors
{
	"classname" "info_survivor_position"
	"origin" "-3209.14 269.716 2.08984"
	"angles" "0 195 0"
	"targetname" "scavenge_position4"
	"SurvivorName" "Ellis"
	"Order" "1"
	"GameMode" "scavenge"
}
{
	"classname" "info_survivor_position"
	"origin" "-3139 280.356 2.08984"
	"angles" "0 180 0"
	"targetname" "scavenge_position2"
	"SurvivorName" "Nick"
	"Order" "1"
	"GameMode" "scavenge"
}
{
	"classname" "info_survivor_position"
	"origin" "-3147 328.356 2.08984"
	"angles" "0 180 0"
	"targetname" "scavenge_position1"
	"SurvivorName" "Coach"
	"Order" "1"
	"GameMode" "scavenge"
}
{
	"classname" "info_survivor_position"
	"origin" "-3196.86 354.997 4.08984"
	"angles" "0 195 0"
	"targetname" "scavenge_position3"
	"SurvivorName" "Rochelle"
	"Order" "1"
	"GameMode" "scavenge"
}
```

**Comment by lechuga16** [comment]
it worked, thanks a lot for the help. https://github.com/lechuga16/scavogl_rework/commit/393eae6d035c9537495f0cb2a653fd13868fb331
