### ISSUE TITLE
c5m5 common limits are not respected in 1v1

### ISSUE THREAD

**Issue by lechuga16** [SirPlease/L4D2-Competitive-Rework#266]
as a test change some commands to test if it could spawn a minimum amount, but it did not respect them. 
z_common_limit 1
z_mega_mob_size 1
z_mob_spawn_min_size 1
z_mob_spawn_max_size 1 

Is the problem only on the servers that I handle or is it something in general?.

![20210505122007_1](https://user-images.githubusercontent.com/34782281/117174965-4f304900-ad9c-11eb-8fbc-db28ba8b42ef.jpg)

**Comment by vikingo12** [comment]
how did you solve it?
