### ISSUE TITLE
double load l4d2_melee_fix.smx 

### ISSUE THREAD

**Issue by Electr0** [SirPlease/L4D2-Competitive-Rework#27]
you moved plugin in plugins folder, may be delete older path from these configs (and files from config subfolders)
![4534534](https://user-images.githubusercontent.com/2865025/64470925-2c333900-d164-11e9-85de-95ab8b6eb5d1.PNG)

**Comment by SirPlease** [comment]
Fixed in [Update v0.5](https://github.com/SirPlease/L4D2-Competitive-Rework/commit/3231095ca95a653233fae0d254863cfd90737cbd)
