### ISSUE TITLE
Tank spawn announcement only occurs on first tank

### ISSUE THREAD

**Issue by Derpduck** [SirPlease/L4D2-Competitive-Rework#270]
https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/l4d2_tank_announce.sp

`g_bIsTankAlive` is never set to false after the first tank is spawned and killed/kicked, so any maps with multiple tank spawns (every finale) do not get an announcement when the next tank spawns.

**Comment by SirPlease** [comment]
You'd imagine someone would've reported this by now, especially after all the tournaments.. 😆
