### ISSUE TITLE
type ! not show in the chat?

### ISSUE THREAD

**Issue by 852-pan0s** [SirPlease/L4D2-Competitive-Rework#272]
How to enable showing "!" in the chat?
e.g. !buy

**Comment by vikingo12** [comment]
remove bequiet plugin

**Comment by SirPlease** [comment]
@vikingo12 is correct, simply don't load the plugin for an easy fix.

If you'd however want to keep the rest of the plugin's functionality, you could modify the bequiet plugin.
Change [this line](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/3a67c5daa2e38f220f22ae3d40b27be36da0c69c/addons/sourcemod/scripting/bequiet.sp#L51) to `if(sayWord[0] == '/')`
