### ISSUE TITLE
l4d_weapon_limits bugs

### ISSUE THREAD

**Issue by Derpduck** [SirPlease/L4D2-Competitive-Rework#275]
This plugin has some bugs around players being incapped/dying.
Not sure on the exact causes because there isn't a single comment in the code explaining it but the culprit seems to be this line
https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/l4d_weapon_limits.sp#L217

When a player with a melee weapon is incapped, the plugin counts 1 extra of each weapon as being held. In a scenario where the team has 2 shotguns and 2 uzis this brings both limits up to 3 and makes it impossible for anyone to pick up a weapon until the player has been revived.

If a player with a melee weapon is incapped and then dies, `bIsIncappedWithMelee[client]` is never reset so there will permanently be 1 less slot for all limits.

Players carrying the magnum also have some strange interactions with this but this needs more testing.

**Comment by A1mDev** [comment]
I also noticed something similar, while readyup something similar also happened (it was impossible to take 3 shotgun).

**Comment by vikingo12** [comment]
I thought I was the only one with this issue, now hoping for fix!
