### ISSUE TITLE
How to allow player connect my server by hosting "Best Available le Dedicated?"

### ISSUE THREAD

**Issue by 852-pan0s** [SirPlease/L4D2-Competitive-Rework#278]
Just like the image,
![l4d2_server](https://user-images.githubusercontent.com/51123243/119255798-26a7ac00-bbf0-11eb-84da-0d31ee0b5016.jpg)

Did it disable?

**Comment by SirPlease** [comment]
If you want to make your server be accessible by anybody, simply remove "sv_steamgroup_exclusive 1" from the `cfg/server.cfg`, as it defaults to "0".
You can also just change it to "0" of course.

**Comment by 852-pan0s** [comment]
Thanks!
