### ISSUE TITLE
l4d_BossPercent problem

### ISSUE THREAD

**Issue by MasterBlaster89** [SirPlease/L4D2-Competitive-Rework#279]
Hello, on every cfg with witch l4d2_bosspercent shows "None". Witch spawns but plugins dont see her. Any clues what is wrong ? Tank % works normally. Error logs clean.

MetaMod:Source v1.11.0-dev+1125V, Stripper v1.2.2, SourceMod v1.10.0.6490
Ubuntu 16 same on 18

**Comment by SirPlease** [comment]
I've not been able to reproduce this, I've loaded Promod Elite and EQ on multiple maps with multiple restarts and not once did it say "None" for the Witch.

Are you sure your install is up to date with the repository?

**Comment by SirPlease** [comment]
Unable to reproduce, no further replies.
