### ISSUE TITLE
l4d2_getup_slide_fix.sp is broken

### ISSUE THREAD

**Issue by Electr0** [SirPlease/L4D2-Competitive-Rework#28]
you replace old check by IsValidInfected
and you valid survivors instead infected, infected teamnum is 3.
`
stock bool IsValidInfected(int client) 
{ 
	if (client <= 0 || client > MaxClients) return false;
	
        if (!IsClientConnected(client) || !IsClientInGame(client)) return false; 
	
        return GetClientTeam(client) == 2;
} 
`

**Comment by SirPlease** [comment]
Big derp, was working on too many things at once. :yum:

**Comment by SirPlease** [comment]
Fixed in [Update v0.5](https://github.com/SirPlease/L4D2-Competitive-Rework/commit/3231095ca95a653233fae0d254863cfd90737cbd)
