### ISSUE TITLE
If you're on the ladder, you get a stagger bug

### ISSUE THREAD

**Issue by A1mDev** [SirPlease/L4D2-Competitive-Rework#284]
if you are shoved when you are on the ladder then you will not be able to move anymore until you are killed. This problem is related to the staggersolver.smx plugin. The stagger timer (the check that is called via the sdkcall) never expires when the player is on the ladder. The simplest fix in this case is, add a check on 'GetEntityMoveType(client) != MOVETYPE_LADDER' in this plugin.

**Comment by SirPlease** [comment]
https://github.com/SirPlease/L4D2-Competitive-Rework/pull/285
