### ISSUE TITLE
l4d2_car_alarm_hittable_fix.smx never loaded in configs

### ISSUE THREAD

**Issue by Electr0** [SirPlease/L4D2-Competitive-Rework#29]
why?)

in changelog:
Alarm Hittable Fix to new Syntax and to also take possible other Alarm Cars hitting them into account. (+ Added to GeneralFixes)

just forgot version

**Comment by SirPlease** [comment]
It's moved to GeneralFixes, or rather it was supposed to.  💯

**Comment by SirPlease** [comment]
Fixed in [Update v0.5](https://github.com/SirPlease/L4D2-Competitive-Rework/commit/3231095ca95a653233fae0d254863cfd90737cbd)
