### ISSUE TITLE
Some issues in recent upgrade

### ISSUE THREAD

**Issue by A1oneR** [SirPlease/L4D2-Competitive-Rework#291]
It seems that the tank will not always spawn in map and the witch will randomly spawn in map.
The scoremod may not work for now.
Sometimes survivors will not receive damage done by commons or some infected.

I don't know the problems come from whether the new l4d2 upgrade or just the mistakes done by myself.
And the plugins are worked well before the l4d2 upgrade.

**Comment by A1mDev** [comment]
+1, scoremod not working correctly lol (R#2 Bonus: 1823122432 <165738400.0%> [HB: 54% | DB: 729248768% | Pills: 100%])

**Comment by vikingo12** [comment]
gosh no dmg from infected

**Comment by SirPlease** [comment]
Godframes are fixed in latest push, I haven't had any problems with the Tank not spawning on the build on this Github repo.
Scoremod is indeed not working correctly, related to outdated offsets for `m_preIncapacitatedHealthBuffer`

**Comment by A1mDev** [comment]
l4d2_notankautoaim.smx does not work

**Comment by SirPlease** [comment]
Resolved with #302
