### ISSUE TITLE
boomer ladder issues

### ISSUE THREAD

**Issue by ProjectSky** [SirPlease/L4D2-Competitive-Rework#294]
I noticed that if boomer is close the ladder in the air, it will be push back by the ladder.

![boomer](https://user-images.githubusercontent.com/16351827/122530939-9bd09a80-d051-11eb-94c1-0ea08a65a5f7.gif)

![charger](https://user-images.githubusercontent.com/16351827/122530966-a25f1200-d051-11eb-8b8c-388658143fd3.gif)

**Comment by SirPlease** [comment]
The boomer is wider, legitimately why this issue occurs on the boomer.

**Comment by A1mDev** [comment]
I think sir still has other problems after the update. :D It is a old problem l4d2. To fix this I think would require some complicated code using game tracing and very performance impacting, but is it really that important and worrying?

**Comment by ProjectSky** [comment]
it’s not a big issues, but it’s annoying, jump from the air but stuck to the ladder

**Comment by A1mDev** [comment]
and it's unlikely that code like this will know when you want to jump up the stairs and spawn, and the sire is right, boomers have more hitboxes. I guess there is some kind of trace that checks if you are touching the stairs or not and asks for the GetPlayerMaxs () and GetPlayerMins () functions. You can check this by applying the code to the boomer and other characters if you like:
float min[3], max[3]
GetEntPropVector (client, Prop_Send, "m_vecMins", min);
GetEntPropVector (client, Prop_Send, "m_vecMaxs", max);

**Comment by A1mDev** [comment]
Or we can try to change what the GetPlayerMins() function returns, exactly in the function that checks whether you are on the ladder or not (for boomers), but this problem I think will wait.=)

**Comment by fbef0102** [comment]
[Boomer Ladder Fix](https://forums.alliedmods.net/showthread.php?t=335948) by BHaType

**Comment by SirPlease** [comment]
> [Boomer Ladder Fix](https://forums.alliedmods.net/showthread.php?t=335948) by BHaType

Yup, saw it earlier today, didn't have time to test it though.
Just got to testing it and it seems to be working great :)

**Comment by ProjectSky** [comment]
after a few days of testing, this [plugin](https://forums.alliedmods.net/showthread.php?t=335948) solved issues, thx everyone help
