### ISSUE TITLE
l4d_tank_damage_announce.sp compile issues

### ISSUE THREAD

**Issue by kitaynoctis** [SirPlease/L4D2-Competitive-Rework#295]
l4d_tank_damage_announce.sp(355) : error 234: symbol "FloatMul" is marked as deprecated: This native is internal implementation. For multiplication use the '*' operator.
l4d_tank_damage_announce.sp(360) : error 234: symbol "FloatMul" is marked as deprecated: This native is internal implementation. For multiplication use the '*' operator.

_SourcePawn Compiler 1.11.0.6526_

**Comment by vikingo12** [comment]
These are just warnings

**Comment by ProjectSky** [comment]
```cpp
int GetDamageAsPercent(int damage)
{
	return RoundToNearest(damage / g_fMaxTankHealth * 100.0);
}

bool IsExactPercent(int damage)
{
	return (FloatAbs(GetDamageAsPercent(damage) - (damage / g_fMaxTankHealth) * 100.0) < 0.001) ? true : false;
}
```

**Comment by kitaynoctis** [comment]
> ```c++
> int GetDamageAsPercent(int damage)
> {
> 	return RoundToNearest(damage / g_fMaxTankHealth * 100.0);
> }
> 
> bool IsExactPercent(int damage)
> {
> 	return (FloatAbs(GetDamageAsPercent(damage) - (damage / g_fMaxTankHealth) * 100.0) < 0.001) ? true : false;
> }
> ```

cool！it work,thanks.

**Comment by A1mDev** [comment]
I think you have an inaccuracy here, you forgot to add the conversion to the float type, this is needed to compare the data type of the float and the data type of int, how much they will differ when rounding, in order to correct the information output, otherwise this code doesn't make sense, correct if I'm wrong.

It needs to be done like this:




```bsl
bool IsExactPercent(int damage)
{
	float fDamageAsPercent = (damage / g_fMaxTankHealth) * 100.0;
	float fDifference = float(GetDamageAsPercent(damage)) - fDamageAsPercent;
	return (FloatAbs(fDifference < 0.001) ? true : false;
}

```

**Comment by SirPlease** [comment]
Pushed with a correct fix, thanks!
