### ISSUE TITLE
Rock skeet print when rock isn't skeeted

### ISSUE THREAD

**Issue by Derpduck** [SirPlease/L4D2-Competitive-Rework#298]
Rock skeet print will be sent if the rock has taken damage and then hits a player.

At this line it checks if the rock has taken damage before it was destroyed, which is used to determine if the print is shown or not.
https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/l4d2_skill_detect.sp#L1794

This hook is supposed to check when rocks break by hitting an object, but it only triggers when rocks hit the world or infected, It does not trigger when hitting survivors.
This is supposed to set the last damage the rock takes to -1, causing the above check to fail.
https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/l4d2_skill_detect.sp#L2120

**Comment by A1mDev** [comment]
Old bug, the stone also has a hp, probably the player does less damage than the stone has hp, so it writes to the chat, and the players yell that the server is bad.

**Comment by jensewe** [comment]
https://forums.alliedmods.net/showthread.php?p=2648989
Worth looking into.

https://github.com/Target5150/MoYu_Server_Stupid_Plugins/commit/28bd4524585d16aa1b08609c33caa33b2cb9d65b
This one is my modified version of `l4d2_skill_detect`, credits to the above plugin.
Just tested it with original one loaded, and it seemed to make a difference.
