### ISSUE TITLE
server_namer.txt missing in config folder results in server_namer.smx not working

### ISSUE THREAD

**Issue by justtheletterjwithadot** [SirPlease/L4D2-Competitive-Rework#3]
**Issue:**
> L 08/03/2019 - 15:03:38: [SM] Exception reported: configs/server_namer.txt not found!
> L 08/03/2019 - 15:03:38: [SM] Blaming: server_namer.smx
> L 08/03/2019 - 15:03:38: [SM] Call stack trace:
> L 08/03/2019 - 15:03:38: [SM]   [0] SetFailState
> L 08/03/2019 - 15:03:38: [SM]   [1] Line 90, C:\Users\Sir\Desktop\Scripting\sourcemod\scripting\server_namer.sp::OnPluginStart
> L 08/03/2019 - 15:03:38: [SM] Unable to load plugin "server_namer.smx": Error detected in plugin startup (see error logs)

**Resolution:**
Adding [server_namer.txt](https://github.com/SirPlease/ZoneMod/blob/master/addons/sourcemod/configs/server_namer.txt) file from [ZoneMod](https://github.com/SirPlease/ZoneMod)

**Comment by SirPlease** [comment]
Server Namer would be a prime example of what would go into sharedplugins, as it's not a general fix nor should it be a config thing.
Appreciate the issue reporting so far, clear and precise :)
