### ISSUE TITLE
Wrong static_tank_map name

### ISSUE THREAD

**Issue by Target5150** [SirPlease/L4D2-Competitive-Rework#30]
In your update v0.5.1 around old version Diescraper , only mapinfo.txt & stripper have been done, while cfg left incompleted . Shared_setting.cfg(confogl.cfg in pmelite) in configs still wrote:

> static_tank_map l4d2_diescraper4_top_34
> finale_tank_default l4d2_diescraper4_top_34   <---Only promod elite

In eq、Promod elite、Apex

It should be change to

> static_tank_map l4d2_diescraper4_top_361
> finale_tank_default l4d2_diescraper4_top_361   <---Only promod elite

**Comment by SirPlease** [comment]
Fixed in [Update v0.5.2](https://github.com/SirPlease/L4D2-Competitive-Rework/commit/f1574bdb09b63b9f4f322a49f96ec67ff1d6a181)
