### ISSUE TITLE
Remove * from pmelite/confogl_plugins.cfg at 112 line

### ISSUE THREAD

**Issue by Electr0** [SirPlease/L4D2-Competitive-Rework#31]
https://github.com/SirPlease/L4D2-Competitive-Rework/blob/cc72695c0fa5a48ae05df93f990947873bba70c3/cfg/cfgogl/pmelite/confogl_plugins.cfg#L112

**Comment by SirPlease** [comment]
Fixed in [Update v0.5.2](https://github.com/SirPlease/L4D2-Competitive-Rework/commit/f1574bdb09b63b9f4f322a49f96ec67ff1d6a181)
