### ISSUE TITLE
blood harvest stripper

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#313]
Does not load only on this whole campaign, was working before last l4d update. stripper-1.2.2-git129-linux.

**Comment by SirPlease** [comment]
It works fine, I believe you still have the addon fix we used to have in the repo to fix lowercase and uppercase issues on this map alone. Get rid of it and it will work fine for you. :)

**Comment by lunatixxx** [comment]
Just tested with a C uppercase and it works.
