### ISSUE TITLE
new ready up starting bug

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#314]
On all first chapter of versus it does not load on first round, only appear for second round. No problem with other maps. Any idea?

**Comment by A1mDev** [comment]
see sourcemod errors =/

**Comment by lunatixxx** [comment]
no error

**Comment by lunatixxx** [comment]
I think this is because of the auto start function as the first loading is long sometimes when you launch from lobby but it considere players have already loaded.

**Comment by A1mDev** [comment]
I think yes, I didn’t see this by the way, they added something quietly =))

**Comment by lunatixxx** [comment]
I am not sure where to put it i didn't really look into it, but something like that should fix it: HookEvent("item_pickup", Event_RoundStartAndItemPickup, EventHookMode_Pre);

**Comment by SirPlease** [comment]
In what context do you use the readyup plugin? Do you use it with competitive configs or outside of it?

**Comment by lunatixxx** [comment]
Autostart of readyup + start from lobby. If someone joined late in the loading it last like 1 minute and the round already started when we arrive on the server. Not really a bug more a flaw.

**Comment by vikingo12** [comment]
@lunatixxx return to the old version of plugin which works perfectly

**Comment by SirPlease** [comment]
> Autostart of readyup + start from lobby. If someone joined late in the loading or left or even have a slow pc it last like 1 minute and the round already started when we arrive on the server. Not really a bug more a flaw.

Yeah, I think for the purposes the autostart was added it won't happen in a loaded config (because we restart the map on config load and players aren't required to all fully load it again.
I'll mark this as Enhancement for now, but hopefully you can understand that I won't put this as something high priority.

> @lunatixxx return to the old version of plugin which works perfectly

Worst solution ever, especially considering the old one doesn't have the functionality he wishes to use.

**Comment by lunatixxx** [comment]
Just noticed that this is cause starting_items to not give anything to the players on the first round, just going to disable auto start for now.

**Comment by jensewe** [comment]
https://github.com/Target5150/MoYu_Server_Stupid_Plugins/tree/master/The%20Last%20Stand/readyup
Could you please try this version? I might not be able to get it reproduced.

**Comment by SirPlease** [comment]
Is this still an issue? @lunatixxx

**Comment by lunatixxx** [comment]
I switched to the normal mode definitively so i don't know.

**Comment by SirPlease** [comment]
Thanks for the reply, did my own digging.. should've done that right away 🤡
