### ISSUE TITLE
The Tickrate_enable made server crash

### ISSUE THREAD

**Issue by A1oneR** [SirPlease/L4D2-Competitive-Rework#317]
Nice L4D2 Update, can't wait for the interesting 30T server.
Anyway,I will keep the attention to the update of the tickrate_enable.

**Comment by A1oneR** [comment]
Also the Left4Dhooks.smx has some signature errors.
"ForceNextStage" and "UseHealingItems"

**Comment by SirPlease** [comment]
Resolved~ (:
