### ISSUE TITLE
Detour Ahead final bug

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#326]
Did 3 attempts and each time there is an invisible wall blocking the entry to go inside the chopper to escape, it never go away making it impossible to finish the map. I am 100% sure that this is something inside the stripper config of zonemod as without it it does not happen.

Map version 8 finale.

**Comment by Derpduck** [comment]
Are you playing the map in campaign or versus? It should work fine in versus.

**Comment by lunatixxx** [comment]
I tested it in campaign still i don't think it should break for coop it does not happens with other maps. Maybe add the modification fo versus only if possible.

`filter:
{
	"classname" "func_brush"
	"targetname" "surv_helireplace"
}
; --- Make props solid
modify:
{
	match:
	{
		"classname" "prop_dynamic"
		"targetname" "surv_helireplace"
	}
	replace:
	{
		"solid" "6"
	}
}`

I guess it is that.
