### ISSUE TITLE
return to the spectator

### ISSUE THREAD

**Issue by QoQman** [SirPlease/L4D2-Competitive-Rework#329]
Connected people are forced to spectator.
Even if the spectator chooses a survivor or Infected, he will be returned to the spectator immediately.
So can't play games.
Do i need to set anything

[GAMEMODE]
ZoneMod v2.2

I'm sorry I'm not very good at English

**Comment by SirPlease** [comment]
It tells you in chat why.
The default setting is to have `cl_interp` be 0.067 at most. (The game's default value is 0.1)

**Comment by vikingo12** [comment]
if thats gonna be the case then I always wondered how blind people look like

**Comment by QoQman** [comment]
Thank you SirPlease.
We were able to play.

But another problem came up.
The number of opponents will be 4/4 server and you will not be able to connect if you exceed 4 people.
How can I change the number of players to 8/8?

**Comment by QoQman** [comment]
This issue has been resolved.
Thank you SirPlease.
