### ISSUE TITLE
Item tracking module

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#330]
Something is wrong with it for me at least, there are no items spawns outside of saferoom already on first round when i activate it even with unlimited items. I have the impression that it kills items before the first round is starting and considering that it did not add any in the array to track well nothing is spawning.

enable_itemtracking 1
itemtracking_savespawns 1
itemtracking_mapspecific 0
pills_limit -1
pipebomb_limit -1
molotov_limit -1
vomitjar_limit -1

**Comment by Derpduck** [comment]
Remove the following section from your global_filters.cfg file https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/cfg/stripper/zonemod/global_filters.cfg#L1100

**Comment by lunatixxx** [comment]
I don't have these lines this is something else.

**Comment by lunatixxx** [comment]
Also there are no errors.

Why the "EnumAndElimSpawns" is called at the end of the first round, is it not supposed to be at the start of the round?

''
if(!g_bIsRound1Over)
	{
		// Round1
		if(IsModuleEnabled())
		{
			EnumAndElimSpawns();
		}
	}
''

Then just after the plugin ask to generate stored items spawns if this is not the round end event (still no items in the list), is it not the reason there are no items spawn ?

''
else
	{
		// Round2
		if(IsModuleEnabled())
		{
			if(UseConsistentSpawns())
			{
				GenerateStoredSpawns();
			}
			else
			{
				EnumAndElimSpawns(); 
			}
		}
	}
''

Maybe i'm weong but something seems weird.

**Comment by lunatixxx** [comment]
Was basically the same problem that i reported for witch_and_tankifier, you're forced to load a config otherwise it does not find the mapinfo even if i had the defaut config folders.
