### ISSUE TITLE
[Request] Tank hud source

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#332]
I found that but this is an old version with lot of missing things: https://github.com/MatthewClair/sourcemod-plugins/blob/master/tank_hud/tank_hud.sp

**Comment by jensewe** [comment]
Built in spechud.

**Comment by lunatixxx** [comment]
"Provides different HUDs for spectators" 

I was talking about the hud that the SI team see when there is a tank. is it included ?

**Comment by A1mDev** [comment]
Yes, look [here ](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/spechud.sp#L669) and [here](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/spechud.sp#L1104) =)

**Comment by lunatixxx** [comment]
There are missing source inc files by the way.

**Comment by jensewe** [comment]
Some include files are considered redundant and removed in latest update.
I've updated it to make use of `l4d2util` in my coop repo that hasn't been pushed to here. Will make it into PR soon :)
