### ISSUE TITLE
Weapon changes on the map

### ISSUE THREAD

**Issue by QoQman** [SirPlease/L4D2-Competitive-Rework#333]
Hello
Let me questions

I can not do English.
I'm not good at programming.

I would like to add a hunting rifle to the zonemod.
That's why I made these changes.

cfg/cfgogl/zonemod/zonemod.cfg
39th line
l4d_wlimits_add 1 1 weapon_hunting_rifle

cfg/stripper/zonemod/global_filters.cfg
Removed line 211 from line 197
Removed line 400 from line 390

cfg/stripper/zonemod/maps/c2m1_highway.cfg
Added to line 42
{
    "classname" "weapon_spawn"
    "origin" "2393 6537 -610"
    "angles" "0 0 0"
    "weapon_selection" "weapon_hunting_rifle"
    "spawn_without_director" "1"
    "solid" "6"
    "disableshadows" "1"
    "spawnflags" "2"
    "count" "5"
}

Is the fix wrong?

**Comment by vikingo12** [comment]
; --- Replace the HR with an ammo pile
filter:
{
	"hammerid" "98901"
}
add:
{
	"classname" "weapon_ammo_spawn"
	"origin" "2259 6517 -672"
	"angles" "0 345 0"
	"model" "models/props/terror/ammo_stack.mdl"
	"solid" "6"
	"disableshadows" "1"
	"spawnflags" "2"
	"count" "5"
}

remove that

**Comment by QoQman** [comment]
I made that fix.
However, the HR did not appear on the map.

Are there any other files to change?

**Comment by vikingo12** [comment]
> I made that fix.
> However, the HR did not appear on the map.
> 
> Are there any other files to change?

global_filters 
remove those:
{
	match:
	{
		"classname" "weapon_spawn"
		"weapon_selection" "weapon_hunting_rifle"
	}
	replace:
	{
		"weapon_selection" "tier1_any"
	}
}

{
	match:
	{
		"classname" "weapon_hunting_rifle_spawn"
	}
	replace:
	{
		"classname" "weapon_spawn"
	}
	insert:
	{
		"weapon_selection" "tier1_any"
		"spawn_without_director" "1"
	}
}
