### ISSUE TITLE
boomer_horde_equalizer issues

### ISSUE THREAD

**Issue by ProjectSky** [SirPlease/L4D2-Competitive-Rework#340]
```WanderersCondition``` offset is correct, but random errors

```
[SM] Exception reported: Check bytes failed. Invalid byte (read: 90@0, expected byte: 39@0). Check offset 'WanderersCondition'.
L 08/05/2021 - 18:25:18: [SM] Blaming: optional/boomer_horde_equalizer.smx
L 08/05/2021 - 18:25:18: [SM] Call stack trace:
L 08/05/2021 - 18:25:18: [SM]   [0] SetFailState
L 08/05/2021 - 18:25:18: [SM]   [1] Line 144, D:\SourcePawn10\boomer_horde_equalizer.sp::CheckBytes
L 08/05/2021 - 18:25:18: [SM]   [2] Line 126, D:\SourcePawn10\boomer_horde_equalizer.sp::SelectBytes
L 08/05/2021 - 18:25:18: [SM]   [3] Line 96, D:\SourcePawn10\boomer_horde_equalizer.sp::CheckPatch
L 08/05/2021 - 18:25:18: [SM]   [4] Line 36, D:\SourcePawn10\boomer_horde_equalizer.sp::OnPluginStart
```

**Comment by A1mDev** [comment]
Well, i see that the patch has already occurred, and the plugin is trying to do it again, but this cannot be because there is a check for it. Check if you have another such plugin running?

**Comment by ProjectSky** [comment]
```boomer_horde_equalizer``` already 1

this error happen random only when the server starts, i already check plugins list, no same function plugins

**Comment by A1mDev** [comment]
So do you have a cvar 'boomer_horde_equalizer' in server.cfg??

**Comment by ProjectSky** [comment]
> So do you have a cvar 'boomer_horde_equalizer' in server.cfg??

No, I did not touch boomer_horde_equalizer, it keep default value

**Comment by A1mDev** [comment]
I see no problem in the plugin, it can't do a double patch in any way. The only problem can be if there is a second such plugin that makes the patch.

**Comment by A1mDev** [comment]
I start 2 plugins got the same errors. So check your server why you have 2 plugins starting.
L 08/05/2021 - 22:48:07: Info (map "c5m4_quarter") (file "errors_20210805.log")
L 08/05/2021 - 22:48:07: [SM] Exception reported: Check bytes failed. Invalid byte (read: 90@0, expected byte: 39@0). Check offset 'WanderersCondition'.
L 08/05/2021 - 22:48:07: [SM] Blaming: optional/boomer_horde_equalizer.smx
L 08/05/2021 - 22:48:07: [SM] Call stack trace:
L 08/05/2021 - 22:48:07: [SM]   [0] SetFailState
L 08/05/2021 - 22:48:07: [SM]   [1] Line 144, boomer_horde_equalizer.sp::CheckBytes
L 08/05/2021 - 22:48:07: [SM]   [2] Line 126, boomer_horde_equalizer.sp::SelectBytes
L 08/05/2021 - 22:48:07: [SM]   [3] Line 96, boomer_horde_equalizer.sp::CheckPatch
L 08/05/2021 - 22:48:07: [SM]   [4] Line 36, boomer_horde_equalizer.sp::OnPluginStart

**Comment by ProjectSky** [comment]
> I start 2 plugins got the same errors. So check your server why you have 2 plugins starting.

too weird, i will continue test.

**Comment by ProjectSky** [comment]
i give up dig the cause of this error, choose to modify some function (like the old version)

``` cpp
void ApplyPatch(bool enable)
{
	int patchBytes[4] = {0x90, 0x90, 0x90, 0x90};
	int originalBytes[4] = {0x39, 0xF3, 0x7D, 0x13};

	int iReadByte;

	for (int i = 0; i < sizeof(patchBytes); i++)
	{
		iReadByte = LoadFromAddress(patchAddress + view_as<Address>(i), NumberType_Int8);
		if (patchBytes[i] < 0) break;
		if (enable)
		{
			if (iReadByte == patchBytes[i])
			{
				PrintToServer("patch already apply!");
				return;
			}
			StoreToAddress(patchAddress + view_as<Address>(i), patchBytes[i], NumberType_Int8);
			PrintToServer("apply: %x to %x", iReadByte, patchBytes[i]);
		}
		else
		{
			if (iReadByte != patchBytes[i])
			{
				PrintToServer("patch not apply!");
				return;
			}
			StoreToAddress(patchAddress + view_as<Address>(i), originalBytes[i], NumberType_Int8);
			PrintToServer("restore: %x to %x", iReadByte, originalBytes[i]);
		}
	}
}
```

**Comment by A1mDev** [comment]
Once again I say the plug-in is fine, when it starts, there can be no byte 90 in memory, but you get byte 90, it means that the patch has already happened, but it could not happen because the plugin is just starting, this can be seen in the error logs
