### ISSUE TITLE
Dead center finale double tank

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#341]
I modified the mission file and added the vscript of this repository, also added  ther cvar to remove the second event tank. 
Basically the first tank fight added just after elevator was long, after a while a second tank came at the same time. 
Does it happen on your servers too ?

On another side before that a few months ago i tried modifiyng the script by myself and remove all tank and replace them by horde events and to just let the tank manually spawned after elevator, tanks from vscript were still coming depsite i did that. I wonder if they are hardcoded or something.

**Comment by Derpduck** [comment]
Yes this is normal, if you pick up or pour cans the finale will start and a tank will eventually spawn.
