### ISSUE TITLE
SI class announce never refresh

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#342]
If someone suicide to change infected (i know it is not a thing on zonemod) or leave and join back and have another SI, it never refresh on the panel. Is it not possible to check every few seconds ?

**Comment by A1mDev** [comment]
In this case, it makes no sense to use a plugin si_class_announce to add a string to the readyup. It is better to remove this code and add it to the readyup if someone needs it...

**Comment by SirPlease** [comment]
A non-issue for the github, outside of the github's purpose.

**Comment by lunatixxx** [comment]
I disabled ghost suicide but tt happens too when people are switching team because they were put in the wrong one for example. How do you keep the same spawns?

**Comment by lunatixxx** [comment]
And i have l4d2_fix_spawn_order.
