### ISSUE TITLE
Tickrate Enabler bugged?

### ISSUE THREAD

**Issue by Krevik** [SirPlease/L4D2-Competitive-Rework#344]
Okay so when I am on your server, or on my server using your version of tickrate enabler and i type "rate" in console I am getting such a response from console:
`
"rate" = "30000"
** NOTE: The real value is 128.000 but the server has temporarily restricted it to 30000.000 **
`

I think tickrate enabler is bugged.

**Comment by vikingo12** [comment]
are you in spec?

**Comment by Krevik** [comment]
> are you in spec?

no

**Comment by A1mDev** [comment]
This has always been the case, the client does not support a tickrate of 100, so you see such an inscription. Ignore it and it can hardly be fixed on the server side, only developers can, but will they? ;D

**Comment by Derpduck** [comment]
This is normal, it is not related to tickrate enabler at all and is always given if your rate is above 30000 on any server.

**Comment by Krevik** [comment]
Thanks guys I am closing it then.
