### ISSUE TITLE
Tank punch stuck fix false positive

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#345]
In c8m5 if you get punch outside of rooftop very far against the invisible wall you can get teleported back and i had the timer set on 3 seconds, i guess this can happen on other maps.

**Comment by A1mDev** [comment]
Well, I think you need to attach at least a screen or a demo to such reports, I don't quite understand what you are talking about.

**Comment by vikingo12** [comment]
Im getting the messages even when tank isn't up :rofl:

**Comment by lunatixxx** [comment]
I don't think this plugin is necessary anymore. Seems that since one update the survivor stuck by a punch now get teleported by the same function that when you stuck in decor.
