### ISSUE TITLE
readyup.smx autofunction struggles with l4d2_slowdown_control.smx

### ISSUE THREAD

**Issue by C0REX** [SirPlease/L4D2-Competitive-Rework#348]
https://www.youtube.com/watch?v=ljnsg_wbRW4

i tested on two different root servers. fresh install (Update plugins. (343)). both run with ubuntu v18.04.
happend when changing the readyup forceing to autostart and when you let the timer run out
doesnt happend when changing the readyup forceing to autostart and u forcestart the match.
doesnt happend when u delete or unload l4d2_slowdown_control.smx no matter whether with autostart or without

**Comment by vikingo12** [comment]
Install an older version of l4d2_slowdown_control for easy fix

**Comment by C0REX** [comment]
looks like a l4d2_slowdown_control.smx from a repo from 12/10/2020 works ..ty vikingo12 :)

**Comment by A1mDev** [comment]
Test now please:)

**Comment by C0REX** [comment]
I tested the update (355) on both servers, the tank runs so far without problems. Thank you A1mDev. At this point a thank you to all of you guys, without your work the game wouldn't be what it is. thumbs up :)
