### ISSUE TITLE
Tank dmg announce

### ISSUE THREAD

**Issue by rom4ntic** [SirPlease/L4D2-Competitive-Rework#370]
Hello, I know it's all those plugins are rather meant for versus, but I decided to use one of them - tank damage announce.smx on my campaign server and damage report goes up to 200% instead of 100%. Thought it was bug at first, but it happens all the time. Anyone could maybe help me with that?

**Comment by vikingo12** [comment]
cause it has a hp multiplier 1.5

**Comment by SirPlease** [comment]
> cause it has a hp multiplier 1.5

This is not the issue, as the code specifically looks for the value of the ConVar first, and then checks if it's versus or realism versus.

`if (StrEqual(sGameMode, "versus") || StrEqual(sGameMode, "mutation12")) g_fMaxTankHealth = GetConVarFloat(g_hCvarTankHealth) * 1.5;`

From a quick glance I don't see an issue with the code, but I went ahead and checked it out on my server.
I've also done a quick test on the server and it works as expected:

```
[!] Damage dealt to Tank (AI)
[1613] (40%) Sir
[1029] (26%) Coach
[800] (20%) Ellis
[558] (14%) Nick
```

**Comment by vikingo12** [comment]
@SirPlease put advanced/expert difficulty

**Comment by SirPlease** [comment]
> @SirPlease put advanced/expert difficulty

Your reply assumed versus, but yes, this is the problem.
I assumed the ConVar would change on difficulty change, but it does not. 👍

**Comment by vikingo12** [comment]
@A1mDev

**Comment by SirPlease** [comment]
I've gone ahead and wrote an update to the plugin.
If you have any other issues with this plugin, don't be afraid to report them.

**Comment by rom4ntic** [comment]
Thank you guys for such a quick response. I've checked on the server, everything seems to be in order now. Thanks for updating this plugin @SirPlease.

**Comment by vikingo12** [comment]
HEEEEEEEY if theres an update for campaigns I can write a bunch of stuff to fix for campaign @SirPlease
