### ISSUE TITLE
Shotgun pellets being incorrect in the secondary ring.

### ISSUE THREAD

**Issue by SirPlease** [SirPlease/L4D2-Competitive-Rework#373]
Left: Chrome.
Right: Pump.
![image](https://user-images.githubusercontent.com/2643403/132951463-54a74d8a-5890-4c64-98fa-63c46e094b20.png)

In this image, you can see 8 pellets for the Chrome and 9 for the Pump.
The problem is that the Pump Shotgun has **10** Pellets, so it's either firing two pellets in the same place or refuses to create the proper amount of extra pellets.

I've gone ahead and tested this with increased values, it always seems to miss just one pellet.

**Comment by vikingo12** [comment]
10>11

**Comment by robex** [comment]
#### Short answer:

In [l4d2_static_shotgun_spread.sp](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/8b2c5f193c4e808fb467211319818e05f04c40dd/addons/sourcemod/scripting/l4d2_static_shotgun_spread.sp#L104), change lines 104-106 from
```
StoreToAddress(pAddr + view_as<Address>(g_BulletOffsets[platform][0]), nBullets + 1, NumberType_Int8);
StoreToAddress(pAddr + view_as<Address>(g_BulletOffsets[platform][1]), nBullets + 1, NumberType_Int8);
StoreToAddress(pAddr + view_as<Address>(g_BulletOffsets[platform][2]), nBullets + 2, NumberType_Int8);
```
to
```
StoreToAddress(pAddr + view_as<Address>(g_BulletOffsets[platform][0]), nBullets, NumberType_Int8);
StoreToAddress(pAddr + view_as<Address>(g_BulletOffsets[platform][1]), nBullets, NumberType_Int8);
StoreToAddress(pAddr + view_as<Address>(g_BulletOffsets[platform][2]), nBullets + 1, NumberType_Int8);
```

![20210915132802_1](https://user-images.githubusercontent.com/23484075/133426155-b6630ac4-1ee2-49de-a708-2b497051d3e2.jpg)


#### Explanation:
I think the plugin hardcodes the center pellet as being always on in this calculation, so it assumes there is always 1 less bullet by increasing `nBullets` by 1 (which is the variable in the asm patch that decides whether a bullet goes to the 1st, 2nd, or no ring). Now if the center pellet is enabled 1 bullet is taken from the 1st ring, whereas before it was the "missing" bullet from the 2nd ring.
