### ISSUE TITLE
max_queries cmd can block connections to server

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#374]
Just to let you know that you should put an advertisement uncommented near these commands in the server.cfg. I had these for a long time without problem but suddenly nobody could connect to my server anymore maybe because my provider changed something on his side, still i wasted much time to find what was the cause and since i removed these cmd it works again. 

sm_cvar sv_max_queries_sec_global 10
sm_cvar sv_max_queries_window 10 

What are these cmd doing in the first place exactly ?

**Comment by vikingo12** [comment]
you sure?

**Comment by SirPlease** [comment]
I'm guessing you figured this out, but they're status queries.
They should never in any case prevent people from being able to connect your server, at worst they won't respond to a "View Game Info" or won't show up on someone's Steam Group Server.

**Comment by lunatixxx** [comment]
Yep apparently this is a targeted ddos attack, someone have time and energy to lose for doing that since one week.
