### ISSUE TITLE
In nextmod l4d2_car_alarm_hittable_fix.smx loading twice

### ISSUE THREAD

**Issue by Electr0** [SirPlease/L4D2-Competitive-Rework#38]
cfgogl\nextmod\shared_plugins.cfg:
sm plugins load optional/nextmod/l4d2_car_alarm_hittable_fix.smx

and in generalfixes.cfg
sm plugins load fixes/l4d2_car_alarm_hittable_fix.smx

**Comment by SirPlease** [comment]
Fixed in [Update v0.6](https://github.com/SirPlease/L4D2-Competitive-Rework/commit/f76b8463b64f5415de6e7fc2875a4e93158df632).
