### ISSUE TITLE
Tank props glow bug with "map" command

### ISSUE THREAD

**Issue by Derpduck** [SirPlease/L4D2-Competitive-Rework#383]
If `map` is used to reset the map while a tank is still alive, and has punched a hittable, that hittable will fail to spawn when the map is loaded.

Using the `map` command (console or sm command) seems to not correctly fire the events this plugin depends on to check when to remove hittables. The `changelevel` command and other restarting methods seem to work fine.

Before `map` command: https://i.imgur.com/P9ozq1U.jpeg
After `map` command: https://i.imgur.com/UXG7I6v.jpeg

It can be avoided by resetting the map with a vote or changelevel, which 99% of the time is what will happen.
This could potentially be an issue in other plugins too if the command is used to change levels on the server.

**Comment by fbef0102** [comment]
l4d2_tank_props_glow.sp add

```
public void OnMapEnd()
{
	g_hTankProps.Clear();
	g_hTankPropsHit.Clear();
}
```

**Comment by Derpduck** [comment]
Thanks, I've added it to #378
It could still be an issue with other plugins.

**Comment by SirPlease** [comment]
I'll close this for now
