### ISSUE TITLE
Readyup menu does not hide when vote is called

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#384]
It hides properly with custom voting (buildinvotes), but with the vanilla votes like return to lobby ect it does not hide and players have troubles seeing what type of vote it is or press F1 unintentionally for tick ready sometimes at the moment where the vote is called. Is it something that can be improved ?

**Comment by SirPlease** [comment]
Yes, this most certainly is something that can be added.

**Comment by lunatixxx** [comment]
Version of jensewe works it hides panel, but it creates this error in logs: 
[BVOTE] Game_IsVoteInProgress(). Couldn't find the vote_controller!

**Comment by lunatixxx** [comment]
No more errors tho with last version of readyup.
