### ISSUE TITLE
spec hud memory leak (or left4dhooks?)

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#385]
I am using this plugin since a while and no problem, but checked the error logs by curiosity and found this. (it last 2 seconds and happened once)

To be fair this is not exactly the same code for my tankhud but it should not be a problem, i am not sure that left4dhooks is not the cause ->  "Blaming: left4dhooks.smx"

`L 09/26/2021 - 18:55:19: [SM] Exception reported: Memory leak`
`L 09/26/2021 - 18:55:19: [SM] Exception reported: Error creating ThisHandle in preparation to call hook callback. (error 6)`
`L 09/26/2021 - 18:55:19: [SM] Blaming: left4dhooks.smx::SelectTankAttack`
`L 09/26/2021 - 18:55:19: [SM] MEMORY LEAK DETECTED IN PLUGIN (file "tankhud.smx")`
`L 09/26/2021 - 18:55:19: [SM] Unloading plugin to free 31396 handles.`
`L 09/26/2021 - 18:55:19: [SM] Contact the author(s) of this plugin to correct this error.`
`L 09/26/2021 - 18:55:19: --------------------------------------------------------------------------`
`L 09/26/2021 - 18:55:19: Type	IMenuPanel          |	Count	31390`
`L 09/26/2021 - 18:55:19: Type	GameConfigs         |	Count	1`
`L 09/26/2021 - 18:55:19: Type	Timer               |	Count	1`
`L 09/26/2021 - 18:55:19: Type	Trie                |	Count	3`
`L 09/26/2021 - 18:55:19: Type	ValveCall           |	Count	1`
`L 09/26/2021 - 18:55:19: --------------------------------------------------------------------------`
`L 09/26/2021 - 18:55:19: Oldest Living Handle: Timer created at 09/24/2021 - 01:02:52`
`L 09/26/2021 - 18:55:19: Newest Living Handle: IMenuPanel created at 09/26/2021 - 18:55:17`
`L 09/26/2021 - 18:55:19: -- Approximately 882076 bytes of memory are in use by (31396) Handles.`

`L 09/26/2021 - 18:55:19: [SM] Exception reported: Memory leak`
`L 09/26/2021 - 18:55:19: [SM] Exception reported: Error creating ThisHandle in preparation to call hook callback. (error 6)`
`L 09/26/2021 - 18:55:19: [SM] Blaming: left4dhooks.smx::SelectTankAttackPre`
`L 09/26/2021 - 18:55:19: [SM] MEMORY LEAK DETECTED IN PLUGIN (file "tankhud.smx")`
`L 09/26/2021 - 18:55:19: [SM] Unloading plugin to free 31396 handles.`
`L 09/26/2021 - 18:55:19: [SM] Contact the author(s) of this plugin to correct this error.`
`L 09/26/2021 - 18:55:19: --------------------------------------------------------------------------`
`L 09/26/2021 - 18:55:19: Type	IMenuPanel          |	Count	31390`
`L 09/26/2021 - 18:55:19: Type	GameConfigs         |	Count	1`
`L 09/26/2021 - 18:55:19: Type	Timer               |	Count	1`
`L 09/26/2021 - 18:55:19: Type	Trie                |	Count	3`
`L 09/26/2021 - 18:55:19: Type	ValveCall           |	Count	1`
`L 09/26/2021 - 18:55:19: --------------------------------------------------------------------------`
`L 09/26/2021 - 18:55:19: Oldest Living Handle: Timer created at 09/24/2021 - 01:02:52`
`L 09/26/2021 - 18:55:19: Newest Living Handle: IMenuPanel created at 09/26/2021 - 18:55:17`
`L 09/26/2021 - 18:55:19: -- Approximately 882076 bytes of memory are in use by (31396) Handles.`

**Comment by lunatixxx** [comment]
I guess it is related to the extra information about attacks i have on it (rocks, punch, objects), it looks like it can't reach the information in left4dhooks or something.

**Comment by MartLegion** [comment]
This error is more related to the plugin not closing some handles (usually with the delete keyword)
example here:
https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/spechud.sp#L608-L629

I usually check if there is some memory leak in plugins by using:

sm_dump_handles <filename>

I take 2 snapshots, like one 1hour after server start
and another one after some hours or 1 day

Then I upload both files here to compare:
https://hexer10.github.io/Sourcemod-HandleDumpParser/

From your example the memory leak reached was thrown after 2 days.
