### ISSUE TITLE
Spawn order bug

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#398]
We just had two jockeys at same time on CEDA after that someone crashed as tank.
Had double smokers on my serv too while a tank fight.

**Comment by lunatixxx** [comment]
I gave another try and it mess infecteds even before a tank, have two chargers or jockey at same time. I got everything it need to make it work normally.

**Comment by SirPlease** [comment]
Do you mean after @jensewe 's improvements or without it?

**Comment by lunatixxx** [comment]
Even before the actual version i had problems like that, not sure what causes it. But i never could get a quad cap.

**Comment by Krevik** [comment]
> Even before the actual version i had problems like that, not sure what causes it. But i never could get a quad cap.

Quad cap may be related to your l4d2_dominators settings.
Quick comment: In the previous version on my custom config using l4d2_fix_spawn_order I had problems with double infected spawns. An update to a new l4d2_fix_spawn_order version fixed it - till this day I do not know what other plugin was causing the problem on my server. New version works perfectly BUT it had problems working correctly with some plugin. After some "debugging" I found out that it probably messes with https://forums.alliedmods.net/showthread.php?p=2712082 (tank pass plugin) which I don't use anymore. However I thought, maybe you're using that plugin too so here may be 2nd source of your problems. Of course I miss tank pass, therefore I would like to post my question here - do you maybe know how can I easily fix spawn order or tank pass plugin to be compatible with each other?

**Comment by jensewe** [comment]
> New version works perfectly BUT it had problems working correctly with some plugin. After some "debugging" I found out that it probably messes with https://forums.alliedmods.net/showthread.php?p=2712082 (tank pass plugin) which I don't use anymore. However I thought, maybe you're using that plugin too so here may be 2nd source of your problems. Of course I miss tank pass, therefore I would like to post my question here - do you maybe know how can I easily fix spawn order or tank pass plugin to be compatible with each other?

Thinking that the version in my PR should handle this flawlessly, judging by code.
Well it's still confusiing that what version you're actually using. Tank Pass isn't gonna be a topic for current competitive scene. Therefore I won't cover this one until later or actual move from configs. Though it would be appreciated if info is provided with cvar "sackorder_debug" on while reproducing the bug.

**Comment by lunatixxx** [comment]
"l4d2_dominators", "53"
And no i am not using tank pass.

**Comment by lunatixxx** [comment]
Even worst somehow, even disabled it breaks the spawns.

**Comment by lunatixxx** [comment]
If bots fill the empty SI slot, could that break the spawns?

**Comment by jensewe** [comment]
> If bots fill the empty SI slot, could that break the spawns?

The class of the spawned bot is not controlled, but pushed into the spawn queue when it dies. So it's a yes.

**Comment by jensewe** [comment]
> Ok but you do not have the choice to have a bot dying when you leave tank to AI in all cases so.

It's an exactly excluded case, and it's known that many matches had tank AIed without spawn issues.
I meant natural bots of regular SI (non-boss) dying would mess up spawn queues, like `director_allow_infected_bots = "1"`.

**Comment by lunatixxx** [comment]
Ignoring bots into the process should be possible.

**Comment by Krevik** [comment]
If that anyhow helps, I have been testing pullrequest proposed by @jensewe for few weeks on my server now, and it seems to work perfectly even with presence of tank pass plugin.
