### ISSUE TITLE
Minor changes to the MVP system

### ISSUE THREAD

**Issue by HunLepto** [SirPlease/L4D2-Competitive-Rework#405]
Make the MVP system not count FF when the player is incapped (because sometimes friends shoot each other while incapped out of fun or strangers out of frustration) and not count CI killed before the game starts (I only noticed this a few days ago). These are just some minor suggestions and you can easily put it into low priority, but I feel this could be a nice addition to the MVP system to show one's skill level a bit more accurately.

**Comment by vikingo12** [comment]
https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/survivor_mvp.sp#L41
will this ever be completed?
