### ISSUE TITLE
[Q] - Skill/stats Plugin

### ISSUE THREAD

**Issue by Berndinox** [SirPlease/L4D2-Competitive-Rework#407]
Why are stats / skills splitt into two plugins:

- l4d2_skill_detect.sp
- l4d2_stats.sp

wont it make sense to put them all in one?

**Comment by SirPlease** [comment]
The problem is the size of the plugins, they were built separately and I don't think anyone "cares" enough to simplify/merge them.
It's not a big deal, but I definitely agree it's a mess and could've been done better.

**Comment by Berndinox** [comment]
Thanks for the FB. I just tought there may is a specific reason.
