### ISSUE TITLE
C9M2 pills replaced by other

### ISSUE THREAD

**Issue by Target5150** [SirPlease/L4D2-Competitive-Rework#41]
In zm1v1
Replaced by bile before
I try restart, the pill replaced by adrenaline

here is ent dump:(1v1)
] ent_fire !picker addoutput "targetname 1"
] ent_dump 1
count: 1
classname: weapon_adrenaline_spawn
effects: 16
friction: 1.00
glowbackfacemult: 1.00
spawnflags: 32768

And then I try 4v4,many situations:
such as only 3 pills on floor,no anything on 2nd floor
or 2 pills on floor ,1 pill on 2nd floor(screenshot in zip)
and ent_dump this situation 
] ent_fire !picker addoutput "targetname 2"
] ent_dump 2
  count: 1
  classname: weapon_pain_pills_spawn
  effects: 16
  friction: 1.00
  glowbackfacemult: 1.00
  spawnflags: 32768

I guass that was item_spawn not only throwble spawn,so global_fliter was not enough

And provided 2 stripper dumps , 0000 was dumped in 1v1 ,0001 was dumped in 4v4
[c9m2.zip](https://github.com/SirPlease/L4D2-Competitive-Rework/files/3607176/c9m2.zip)

**Comment by SirPlease** [comment]
Fixed in [Update v0.6.6](https://github.com/SirPlease/L4D2-Competitive-Rework/commit/ce6b7cde48ec46cb68a713a92e45cb5d26d66224)

**Comment by SirPlease** [comment]
Fixed in [Update v0.6.6](https://github.com/SirPlease/L4D2-Competitive-Rework/commit/ce6b7cde48ec46cb68a713a92e45cb5d26d66224)
