### ISSUE TITLE
[Request] Fov monitor

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#416]
A small plugin to check fov client settings (fov_desired), the same that for lerps.

**Comment by SirPlease** [comment]
Why would this be a good thing to add to the Competitive Framework?

**Comment by lunatixxx** [comment]
Why not ? It is informative as lerp plugin is. And may be interesting to see if some are using weird values, as it is a client cvar and can be more easily manipulated.

**Comment by SirPlease** [comment]
Lerp is informative for a good reason as lerp actually impacts the game in a way that actually is noticable, whereas `fov_desired` arguably does not.

**Comment by lunatixxx** [comment]
> Lerp is informative for a good reason as lerp actually impacts the game in a way that actually is noticable, whereas `fov_desired` arguably does not.

I will have to disagree. I did two screenshots on the same spot, one with 120 fov and one with thirdpersonshoulder on. Guess what ? Fov 120 give more information than tps view...

**Comment by lunatixxx** [comment]
Fov 90 / 120: https://media.discordapp.net/attachments/907152883743600693/909708322972778545/fov_comparison.jpg?width=1440&height=404

TPS: https://media.discordapp.net/attachments/907152883743600693/909712489627910164/tps_view.jpg?width=1043&height=586
