### ISSUE TITLE
l4d2_godframes_control_merge adds 100 ms before processing ff

### ISSUE THREAD

**Issue by LuckyServ** [SirPlease/L4D2-Competitive-Rework#42]
For [this line](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/826269166b1e925d6de7e0225413472e9940cca2/addons/sourcemod/scripting/l4d2_godframes_control_merge.sp#L446), I understand the minimum time for a timer is 100ms and I'm guessing this was done to add up all the pellets before processing since I assume OnTakeDamage is fired for every pellet. 

However there might be a better way using the [RequestFrame](https://sm.alliedmods.net/new-api/functions/RequestFrame) function. This would not add 100 ms of latency to t1 shotguns ff.

**Comment by SirPlease** [comment]
Solid suggestion, added it in with Spoon's Godframe Native and a clientbased boolean rather than a global handle keeping FF in check.

Fixed in [Update v0.6.4](https://github.com/SirPlease/L4D2-Competitive-Rework/commit/6671eeb9d3258e99e0001b0d4a161f231aff53ee)
