### ISSUE TITLE
Tank hittables behavior and spawn order

### ISSUE THREAD

**Issue by Krevik** [SirPlease/L4D2-Competitive-Rework#421]
So with these files I am having two main problems - tank hittables behavior and problem with spawn order.
1. Tank hittables are just flying like crazy so you basically cannot control them in the way it is possible on SirPlease official servers.
2. Spawn order is working differently (spawns of infected are not fully predictable as it is on SirPlease servers)
At first I thought the bug is caused by the thing I am using another OS on the server, however after switching to OVH Ubuntu 18.04 the problem remains (also the problem with tank hittables). Don't know if the problem is persistent for other people owning their servers? 
Anyway as SirPlease servers don't have such problems it is probably something on my side therefore it is more a QUESTION than ISSUE.

How can I control tank hittables behavior? (I know the most probable problem cause is increased tickrate, but as SirPlease servers are not having such problem then how could I fix that?)
And the other question, what can have an influence on spawn order? Additional info: Older version of spawn order (don't know if it was a problem caused by spawn order or maybe by left4dhooks) worked totally incorrectly on debian 10 - they were sometimes just broken, giving constantly boomers to people and throwing errors with L4D_OnEnterGhostState I think).

Another problem (3.) probably connected with OS, etc is l4d2_skill_detect behavior - it not always detects all the things. I noticed that it is especially bugged with hunter high pounce detection. And again the problem does not occur on SirPlease servers. For that reason I am using old l4d2_skill_detect version which suprisingly works better than the actual official version contained within this repo. However switching to recommended ubuntu 18.04 doesn't solve the problem. I did some testing and the actual reason of that is probably detection of height of jump.

**Comment by A1mDev** [comment]
@Krevik, The physical props that the tank can interact with also depend on gravity 'sv_gravity', a low value can do what you described =)

**Comment by Krevik** [comment]
Well, but sv_gravity will affect everything, also survivors and that is something that I do not want, cause let's say gravity of other things is mostly ok. The problem is only with gravity of hittables upon hit by tank so...

**Comment by A1mDev** [comment]
@Krevik of course, each item has its own mass, but the mass cannot be below 400 and above 1500. You can change the cvar to adjust the impact force 'tank_swing_physics_prop_force'.

**Comment by Krevik** [comment]
Thank you a lot that's what I was looking for, I owe you at least a good beer!
