### ISSUE TITLE
Linux-players compatibility

### ISSUE THREAD

**Issue by Krevik** [SirPlease/L4D2-Competitive-Rework#422]
Another more question or suggestion than issue. Linux-Players cannot join the server because of custom data like models/sounds to be downloaded from server. For example hats plugin or fortnite dances plugin (which I believe are present on SirPlease servers or at least were present, but are not present in this github repo) contained such custom data (models,sounds,etc) were causing crashes during joining try of players that were playing the game using linux. Probably it is l4d2 problem, but maybe somebody from here could suggest some resolution for that problem? Also if Sir decide that the issue is not really related to the server files, sorry for making a mess.

**Comment by SirPlease** [comment]
It's just the fortnite dances that are present on the Servers that require the player to manually download the Linux/Mac files manually before joining the server.
The server can't force the player to download files with extensions that the game doesn't use for security reasons.

**Comment by Krevik** [comment]
Oh, could you tell me where should player exactly put those files? I've been trying that but I didn't succeed probably because of the location.

**Comment by SirPlease** [comment]
In the base left 4 dead 2 directory. (`left4dead2/left4dead2`)
Considering I just saw your post on the base plugin on Alliedmodders, I'm assuming you're trying to do this for your own servers.
It all depends on where the plugin is reading from, in my case it reads from `models/player/custom_player/foxhound/`

so, `Left 4 Dead 2/left4dead2/models/player/custom_player/foxhound/` is the folder on the player.

**Comment by Krevik** [comment]
Hmmm I was trying that, however it didn't work in my case. Well good to know that this way is working and I probably just failed somewhere. Thanks Sir!
