### ISSUE TITLE
Can't generate any logs files in soucemod

### ISSUE THREAD

**Issue by honghl5** [SirPlease/L4D2-Competitive-Rework#425]
With your guide in README.txt, I ran a server. But I notice there is no logs files in addons/sourcemod/logs. And there are some plugins can't save the cookies data, like HAT plugin which didn't save the hat data when I rejoin the server, even though I set the param to "1". I try to find a solution, but couldn't find one so far. Is there a solution can solve this? instead of reset the whole server. : (

**Comment by SirPlease** [comment]
Hiya,

Have you made sure the folder exists and the user you installed the server on has write permission to the logs folder?

**Comment by honghl5** [comment]
oh,yeah! The problem solved after I give the user write permission! Tyvm! : D
