### ISSUE TITLE
damage of uzi may be too low

### ISSUE THREAD

**Issue by honghl5** [SirPlease/L4D2-Competitive-Rework#432]
hi sir,
I always check your UPDATELOGS. I remember the damage of  uzi adjusted to 20 from 22 in Zonemod2.0.  Testing myself today, I find it is 19 per shot. And the smg's is 24. It is the original set ? or maybe I missed something?

**Comment by SirPlease** [comment]
Hello friend, how exactly are you testing this?
The damage values of the uzis aren't set in the config any longer, so the config isn't modifying their damage values (meaning the Silenced has 25 and the Regular has 20).

Keep in mind that there's damage drop off based on how far the shooter is from the target, just in case you're using a plugin to calculate damage.

**Comment by honghl5** [comment]
I know the damage-dropingoff thing. And I tested it as following. 
I shoot the tank with one bullet in a distance of 0, face to face. Then, I swap to SI to check the tankhud. I do it again with 50 bullets. Calculating the damage. 19 damage per shot and 950 damge in 50 shots with uzi. 24 damage and 1200 damage with smg. 
It's only a tiny difference. But it makes me confused. So I just need to check. : D

**Comment by honghl5** [comment]
I think I know the reason why it is 19 but not 20. In a distance of 0, the damage of one bullet dont drop off. But that is an ideal distance which cannot meet in game. Because the minimize distance between SI and SV is 1. And in the distance of 1, there will be damage droppingg off. The minimize dropping-damage is 1. So, even though the distance between SI and SV is super close, there will be 1 dropping-damage per bullet. Is that right?

**Comment by SirPlease** [comment]
It's normal comrade, nothing to worry about.
