### ISSUE TITLE
ai Tank stuck in Dead Before Dawn

### ISSUE THREAD

**Issue by honghl5** [SirPlease/L4D2-Competitive-Rework#434]
when ai tank need to pass the crashed helicopter through the house or backyard, it just stucks by the helicoper and hits until it's dead. The ai tank wont find another way to get though the helicopter, except the way it used to be.

**Comment by SirPlease** [comment]
Nav issue, @Derpduck?

**Comment by Derpduck** [comment]
I looked into this when it was posted but couldn't find a solution I was happy with, I can take another look.

**Comment by SirPlease** [comment]
Won't fix.
