### ISSUE TITLE
did spreadpershot and maxmovespread really working?

### ISSUE THREAD

**Issue by JQ-WTF** [SirPlease/L4D2-Competitive-Rework#437]
i set the to 0 and 10, but sees not working.  
but **set upgrade_laser_sight_spread_factor 0** is working. 
laser change spread.

**Comment by SirPlease** [comment]
Hiya, how exactly are you testing this?
The client predicts bullet impacts locally, if you're basing this on where bullets land visually (without visualise_impacts plugin) it will always show the default.

**Comment by JQ-WTF** [comment]
> 

but why laser change it? it likes update something?

**Comment by JQ-WTF** [comment]
Does it make it less enjoyable to watch if the bullet is not in the right place? And it can be confusing player

**Comment by SirPlease** [comment]
Generally players don't look at the wall/objects while shooting, so I wouldn't worry about it.
If you want to confirm bullet spread is actually changing with your modifications, there's a [plugin](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/plugins/optional/visualise_impacts.smx) in the optional folder that you can load to see bullet impacts.

**Comment by JQ-WTF** [comment]
Thank you very much for your patience in answering my questions :D
