### ISSUE TITLE
Duplicate l4d2_playstats plugin load and unintended loading in 1v1 configs?

### ISSUE THREAD

**Issue by devilesk** [SirPlease/L4D2-Competitive-Rework#44]
`sm plugins load optional/zonemod/l4d2_playstats.smx` appears in `zonemod/shared_plugins.cfg` as well as `confogl_plugins.cfg` for the `zonemod`, `zm3v3`,  and `zm2v2` configs. It's not in `zm1v1/confogl_plugins.cfg` but it will still get loaded due to it being in `zonemod/shared_plugins.cfg`. The nextmod configs have the same inconsistency.

If `l4d2_playstats.smx` is only supposed to be in the 4v4, 3v3, and 2v2 modes then it shouldn't be in `shared_plugins.cfg`. If it's supposed to be in all modes, including 1v1, then it should be removed from the `confogl_plugins.cfg` files. The eq configs do the former, `l4d2_playstats.smx` is not in its `shared_plugins.cfg` but it is in the 4v4, 3v3, and 2v2 eq `confogl_plugins.cfg` files and missing from the 1v1 file.

**Comment by SirPlease** [comment]
Fixed in [Update v0.6.3](https://github.com/SirPlease/L4D2-Competitive-Rework/commit/f699df246c7db88a7f4f39cb4cfb27becea271af) 👍
