### ISSUE TITLE
in sv_consistency_fix using color tags on PrintToChatAll instead CPrintToChatAll

### ISSUE THREAD

**Issue by Electr0** [SirPlease/L4D2-Competitive-Rework#46]
PrintToChatAll("{blue}[{default}SoundM{blue}]{default}: Modified Sound Files detected on {olive}%N", client);

should be

CPrintToChatAll("{blue}[{default}SoundM{blue}]{default}: Modified Sound Files detected on {olive}%N", client);

**Comment by SirPlease** [comment]
Fixed in [Update v0.6.4](https://github.com/SirPlease/L4D2-Competitive-Rework/commit/6671eeb9d3258e99e0001b0d4a161f231aff53ee)
