### ISSUE TITLE
l4d2_melee_spawn_control.smx spawn error

### ISSUE THREAD

**Issue by JexQ-Schwartz** [SirPlease/L4D2-Competitive-Rework#467]
cheack the cvar, it's working. but only spawn fireaxe.

**Comment by Target5150** [comment]
> l4d2_melee_spawn "fireaxe,frying_pan,machete,baseball_bat,crowbar,cricket_bat,tonfa,katana,electric_guitar,knife,golfclub,pitchfork,shovel"
![9{~AL3CK3QTS65S0B%H3NVY](https://user-images.githubusercontent.com/42076548/164990639-81a5f59f-aea9-490a-8c9d-28452547a134.png)

tested and work fine.
check your format or weapon name or the "," wrong or not.

**Comment by JQ-WTF** [comment]
ok,my bad. but it still can‘t spawn riotshield

**Comment by SirPlease** [comment]
I've never messed with the Riot Shield, but AFAIK it's not an official melee weapon.
Looking at the melee_manifest, it's not in there.

**Comment by JexQ-Schwartz** [comment]
> I've never messed with the Riot Shield, but AFAIK it's not an official melee weapon. Looking at the melee_manifest, it's not in there.

OK, thankyou :D
