### ISSUE TITLE
l4d2_getup_slide_fix version 1.3 with charger impact

### ISSUE THREAD

**Issue by devilesk** [SirPlease/L4D2-Competitive-Rework#47]
I noticed that the l4d2_getup_slide_fix plugin here is based on version 1.1 while l4d2_getup_slide_fix in your ZoneMod repo is using a 1.3 version of this plugin which includes additional code for handling charger impacts.

Just wondering if using this version without the charger impact code is intended or not. Is this responsible for the change in the ZoneMod 1.9.4 changelog that says "Chargers no longer get stuck on Survivors mid-charge, this simply fixes Survivors becoming a “brick wall”."?

**Comment by SirPlease** [comment]
It's intentional, yes.
Simply because Charger Impacts (when a charger hits the wall and stumbles a Survivor) shouldn't prevent other staggers. I'm not sure why I added this to the plugin in the past.

It has nothing to do with Survivors becoming a "brick wall".
