### ISSUE TITLE
my server doesn't show up in steamgroup servers list

### ISSUE THREAD

**Issue by swhoro** [SirPlease/L4D2-Competitive-Rework#471]
here is my server.cfg:
```
hostname "[A]aiden's l4d2 server"
sv_voiceenable 0

sv_steamgroup *****
sv_steamgroup_exclusive 2
sv_allow_lobby_connect_only 0

sv_consistency 0
sv_pure 0
sv_pure_kick_clients 0

motdfile "mymotd.txt"
hostfile "myhost.txt"

sm_cvar sv_region 4
sm_cvar director_afk_timeout 20
sm_cvar sb_melee_approach_victim 1
sm_cvar sb_max_team_melee_weapons 4
sm_cvar mp_gamemode "coop"
sm_cvar z_difficulty "Normal"
sm_cvar rescue_min_dead_time 60

sm_cvar mv_maxplayers 8
sm_cvar sv_force_unreserved 1

sm_cvar fps_max 0
sm_cvar sv_minrate 100000
sm_cvar sv_maxrate 100000
sm_cvar sv_minupdaterate 100
sm_cvar sv_maxupdaterate 100
sm_cvar sv_mincmdrate 100
sm_cvar sv_maxcmdrate 100 
sm_cvar sv_client_min_interp_ratio  -1
sm_cvar sv_client_max_interp_ratio 0
sm_cvar nb_update_frequency 0.01
sm_cvar tick_door_speed 1.3
sm_cvar net_splitpacket_maxrate 50000

sm_cvar sv_forcepreload 1
sm_cvar sv_client_predict 1
```

could you please help me?

some other information:
1.I only open 9696 tcp/udp port for game, close other ports;
2.I am in china now, so the server can not connect to steamcommunity.com
Will these affect steamgroup list function?

**Comment by SirPlease** [comment]
Firstly, don't share your Steam Group ID with others, as others can abuse it to add their servers to it. (Remove it from your post)
Secondly, your server needs to be able to communicate with the Valve masterserver in order to be listed.

I assume that you've correctly told your server to communicate through those ports?

**Comment by swhoro** [comment]
> 
Sorry I don't understand  your last sentence.

I can connect with my server with "connect IP:PORT"
What is Valve masterserver's domain? In China, steamcommunity.com is banned but store.steampowered.com is not.

**Comment by SirPlease** [comment]
Is your server hosted by a server provider or on your home network?
If hosted on your own network, ask if someone else is able to connect to your server without issue as well.

If the firewall is blocking some or all connectivity between the server and Valve's masterservers, they won't show up. (Usually happens if certain IP ranges are blocked or there's L7 filtering going on)
I don't think you can retrieve a static masterlist for your servers, only for clients.

**Comment by swhoro** [comment]
> Is your server hosted by a server provider or on your home network? If hosted on your own network, ask if someone else is able to connect to your server without issue as well.
> 
> If the firewall is blocking some or all connectivity between the server and Valve's masterservers, they won't show up. (Usually happens if certain IP ranges are blocked or there's L7 filtering going on) I don't think you can retrieve a static masterlist for your servers, only for clients.

My server is hosted on tencent cloud.
If my server connot connect to Valve's masterservers, is there a log, and where is the log file?

**Comment by swhoro** [comment]
emmm I solve this problem, but have new problems.
here is my new server.cfg:
```
hostname "xxxxxx"
sv_voiceenable 0
sv_tags "hidden"

rcon_password "xxxxxx"
sv_allow_lobby_connect_only "0"
sv_steamgroup "xxxxxx"
sv_steamgroup_exclusive "2"
sv_search_key "xxxxxx"

sv_consistency 0
sv_pure 0
sv_pure_kick_clients 0

motdfile "mymotd.txt"
hostfile "myhost.txt"

sm_cvar sv_region 4
sm_cvar director_afk_timeout 20
sm_cvar sb_melee_approach_victim 1
sm_cvar sb_max_team_melee_weapons 4
sm_cvar mp_gamemode "coop"
sm_cvar z_difficulty "Normal"
sm_cvar rescue_min_dead_time 60

sm_cvar mv_maxplayers 8
sm_cvar sv_force_unreserved 1

sm_cvar fps_max 0
sm_cvar sv_minrate 100000
sm_cvar sv_maxrate 100000
sm_cvar sv_minupdaterate 100
sm_cvar sv_maxupdaterate 100
sm_cvar sv_mincmdrate 100
sm_cvar sv_maxcmdrate 100 
sm_cvar sv_client_min_interp_ratio  -1
sm_cvar sv_client_max_interp_ratio 0
sm_cvar nb_update_frequency 0.01
sm_cvar tick_door_speed 1.3
sm_cvar net_splitpacket_maxrate 50000

sm_cvar sv_forcepreload 1
sm_cvar sv_client_predict 1
```
I create a steam group and let my friend in. Later I kick him from the group.
I think I has set sv_steamgroup_exclusive "2" so that my friend cannot join in, but he can, no matter with "openserverbrowser" or steam friend panel.
here is my start parameters: 
`-game left4dead2 -ip $IP -port $PORT  +sv_clockcorrection_msecs 25 -timeout 10 -tickrate 100 +map c1m1_hotel -maxplayers 8 -insecure +servercfgfile server.cfg`

**Comment by SirPlease** [comment]
I thought I replied to this, either way, sv_steamgroup_exclusive doesn't work the way it says it does.
If you have the IP of the server or a friend in the server, you can always join it.
It just doesn't get added to the public master server.

**Comment by swhoro** [comment]
Ok, thanks for your help
