### ISSUE TITLE
Caster system and source tv

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#476]
Is it possible to exclude source tv bot from the kick vote? Last time i tried it was kicking it.

**Comment by A1mDev** [comment]
SourceTV bot fails this [condition](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/caster_system.sp#L501) in sourcemod...

**Comment by SirPlease** [comment]
It shouldn't be doing that, the official term would be [IsClientSourceTV](https://sm.alliedmods.net/new-api/clients/IsClientSourceTV), but like A1m said, FakeClient should cover it as it's the wider range.

**Comment by lunatixxx** [comment]
I am using that for protect sorucetv against kick by players, but it does not keep immunity with !kickspecs

```
#include <sourcemod>

#pragma semicolon 1
#pragma newdecls required

public void OnPluginStart()
{
    AddCommandListener(cmdCallVote, "callvote");
}

public Action cmdCallVote(int client, const char[] command, int argc)
{
    if (!(0 < client <= MaxClients && IsClientInGame(client)))
    {
        return Plugin_Continue;
    }

    char sType[32];
    GetCmdArg(1, sType, sizeof sType);
    if (StrEqual(sType, "kick", false))
    {
        char sTarget[32];
        GetCmdArg(2, sTarget, sizeof sTarget);
        int iTarget = GetClientOfUserId(StringToInt(sTarget));
        if (IsClientSourceTV(iTarget) || IsClientReplay(iTarget))
        {
            return Plugin_Handled;
        }
    }

    return Plugin_Continue;
} 
```

**Comment by A1mDev** [comment]
In game 'l4d' this function 'IsClientReplay' is meaningless because this code does not exist in the game. In any case, as stated above, this code cannot kick a SourceTV bot via kickspec.

**Comment by lunatixxx** [comment]
Yep apparently in the most recent version it does not kick soruce tv
