### ISSUE TITLE
Tongue bend fix error

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#481]
Not sure if it is important or not, got multiple time the same error.

```
L 06/04/2022 - 01:20:28: [SM] Exception reported: SendProp m_bendPositions is not an array. Element 9 is invalid.
L 06/04/2022 - 01:20:28: [SM] Blaming: l4d_tongue_bend_fix.smx
L 06/04/2022 - 01:20:28: [SM] Call stack trace:
L 06/04/2022 - 01:20:28: [SM]   [0] GetEntPropVector
L 06/04/2022 - 01:20:28: [SM]   [1] Line 63, plugin.sp::DTR_OnUpdateBend_Post
```

**Comment by A1mDev** [comment]
Strange error. m_bendPositions contains 120 bytes. Since it's a vector, and a vector is an array of floats with 3 elements, we can represent it like this:
- float m_bendPositions[10][3];
120 byte = 10(elements) * 3(vector) * 4(type float)

```- m_bendPositions (Offset 1212) (Save)(120 Bytes)```
