### ISSUE TITLE
Prevent spec / dead SI entities from being transmited to survivors 

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#487]
Cheaters can get the information on who is watching them which help them to hide it even if they don't care most of the time, every little thing that annoy them is good to take. I would use your plugin that do not transmit ghost entities as a base, it's easy to change it for spectator but i do not know how to check when a SI is just dead. m_iPlayerState ?

**Comment by A1mDev** [comment]
I think they just get one of the netprops (for example m_hObserverTarget), that is available to the client, then in this case this plugin is unlikely to help you =)

**Comment by A1mDev** [comment]
If i'm not mistaken this is netprop m_hObserverTarget
