### ISSUE TITLE
l4d_tank_rush completion score bug

### ISSUE THREAD

**Issue by devilesk** [SirPlease/L4D2-Competitive-Rework#49]
l4d_tank_rush.smx has a bug where if survivors die to a 2nd round tank, then the max points for the next map will be set to the max points of the previous map. Maps that have a max_distance defined in mapinfo are not affected by this bug.

For example, if survivors die to a 2nd round tank on Dead Air map 4, then Dead Air map 5 finale will have its max points set to 500 (map 4's max points) instead of 800.

The bug is due to the plugin [reseting the second half flag OnMapStart](https://github.com/Attano/L4D2-Competitive-Framework/blob/cf297ec4b58d1209b7d73eac04d14d233780ce08/addons/sourcemod/scripting/l4d_tank_rush.sp#L37) which happens after the [round_start event handler](https://github.com/Attano/L4D2-Competitive-Framework/blob/cf297ec4b58d1209b7d73eac04d14d233780ce08/addons/sourcemod/scripting/l4d_tank_rush.sp#L76)

The plugin isn't enabled in any of the current configs, but it is still in the apex and zonemod plugin folders. I came up with a fix for this bug and put it in this gist https://gist.github.com/devilesk/3d85f1d65bd23d28cb8dd0fd50b75f8d It removes tracking the round half with a bSecondRound variable and just calls the InSecondHalfOfRound stock from l4d2util instead. The IsTank function is also removed because l4d2util provides one.

**Comment by SirPlease** [comment]
I appreciate you reporting this, as you've said this plugin is currently not used in any of the included configs but I'll add the plugin to the optional plugins folder as the plan is to eventually get rid of all the separated folders.
