### ISSUE TITLE
Survivor still picking up teammate after tank punch/rock

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#493]
This bug always bothered me. Is it possible to force a cancel of the action?

**Comment by SirPlease** [comment]
There's already a plugin for that in the repo, that functionality is disabled in competitive configs though.

https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/l4d2_pickup.sp
