### ISSUE TITLE
Can I change 3v3 tank health

### ISSUE THREAD

**Issue by setchin** [SirPlease/L4D2-Competitive-Rework#503]
Hey Sir! Thanks a lot for your work!
I recently tried zonemod 3v3 and found tank health a little bit too high.
According to confogl.cfg, tank health has been changed to 3000 with

> confogl_addcvar z_tank_health 3000

but in fact, it seems not to work and tank health is 5000.
I also tried to type in sm_cvar z_tank_health 3000 in console but it also doesn't help
I am wondering how I can modify tank health?

**Comment by SirPlease** [comment]
Versus has a multiplier of **1.5**
In order to change the health to **3000**, you'll have to change the convar to **2000**.

I'd advise that if you're making changes to a config on a publicly used server, not to keep the config the same name in order to avoid confusion.

**Comment by setchin** [comment]
> Versus has a multiplier of **1.5** In order to change the health to **3000**, you'll have to change the convar to **2000**.
> 
> I'd advise that if you're making changes to a config on a publicly used server, not to keep the config the same name in order to avoid confusion.

Great! It works, and thanks a lot for the advice :)
