### ISSUE TITLE
pmelite config - plugin not loading

### ISSUE THREAD

**Issue by justtheletterjwithadot** [SirPlease/L4D2-Competitive-Rework#51]
Hi Sir,

Loaded pmelite config and saw the following errors

> Unknown command "sm_weapon"
> Unknown command "sm_weapon"
> Unknown command "sm_weapon"
> Unknown command "sm_weapon"
> Unknown command "sm_weapon"
> Unknown command "sm_weapon"
> Unknown command "sm_weapon"
> Unknown command "sm_weapon"
> Unknown command "sm_weapon"
> Unknown command "sm_weapon"
> Unknown command "sm_weapon"
> Unknown command "sm_weapon"

In [confogl_plugins.cfg](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/cfg/cfgogl/pmelite/confogl_plugins.cfg) for pmelite config,

`sm plugins load optional/elite/l4d_weapon_attributes.smx`

should be 

`sm plugins load optional/elite/l4d2_weapon_attributes.smx`

Regards,
J.

**Comment by SirPlease** [comment]
Appreciate the report, resolved in [Update  v0.6.7](https://github.com/SirPlease/L4D2-Competitive-Rework/commit/b3dbf3e45f079c2c22f3a617b0a601576a491b13)
