### ISSUE TITLE
Ghost infected speed and tickrate

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#511]
SI can do fast spawns with sprint and jump that they could never do on 30 tickrate, play on it and you will see what i mean they seems way slower. Is it a problem? Maybe not it balances vs other things but it is debatable.

**Comment by SirPlease** [comment]
This was noticable the moment we changed the tickrate and people lovingly embraced it.
Either way, it'd have quick a nasty backlash if we were to suddenly mess with it to try and get it to vanilla status.

**Comment by lunatixxx** [comment]
Does there is any cvar that can control their speed?

**Comment by lunatixxx** [comment]
Tested z_ghost_speed 250, was unplayable.

z_ghost_speed 430, not much change with actual value but seems a little less broken. Probably majority will not be able to tell the difference.

**Comment by Derpduck** [comment]
The tickrate change just causes the ghosts accelerate to full speed faster, but they don't actually move faster than on 30 tick. `z_ghost_speed` is just the max speed, there isn't a cvar for ghost acceleration.
