### ISSUE TITLE
bequiet errors

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#515]
Error with new sourcetv function.

L 07/27/2022 - 21:55:07: [SM] Exception reported: Client index 0 is invalid
L 07/27/2022 - 21:55:07: [SM] Blaming: bequiet.smx
L 07/27/2022 - 21:55:07: [SM] Call stack trace:
L 07/27/2022 - 21:55:07: [SM]   [0] GetClientTeam
L 07/27/2022 - 21:55:07: [SM]   [1] Line 83, plugin.sp::Say_Callback

**Comment by SirPlease** [comment]
Considering you're using a PR version and not the actual version in the repo, this issue is invalid.
Instead comment it on the PR. #505
