### ISSUE TITLE
The second Tank disappears in C10M5 finale sometime

### ISSUE THREAD

**Issue by honghl5** [SirPlease/L4D2-Competitive-Rework#517]
[Here's the vedio record](https://www.bilibili.com/video/BV17B4y1Y7Kp?spm_id_from=444.41.list.card_archive.click&vd_source=10bd4ba07ec47f7bc5ff14ed3165d31e&t=3260.7)

The second Tank should show up in 1st round, but the boat was coming instead. Because survivors didn't make it in the first Tank, I dont know there was the same situation in 2nd round.
And a friend of mine tells me that he saw the same thing happened once.
I dont know how the frequency of this bug showing is. But this bug could cause lots of match issues.

**Comment by lunatixxx** [comment]
Finale script bugs. 
If player leave first tank control to AI you can be sure that it will glitch the second.

https://github.com/Tsuey/L4D2-Community-Update/issues/48

**Comment by honghl5** [comment]
Thanks for explaination. Hoping a solution.

**Comment by jensewe** [comment]
It isn't an issue with the script system. Tank might fail to spawn because of `ZombieManager::GetRandomPZSpawnPosition`, and somehow the event manager advances regardless, as a result the rescue vehicle comes in.
