### ISSUE TITLE
l4d_tank_rush.smx

### ISSUE THREAD

**Issue by justtheletterjwithadot** [SirPlease/L4D2-Competitive-Rework#52]
Hi Sir,

In your latest commit, you have updated l4d_tank_rush.smx

Just wondering, is it supposed to be in each config's plugin folder instead of "../optional/"?

Regards,
J.

**Comment by SirPlease** [comment]
No, none of provided configs make use of the plugin and I've therefor moved it to the optional folder as eventually I will be transferring all the shared plugins to the optional folder to prevent clutter.

**Comment by justtheletterjwithadot** [comment]
Ah! My bad.

Thank you for clarifying!

Regards,
J.
