### ISSUE TITLE
OnRoundLiveCountdownPre

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#522]
I tried to use this forward (OnRoundLiveCountdownPre) of readyup for a plugin, but if players cancel the start countdown then it seems to not be taken in consideration anymore. Is it just how it works?

**Comment by lunatixxx** [comment]
Anyway it's easy to get around it with OnRoundLiveCountdown and a timer to reset to previous state.

**Comment by jensewe** [comment]
An update to readyup recently has fixed this one, new forward in the following link
https://github.com/Target5150/MoYu_Server_Stupid_Plugins/blob/7e4e951dd8749d0f8c59746d2d782caf7df30809/include/readyup.inc#L62

Source and plugin
https://github.com/Target5150/MoYu_Server_Stupid_Plugins/tree/master/The%20Last%20Stand/readyup
