### ISSUE TITLE
Skill_detect problems

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#525]
g_hCvarDeathChargeHeight is preventing some death charges to being reported (the sacrifice map 1, parish map 5, ect)

Also half of the time fully leveled chargers are wrong and same for hunter skeets that are supposed to be teamskeet, maybe it could be improved.

**Comment by SirPlease** [comment]
I'm not leaving this up an issue as I've stated before that there's zero interest in reworking this plugin.
