### ISSUE TITLE
Some players blocking slots (intentionally or not)

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#526]
I already tried: https://forums.alliedmods.net/showthread.php?t=103203

But this plugin crash server when you use sm_changelevel or sm_map, and have plenty of errors too with timers.

Usually long loaders will be ejected automatically, but some are still keeping the slot forever and the only way is to kick them as they appear in admin menu.

**Comment by SirPlease** [comment]
AFAIK these people are no longer communicating with the server, I'd suggest just modifying `sv_timeout` which has a default value of "65".

This is not an issue related to the Competitive Rework.
