### ISSUE TITLE
30s delay time of losing frustration begins to count eventhough door doesnt open in C7M1

### ISSUE THREAD

**Issue by honghl5** [SirPlease/L4D2-Competitive-Rework#529]
I think it is a real problem for SI.
If survivors touch the train door for Tank spawn but do not open it, the delay time will begin to count down. Survivors wait 30s. And then after they open the train door, Tank will begin to lose frustration.
Maybe it is necessary that the delay time counts down after the train door open？

**Comment by SirPlease** [comment]
Zonemod 2.8 will be coming out with a different approach to this Tank that will indirectly resolve this issue, it obviously will not be a global fix which means that if you'd like to apply it to your configs or setups, you could use check out @jensewe's PR [here](https://github.com/Derpduck/L4D2-Comp-Stripper-Rework/pull/42)

I'll be closing this on Zonemod's update.
