### ISSUE TITLE
Alarm-car does not trigger when survivor touches the car body side

### ISSUE THREAD

**Issue by honghl5** [SirPlease/L4D2-Competitive-Rework#541]
Recently, lots of players find that the alarm will not be triggered if survivor just touches the side of alarm-car, eventhough Smoker drags survivor to. The alarm-car will be triggered Only if survivor stands on the car, push  or shot the car.  Survivors always trigger the alarm if they touches the alarm-car in any way in my memory. Is that designed or?

**Comment by vikingo12** [comment]
Can confirm this, had many moments like these when randomly touching a car but alarm doesn't trigger

**Comment by SirPlease** [comment]
Any video footage would help

**Comment by vikingo12** [comment]
> Any video footage would help

https://www.youtube.com/watch?v=dZlOHe3jUdk

**Comment by SirPlease** [comment]
I've gone ahead and confirmed that this also happens in vanilla 🤷‍♂️

**Comment by vikingo12** [comment]
> I've gone ahead and confirmed that this also happens in vanilla man_shrugging As for smoker pulls not activating a car, I have yet to see that.

https://youtu.be/rm-RDiW9j00

**Comment by SirPlease** [comment]
> https://youtu.be/rm-RDiW9j00

I've been unable to reproduce that, I just went ahead and tried again for 3 more attempts. Two pulls by a player smoker and one by an AI, the alarm always triggered.
What was your testing environment?

**Comment by vikingo12** [comment]
> > https://youtu.be/rm-RDiW9j00
> 
> I've been unable to reproduce that, I just went ahead and tried again for 3 more attempts. Two pulls by a player smoker and one by an AI, the alarm always triggered. What was your testing environment?

1v1 cfg with bots
