### ISSUE TITLE
sv_forcepreload is bad

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#542]
It got removed from TF2 and csgo long time ago.

https://www.reddit.com/r/GlobalOffensive/comments/adq2a4/comment/edlbh3d/?st=JQSQ5GJB&sh=5d987640

**Comment by SirPlease** [comment]
Your comment is regarding client side preloading, not server side preloading.

**Comment by SirPlease** [comment]
To be honest, I have no idea why that description is there as all it does is server-side preloading which has no impact on clients as all.

In the end it pretty much comes down to your own perception of its effectiness, pre-loading sounds like a good thing in most cases, but I don't think it has been explored in depth.
