### ISSUE TITLE
c1m3 old path bug

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#560]
The tank can break the vending machine + the door by mistake and free the way, it's not consistent but it happened two times to me. Both props collide i suppose? Sometimes the position is not always exactly the same with stripper, i noticed that with physic props.

**Comment by Derpduck** [comment]
Can you provide a video of this? The vending machines are not physics props and tank shouldn't be able to break them so I'm a bit confused.

**Comment by Derpduck** [comment]
This is normal, the props to block the paths don't spawn until survivors do the drop just before this.

**Comment by Derpduck** [comment]
Yes.
