### ISSUE TITLE
Possibility of using some single plugins on Windows system

### ISSUE THREAD

**Issue by X7sd** [SirPlease/L4D2-Competitive-Rework#565]
I'm searching for some interesting plugins for my server.
My server only hosts coop mode campaign, but I still need skill infomation and mvp list to show in game.
So is it possible to only use survivor_mvp.smx and l4d2_skill_detect.smx without installing the whole Zonemod on a Windows server?

**Comment by SirPlease** [comment]
As long as you keep track of dependencies and whether or not they require gamedata/extensions that aren't supporting Windows, you'll be fine.

The plugins you've listed rely on the [Left4DHooks](https://forums.alliedmods.net/showthread.php?t=321696) extension, which means you'll need to have it installed.

**Comment by X7sd** [comment]
I installed two plugins with Left4DHooks installed.
l4d2_skill_detect.smx has some information printed on server console but print nothing in game.
survivor_mvp.smx do not work at all.
Do I need config files to make them to run properly or I should put them in /plugins/optional?

**Comment by SirPlease** [comment]
Please make sure you both understand the purpose and functionality of a plugin as well as them actually being loaded.
I believe the functionality you're looking for is the [l4d2_stats](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/l4d2_stats.sp) plugin, which prints out skeets, boomer pops, etc. in chat.

survivor_mvp.smx should be printing out the mvp at the end of the round or when a player uses the `!mvp` command.

**Comment by A1mDev** [comment]
As far as I know all plugins and extensions support windows except the Collisionhook extension.

**Comment by vikingo12** [comment]
> As far as I know all plugins and extensions support windows except the Collisionhook extension.

collisionhook does support windows, at least on my server it works flawlessly

**Comment by vikingo12** [comment]
> I installed two plugins with Left4DHooks installed. l4d2_skill_detect.smx has some information printed on server console but print nothing in game. survivor_mvp.smx do not work at all. Do I need config files to make them to run properly or I should put them in /plugins/optional?

by default the prints are disabled, put this in your server config:
sm_skill_report_enable 1
sm_skill_report_old 1

survivor_mvp also requires colors, maybe that's why it doesn't work
-> https://forums.alliedmods.net/showthread.php?t=96831
put the .inc file in sourcemod/scriping/include folder

**Comment by A1mDev** [comment]
@vikingo12, this file is already in this repository, it is recommended to use it because this file contains fixes for new versions of the sourcemod, and it is only needed to build the plugin, and then does not participate in the work separately.

**Comment by vikingo12** [comment]
@A1mDev literally nothing will happen if he uses a file from alliedmodders
