### ISSUE TITLE
Does l4d2_weapon_attributes load when every map starts or only load once at start of the campaign?

### ISSUE THREAD

**Issue by X7sd** [SirPlease/L4D2-Competitive-Rework#587]
I set the damage of Scout to 200 and AWP to 350 so that they may have more chance to be picked up by players.
I just simply write
`ServerCommand("sm_weapon sniper_scout damage 200");
ServerCommand("sm_weapon sniper_awp damage 350");`
in OnMapStart()
But the settings do not work when entering a new map.

**Comment by fantasylidong** [comment]
Why not just write in shared_settings which will be autoloaded in new map.

**Comment by X7sd** [comment]
> Why not just write in shared_settings which will be autoloaded in new map.

Oh, I'm not using this framework. I just use the single plugin so thers's no shared_settings in my server.

**Comment by fantasylidong** [comment]
> > Why not just write in shared_settings which will be autoloaded in new map.
> 
> Oh, I'm not using this framework. I just use the single plugin so thers's no shared_settings in my server.

In that case, write in the server.cfg does the same thing.

**Comment by SirPlease** [comment]
`OnMapStart()` is too early.
If you don't want to use the server.cfg, you can enter your commands in `OnConfigsExecuted` instead.
