### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by CanadianJeff** [SirPlease/L4D2-Competitive-Rework#59]
https://github.com/SirPlease/L4D2-Competitive-Rework/blob/e82dacf5f4b4affcf8634398aebf508ab64c0783/cfg/server.cfg#L72

**Comment by SirPlease** [comment]
No, it's correct.
This is done to prevent having **sv**_maxplayers being set on map change, as server.cfg gets called on every map load.

**mv**_maxplayers is added by the modified match_vote plugin and will simply set sv_maxplayers on plugin load. (Which is on config unload as well as load)
