### ISSUE TITLE
Parish Map 2 Weapon Asymmetry

### ISSUE THREAD

**Issue by honkthebonk2** [SirPlease/L4D2-Competitive-Rework#60]
While playing on our modified version of zonemod, I noticed a 100% consistent issue that happens on map 2 of the Parish, where this table:
![1](https://user-images.githubusercontent.com/41553860/67618026-f519f500-f7ae-11e9-8a83-ba652d89bc2b.png)
will only have one weapon spawn for the first round,
![2](https://user-images.githubusercontent.com/41553860/67618030-fc410300-f7ae-11e9-9f74-c623a3fcab30.png)
but have two weapon spawns for the second round. I realize this isn't on your servers nor is it the most up-to-date version of zonemod, but when devilesk ran a diff between our version and 1.9.4 I didn't see any changes that would fix this.

**Comment by devilesk** [comment]
It looks like it's these entities that are removing a weapon spawn. Don't know why it only happens for the first round though.
```
{
"origin" "-6836 -5520 -247"
"targetname" "case_weapon_spawn"
"classname" "logic_case"
"hammerid" "1514758"
"OnCase01" "weapon_spawn_shotgunKill0-1"
"OnCase02" "weapon_spawn_rifleKill0-1"
}{
"origin" "-6852 -5520 -247"
"spawnflags" "1"
"classname" "logic_auto"
"hammerid" "1514800"
"OnMapSpawn" "case_weapon_spawnPickRandom0-1"
}
```

Adding the following stripper rule to c5m2_park.cfg fixes it though:
```
filter:
{
	"targetname" "case_weapon_spawn"
}
```
