### ISSUE TITLE
witch spawn problem.

### ISSUE THREAD

**Issue by a847427933** [SirPlease/L4D2-Competitive-Rework#607]
Is there any way to spawn witch in zonemod 2.8?

**Comment by vikingo12** [comment]
zonemod.cfg 
change confogl_addcvar sm_witch_can_spawn 0 to 1

**Comment by a847427933** [comment]
> zonemod.cfg change confogl_addcvar sm_witch_can_spawn 0 to 1

Thank you.
And there's other question, how to remove 30tick when you are spectator？

**Comment by vikingo12** [comment]
shared_plugins.cfg
remove sm plugins load optional/specrates.smx

**Comment by a847427933** [comment]
> shared_plugins.cfg remove sm plugins load optional/specrates.smx

Thank you for your answer. All the problems have been solved.
