### ISSUE TITLE
Removed lobby reservation Funtion.

### ISSUE THREAD

**Issue by a847427933** [SirPlease/L4D2-Competitive-Rework#619]
I set /root/steam/l4d2/left4dead2/cfg/cfgogl/zonemod/shared_cvars.cfg/confogl_match_killlobbyres 0.
but Removed lobby reservation still working while start the server.
when i try to connect the server,i will get kicked back to the main menu with ''Server error - failed to handle reservation request.''in console.

**Comment by vikingo12** [comment]
remove sm_killlobbyres from shared_settings

**Comment by a847427933** [comment]
> remove sm_killlobbyres from shared_settings

Thank you
