### ISSUE TITLE
Allow infecteds to choose who will be the Tank each round

### ISSUE THREAD

**Issue by altair-sossai** [SirPlease/L4D2-Competitive-Rework#626]
I customized the l4d_tank_control_eq plugin to allow the infected to choose who will be the tank.
At the beginning of each round (after !ready) the infected are shown a choice menu with the names of players who have not yet been Tank, at the end of voting or after a certain time (if someone does not vote) the tank is chosen.

The code is in my GitHub, can be accessed through the link below:
https://github.com/altair-sossai/l4d2-zone-server/blob/master/addons/sourcemod/scripting/l4d_tank_control_eq.sp

If you are interested in including it in the main repository, feel free to copy it.
It might be interesting to add parameters that can turn this functionality on/off, for now it doesn't exist, but if you're interested, I can include it

The development was based on the following repository:
https://github.com/alexberriman/l4d2-plugins/tree/master/l4d_tank_vote

**Comment by vikingo12** [comment]
From what I know, Sir said that players must learn to play tanks instead of skipping them, plus if it was needed, there is already a plugin made long time ago

**Comment by SirPlease** [comment]
This is not something I'm interested in adding to Zonemod, but I appreciate you sharing it 😄
