### ISSUE TITLE
max_distance is defined twice in mapinfo.txt of certain nextmod configs. 

### ISSUE THREAD

**Issue by AshesBeneath** [SirPlease/L4D2-Competitive-Rework#63]
I don't if this would cause issue but it visually annoys tbh. 

https://github.com/SirPlease/L4D2-Competitive-Rework/blob/a0781f57ce2226d9eecfa0f8048b57381f2a85f3/cfg/cfgogl/nextmod1v1/mapinfo.txt#L1530

https://github.com/SirPlease/L4D2-Competitive-Rework/blob/a0781f57ce2226d9eecfa0f8048b57381f2a85f3/cfg/cfgogl/nextmod2v2/mapinfo.txt#L1555

https://github.com/SirPlease/L4D2-Competitive-Rework/blob/a0781f57ce2226d9eecfa0f8048b57381f2a85f3/cfg/cfgogl/nextmod3v3/mapinfo.txt#L1598

https://github.com/SirPlease/L4D2-Competitive-Rework/blob/a0781f57ce2226d9eecfa0f8048b57381f2a85f3/cfg/cfgogl/nextmodpug/mapinfo.txt#L1604

https://github.com/SirPlease/L4D2-Competitive-Rework/blob/a0781f57ce2226d9eecfa0f8048b57381f2a85f3/cfg/cfgogl/nextmod/mapinfo.txt#L1530

**Comment by SirPlease** [comment]
🙄 Spoon.
