### ISSUE TITLE
srcscramble.ext issue on Ubuntu 18.04

### ISSUE THREAD

**Issue by theletterjwithadot** [SirPlease/L4D2-Competitive-Rework#633]
Commit https://github.com/SirPlease/L4D2-Competitive-Rework/commit/440f3461b6eb7809034f10ad8aec9a1557f31753 causing the following error:  `[SM] Unable to load extension "srcscramble.ext": /lib/i386-linux-gnu/libc.so.6: version 'GLIBC_2.32' not found`

~~Checked with @sheo9000 and @Target5150, and they are facing the same issue too.~~

Checked with @sheo9000 and @Target5150.
@Target5150 is facing the same issue on his servers too. @sheo9000 hasn't checked his.

**Comment by sheo9000** [comment]
I did not check if I have same issue

**Comment by A1mDev** [comment]
Try it - https://github.com/L4D-Community/SMExt-SourceScramble/actions

**Comment by SirPlease** [comment]
The commit was reverted after realizing we already had one, big derp of a commit.
