### ISSUE TITLE
Saferoom door can be brake in versus

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#636]
I saw occasionnally tank brake saferoom door a few times now for start and end saferoom, i don't know if this is a bug in vanilla or by tank punch fix plugin. Survivors could potentially not finish a map.

**Comment by SirPlease** [comment]
It's normal for a Tank to be able to break the `starting` saferoom door by simply walking up against it.
The tank is unable to punch the door out, and this behavior does not apply to end saferoom doors.
