### ISSUE TITLE
Release tagging

### ISSUE THREAD

**Issue by keyCat** [SirPlease/L4D2-Competitive-Rework#65]
Hello!

I have a small suggestion to make.
Since this repository become not only a repo for competitive framework, but also a main repo for releasing several configs, could you mark releases of configs and changes to the framework using [Git tagging](https://git-scm.com/book/en/v2/Git-Basics-Tagging)? It would help a lot.

Thanks for the work.

**Comment by SirPlease** [comment]
Heyo,

I personally am a pleb and just make use of the Github UI as it's user friendly and easy to do, which unfortunately **STILL** does not support tagging.
