### ISSUE TITLE
Tank spawn position diffrent after l4d2 last version update

### ISSUE THREAD

**Issue by Kaze1027** [SirPlease/L4D2-Competitive-Rework#656]
Have you guys found that the tank would spawn earlier or later than before, such as on C2M1, tank would spawn when survivors get to motel, but now it spawn earlier nearby the bridge. And it's worse on C1M1, tank will spawn when survivors get to the cleaning cart around the corner in the first hallway, sometimes two of survivors have to fight tank with only melee. LOL

**Comment by vikingo12** [comment]
the spawns are randomized

**Comment by SirPlease** [comment]
I haven't heard any reports on this so far and haven't really played the game myself after the patch.
I've ran a quick test myself and the lowest valuable possible in ZoneMod for C1M1 is 25%.
This Tank spawn triggered about one door before the weapons, so it shouldn't be a problem.

Did you happen to play this on another config like `Apex`, `NextMod` or Promod Elite?
These configs still allow the Tank to spawn between 20% and 28% which would indeed be at the cleaning cart.

Either way, I have no indication that anything is broken with the Tank spawning system.

**Comment by honghl5** [comment]
I heard two reports about this(c2m1) in my servers. Tank accidently spawn behind the survivors, but just happened once. And  BTW, I got this following error every time in c2m1 in confoglcompmod's logs:
L 05/22/2023 - 11:52:26: [CvarSettings] [c2m1_highway] Could not find CVar specified (confogl_boss_unprohibit)
L 05/22/2023 - 18:14:52: [CvarSettings] [c2m1_highway] Could not find CVar specified (confogl_boss_unprohibit)
L 05/22/2023 - 18:16:32: [CvarSettings] [c2m1_highway] Could not find CVar specified (confogl_boss_unprohibit)
L 05/22/2023 - 18:22:55: [CvarSettings] [c2m1_highway] Could not find CVar specified (confogl_boss_unprohibit)
L 05/22/2023 - 18:26:07: [CvarSettings] [c2m1_highway] Could not find CVar specified (confogl_boss_unprohibit)
L 05/22/2023 - 18:35:33: [CvarSettings] [c2m1_highway] Could not find CVar specified (confogl_boss_unprohibit)
L 05/22/2023 - 18:45:30: [CvarSettings] [c2m1_highway] Could not find CVar specified (confogl_boss_unprohibit)
L 05/22/2023 - 18:46:59: [CvarSettings] [c2m1_highway] Could not find CVar specified (confogl_boss_unprohibit)
L 05/22/2023 - 18:52:24: [CvarSettings] [c2m1_highway] Could not find CVar specified (confogl_boss_unprohibit)
L 05/22/2023 - 18:54:11: [CvarSettings] [c2m1_highway] Could not find CVar specified (confogl_boss_unprohibit)
L 05/22/2023 - 19:08:34: [CvarSettings] [c2m1_highway] Could not find CVar specified (confogl_boss_unprohibit)
L 05/22/2023 - 19:32:44: [CvarSettings] [c2m1_highway] Could not find CVar specified (confogl_boss_unprohibit)
L 05/22/2023 - 19:36:05: [CvarSettings] [c2m1_highway] Could not find CVar specified (confogl_boss_unprohibit)
L 05/22/2023 - 19:49:48: [CvarSettings] [c2m1_highway] Could not find CVar specified (confogl_boss_unprohibit)
L 05/22/2023 - 19:52:02: [CvarSettings] [c2m1_highway] Could not find CVar specified (confogl_boss_unprohibit)

**Comment by honghl5** [comment]
I didnot change the cfgogl file (should be shared_cvars.cfg specified). Just report an error Σ(⊙▽⊙"a

**Comment by vikingo12** [comment]
do you or not cause it seems like your confoglcompmod doesnt have it loaded

**Comment by vikingo12** [comment]
well do you have a confoglcompmod folder in your scripting folder?

**Comment by honghl5** [comment]
oh, I know what you mean actually. So it, this error, doesnt matter. I can load it or do not load it.  Because other plugin does the same thing. I am just carious. ty for your patience

**Comment by Kaze1027** [comment]
Thx for you guys' answers, I think I got it wrong.
