### ISSUE TITLE
Tank attribution could be improved

### ISSUE THREAD

**Issue by LuckyServ** [SirPlease/L4D2-Competitive-Rework#664]
Sometimes players get tanks twice before other players on the team got it a single time. Not sure what causes this.

Also:

- Player who is chosen to have tank disconnects / spectates and comes back before tank spawns => Should pass back to him.
- Player who is chosen to have tank disconnects / spectates and tank spawns, then player comes back => Should not pass back to him.

Might give a go at fixing the plugin, will submit a PR if I do.

**Comment by Krevik** [comment]
I have sth similiar on my server, you might want to modify it and use it
https://github.com/Krevik/Kether.pl-L4D2-Server/blob/kether_2.0/addons/sourcemod/scripting/l4d_tank_control_eq_kether.sp

**Comment by altair-sossai** [comment]
I've implemented an improvement that ensures that the starting players on each team have priority in controlling the Tank. For example, if a player who previously controlled the Tank is replaced, the new player will not take over the Tank until everyone else has had their turn. Does this make sense to you? Is this a valid improvement?

**My commit has not been tested yet, and I will conduct the tests in the coming days.**

https://github.com/altair-sossai/l4d2-zone-server/commit/62020836a02737d89ef8ee85701b6cb5a1664ac8

**Comment by LuckyServ** [comment]
While fixing this issue for my servers I came accross the forward **TankControl_OnTankSelection** that allows you to setup your own algo on how you want tank attribution to work. arti likely realised (rightfully) that each server owner would potentially like to run their own algo.

You can change the default algo however you want in l4d_tank_control_eq.sp, but just please make sure that the forward still works the same as before.

**Comment by altair-sossai** [comment]
Apparently the correction respects the `TankControl_OnTankSelection` handler, as it is only used if the return of this function is empty.

![image](https://github.com/SirPlease/L4D2-Competitive-Rework/assets/11737883/5a9ce42e-5139-4550-8558-5d8fcb5b8ddd)
