### ISSUE TITLE
Error in vscript file c4m2_sugarmill_a_navfixes.nut

### ISSUE THREAD

**Issue by A1mDev** [SirPlease/L4D2-Competitive-Rework#667]
```
[NavFixes] c4m2_sugarmill_a_navfixes initialized


AN ERROR HAS OCCURED [the index 'ConnectTo' does not exist]

CALLSTACK
*FUNCTION [main()] scripts/vscripts/nav_fixes/c4m2_sugarmill_a_navfixes.nut line [15]

LOCALS
[fix1_nav_a2] NULL
[fix1_nav_a1] INSTANCE
[fix1_jesusNav] NULL
[vargv] ARRAY
[this] TABLE
```

**Comment by Derpduck** [comment]
Do you have a modified nav mesh file on the server?

**Comment by A1mDev** [comment]
> Contributor

Yes

**Comment by A1mDev** [comment]
> Do you have a modified nav mesh file on the server?

Yes. I use some stuff from [TLS repository](https://github.com/Tsuey/L4D2-Community-Update)

**Comment by Derpduck** [comment]
The nav mesh has been modified to directly address the issue this script is for, so the nav IDs the function uses no longer exist and the script would be redundant.

**Comment by SirPlease** [comment]
I'll go ahead and close this, as it appears that this is not an issue related to the repository, but your own setup.
