### ISSUE TITLE
[BUG] Server crash or freeze due to actions extension

### ISSUE THREAD

**Issue by A1mDev** [SirPlease/L4D2-Competitive-Rework#671]
**Describe the bug**
Server crash or freeze due to extension `actions`, problem occurs when process srcds terminates.

**To Reproduce**
Start the server along with the `actions` extension, write `quit` to the console. After that there is a memory leak or something like that.

**Server Operating System (if applicable):**
 - Ubuntu 22.04. Seems to appear on the Windows too.

**Comment by SirPlease** [comment]
I've tested it on version `2.7` (prior Github version) and it indeed got stuck on `quit`.
The update has resolved this issue.

**Comment by vikingo12** [comment]
> Owner

no windows support?

**Comment by PaaNChaN** [comment]
i added the updated actions ext, but there was an error in the sorucemod log.
OS Version: Ubuntu 20.04
```
L 06/21/2023 - 19:59:53: SourceMod error session started
L 06/21/2023 - 19:59:53: Info (map "c2m1_highway") (file "~~/left4dead2/addons/sourcemod/logs/errors_20230621.log")
L 06/21/2023 - 19:59:53: [SM] Unable to load extension "actions.ext": /lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ~~/left4dead2/addons/sourcemod/extensions/actions.ext.2.l4d2.so)
L 06/21/2023 - 19:59:53: [SM] Unable to load plugin "fixes/l4d2_shove_fix.smx": Required extension "Actions" file("actions.ext") not running
L 06/21/2023 - 19:59:57: Error log file session closed.
```

i have resolved the error by using the following actions ext.
https://forums.alliedmods.net/showpost.php?p=2805288&postcount=80
