### ISSUE TITLE
checkpoint-rage-control.smx Exception Error

### ISSUE THREAD

**Issue by PaaNChaN** [SirPlease/L4D2-Competitive-Rework#676]
im using the latest gamedata and i get the following error in the log.
```
L 06/29/2023 - 22:45:32: [SM] Exception reported: Saferoom Check Offset or signature seems incorrect
L 06/29/2023 - 22:45:32: [SM] Blaming: optional/checkpoint-rage-control.smx
L 06/29/2023 - 22:45:32: [SM] Call stack trace:
L 06/29/2023 - 22:45:32: [SM]   [0] SetFailState
L 06/29/2023 - 22:45:32: [SM]   [1] Line 195, x:\GitHub\Copy_L4D2-Competitive-Rework\addons\sourcemod\scripting\checkpoint-rage-control.sp::FindPatchTarget
L 06/29/2023 - 22:45:32: [SM]   [2] Line 60, x:\GitHub\Copy_L4D2-Competitive-Rework\addons\sourcemod\scripting\checkpoint-rage-control.sp::OnPluginStart
```

**Comment by jensewe** [comment]
I can confirm the gamedata has nothing bad on both windows and linux. You might want to check the plugin as well.

**Comment by PaaNChaN** [comment]
hello Forgetest.
i have already verified that the plugin is also the latest version.
looking at the error logs, it seems that sometimes it occurs and sometimes it does not.
also, it occurs only in chapter1.

**Comment by jensewe** [comment]
Duplicate plugin?

**Comment by PaaNChaN** [comment]
i found the cause.
my server is Instead of using `predictable_unloader.smx`, I was using the `sm plugins unload_all` command to unload all plugins on the server.
there are several reasons why i was using the `sm plugins unload_all`, but when I stopped using it and unloaded using `predictable_unloader.smx`, the error disappeared.

**Comment by vikingo12** [comment]
> i found the cause. my server is Instead of using `predictable_unloader.smx`, I was using the `sm plugins unload_all` command to unload all plugins on the server. there are several reasons why i was using the `sm plugins unload_all`, but when I stopped using it and unloaded using `predictable_unloader.smx`, the error disappeared.

can you share your method of unloading plugins on your server and does it work better than the plugin?

**Comment by PaaNChaN** [comment]
now i use `predictable_unloader.smx` to unload plugins.
as a result, Exception Error no longer occurs.

**Comment by vikingo12** [comment]
> now i use `predictable_unloader.smx` to unload plugins. as a result, Exception Error no longer occurs.

nonono, what was your original method? was it just unload_all in confogl_off.cfg?

**Comment by PaaNChaN** [comment]
after `sm plugins unload_all` in `confogl_off.cfg`, load all plugins needed to use `sm_match` & `sm_forcematch`.

**Comment by vikingo12** [comment]
> after `sm plugins unload_all` in `confogl_off.cfg`, load all plugins needed to use `sm_match` & `sm_forcematch`.

good, thanks

**Comment by SirPlease** [comment]
> now i use `predictable_unloader.smx` to unload plugins. as a result, Exception Error no longer occurs.

Yep, that'd be it.
#142 describes the issue best, the old method was basically to just `sm plugins unload_all` followed by `sm plugins refresh`

**Comment by BRU7U5** [comment]
This problem takes place on my example. The "checkpoint-rage-control" plugin is installed on my server by standard. And after loading the config via "!match", this plugin is first unloaded, and then tries to load again via the config "zonemod". But as a result, this error appears and this plugin does not work. Moreover, when disabling the "zonemod" config, this plugin tries to load again and this error appears again. The decision to cancel the reloading of the map after the command "!rmatch" is also incomprehensible to me. Yes, the server is mostly restored to standard settings, but apparently not all ConVar are restored to the correct values, which often causes a trivial error related to the lack of players in the opposite team. I get this error when I used !rmatch when I was alone on the server. The fact of this error is not as bad as the fact that it could be an indirect cause of other ConVars potentially getting incorrect values as well.

**Comment by SirPlease** [comment]
>  The decision to cancel the reloading of the map after the command "!rmatch" is also incomprehensible to me.
This was done to prevent having to sit through the map reload only to vote again, which is what players tend to do when they `!rmatch`.
The map will reload when loading the next config to clean up any potential leftovers (mostly stripper:source focused).

I'll consider reloading the map by default as we now have a `!chmatch` command.

>  Yes, the server is mostly restored to standard settings, but apparently not all ConVar are restored to the correct values, which often causes a trivial error related to the lack of players in the opposite team.

At first I couldn't reproduce this error as the server was on campaign when I loaded a matchmode, meaning it'd revert to campaign after unload, but I've located the cause of this.
Confoglcompmod (ReqMatch module) is hardforcing the `sb_all_bot_game` value to `0` after a config is unloaded.
I'll push a patch for this later today 👍 

All other settings are reset properly on config unload, so it's not a worry.

**Comment by BRU7U5** [comment]
> During brief tests, the issue occurs during patching.
> I have to admit I haven't spent much time on it as it generally isn't an issue with expected behaviour.

I have to admit that I may have been misleading about the "checkpoint-rage-control" plugin. To be more precise, one of the latest versions of this plugin has an error with reloading of this plugin. I found a compiled file of an older version (not sure if there is something different there), but it works fine. After unloading and loading it back in, it does not cause any problems. Now I'm starting to get suspicious of the SourcePawn compiler.

> I'll consider reloading the map by default as we now have a !chmatch command.

I think it makes sense to reboot the map after disabling "Confogl". Players can now change configs via "!chmatch" if they want to, so in my opinion rebooting the map after disabling "Confogl" will only make the process cleaner.

> At first I couldn't reproduce this error as the server was on campaign when I loaded a matchmode, meaning it'd revert to campaign after unload, but I've located the cause of this.
> Confoglcompmod (ReqMatch module) is hardforcing the sb_all_bot_game value to 0 after a config is unloaded.

I was just looking at that module today too, and found it hard-setting "sb_all_bot_game" to "0". I don't quite understand why it was done. But maybe it was done to prevent bots from automatically going through the map if the server is empty. But, in general, I think no one will have this problem, as most servers automatically restart the server if all players leave it.

> I'll push a patch for this later today 👍

Thanks!

> All other settings are reset properly on config unload, so it's not a worry.

I agree. I double-checked everything again today. And restoring the settings works fine. The "sb_all_bot_game" made it feel like the config unloading was incorrect.

--------------------------------------------------------------------------------------------------------------
Regarding "checkpoint-rage-ccontrol" and SourcePawn compiler, I would like more experienced coders like Forgetest ( if they have the desire :) ) to check this theory and maybe we could find the real cause of this failure.

Thanks for the reply!
