### ISSUE TITLE
[Question] Tickrate fixes

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#68]
Is it really relevant with a server on 60 tickrate ? Personally i don't see anything weird happening and if it does it must be very minimal, but yep probably than it is a problem with 120 tick.

**Comment by SirPlease** [comment]
The plugin was in development while we were using 60 Tick, so yeah, the same issues are there. (Slower doors, pistol firing speed and fall damage at certain spots where you shouldn't be taking any). However, the door speed plugin would definitely need a bit of tweaking as doors are slower but not as slow as on 100 tick.
It's been too long to remember if gravity needed tweaking.

**Comment by lunatixxx** [comment]
Thanks for answer. By the way i can't compile the last sp version, it ask for smlib/general ect

**Comment by SirPlease** [comment]
Can I mark this as resolved or do you have any further questions? :)

**Comment by lunatixxx** [comment]
All good thanks
