### ISSUE TITLE
[Request / Question] World index instead of hittable index

### ISSUE THREAD

**Issue by jensewe** [SirPlease/L4D2-Competitive-Rework#683]
**Is your feature request related to a problem? Please describe.**
https://github.com/SirPlease/L4D2-Competitive-Rework/blob/85bfb47fed37281d18cbd9dbed31eea5e43ce9a5/addons/sourcemod/scripting/l4d2_hittable_control.sp#L430
Does this really fix issues? Or it just ruins the whole attack trace, damage tracking for hittables?

**Describe the solution you'd like**
Remove this line and luckily nothing is going to bug out, or fix issues lying behind.

**Describe alternatives you've considered**
Provide a way to allow other plugins to track hittable damages.

**Comment by SirPlease** [comment]
It was a band-aid fix to prevent clear cases where the hittable would refuse to apply damage (IIRC it'd happen on when a Survivor got hit by another hittable slightly before getting hit by another)

A good test case for this was by placing a bin/table near a survivor and then smashing a dumpster into them, they'd take damage from the bin/table but the dumpster would touch them and do nothing.

**Comment by jensewe** [comment]
Thanks for the info.
Looks like there's a built-in overhit protection and after tests it tends to be the exact cause.

```cpp
int CTerrorPlayer::OnTakeDamage_Alive(const CTakeDamageInfo &info)
{
    ...

    if ( info.m_bitsDamageType == DMG_CRUSH && info.m_hInflictor && CanCausePlayerPhysicsDamage(info.m_hInflictor) )
    {
        if ( (m_physOverhitTimer.HasStarted() && !m_physOverhitTimer.IsElasped())
          || (IsIncapacitated() && info.m_flDamage < 50.0) )
        {
            return 0; // prevents damage
        }
        m_physOverhitTimer.Start(2.0);
    }

    ...
}
```
