### ISSUE TITLE
[REQ] Consistency fix logtofile

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#69]
Could you add a log file function so it will be more easy to track people who modify files ?

**Comment by SirPlease** [comment]
AFAIK there's no way to track exactly what file the client was missing, or had modified.
If you were to use this for banning, it'd be quite harsh as can end up with errors like these because of certain addons (often the boomer model).

**Comment by lunatixxx** [comment]
Not to ban but in a log just to remember than this player had missing or modified files.

**Comment by SirPlease** [comment]
I assume you'd like this to get logged the moment the player gets kicked when attempting to connect?
I figured the reason on "player_disconnect" wouldn't help in this, but I tested it to make sure. Player Disconnect will simply give "Disconnect by user" as reason and I can't find a reliable hook for something like this.
I'll dig a bit deeper with assembly, but no promises

**Comment by SirPlease** [comment]
This is a no go, sorry.
