### ISSUE TITLE
[BUG] Spit Spread Patch

### ISSUE THREAD

**Issue by Unfellowed** [SirPlease/L4D2-Competitive-Rework#697]
Acid beach becomes invisible.
https://youtu.be/FV335O_9nDc

**Comment by jensewe** [comment]
Thanks for reporting but where it is?

**Comment by Unfellowed** [comment]
I changed #include < collisionhook > to < sdkhooks > for the plugin to work. Is this the cause of the problem?
https://youtu.be/1MMG7BQkqXU

**Comment by jensewe** [comment]
In the first place the plugin is set to rely on collision hook. What do you mean by making the plugin to "work"?
Are you troubled by issues of **collision hook on windows**? It sounds like you don't have collision hook in your server.

**Comment by Unfellowed** [comment]
Oh, I updated the extension from this post and they worked. Sorry to bother!
https://forums.alliedmods.net/showpost.php?p=2808098&postcount=158
