### ISSUE TITLE
[BUG] l4d_witch_damage_announce.smx don't work

### ISSUE THREAD

**Issue by Electr0** [SirPlease/L4D2-Competitive-Rework#698]
**Describe the bug**

L 08/09/2023 - 18:31:57: [SM] Exception reported: Invalid memory access
L 08/09/2023 - 18:31:57: [SM] Blaming: optional/l4d_witch_damage_announce.smx
L 08/09/2023 - 18:31:57: [SM] Call stack trace:
L 08/09/2023 - 18:31:57: [SM]   [1] Line 249, ..\\l4d_witch_damage_announce.sp::PrintWitchDamage
L 08/09/2023 - 18:31:57: [SM]   [2] Line 217, ..\\l4d_witch_damage_announce.sp::CalculateWitch
L 08/09/2023 - 18:31:57: [SM]   [3] Line 189, ..\\l4d_witch_damage_announce.sp::WitchDeath_Event

**Comment by A1mDev** [comment]
It seems very strange at some point there are more survivors than indicated by the survivor_limit (4) convar. Do you know how to reproduce this?

**Comment by SirPlease** [comment]
Just to check, is this played on a 4v4 config or less?
Considering the plugin does not actively keep track of `survivor_limit` and instead uses a hardcoded maxlimit of 4.

Also, does it consistently not work or does this error only happen every now and then?
I'll be able to run some test in a bit, but additional information would be appreciated 😄
