### ISSUE TITLE
Loading order mistake

### ISSUE THREAD

**Issue by Electr0** [SirPlease/L4D2-Competitive-Rework#7]
https://github.com/SirPlease/L4D2-Competitive-Rework/blob/3211e015f8ec1036496779e9829e5760c623cfee/addons/sourcemod/scripting/modules/ReqMatch.sp#L121

you forgot upload last changes for confoglcompmod. because in confoglcompmod.smx:
ServerCommand("exec generalfixes.cfg");
ExecuteCfg(sBuffer);
ServerCommand("exec sharedplugins.cfg");

in sources:
ExecuteCfg(sBuffer);
ServerCommand("exec generalfixes.cfg");
ServerCommand("exec sharedplugins.cfg");

this brake loading order because you load plugins => after unload all load plugins because exec generalfixes.cfg after it =D

**Comment by SirPlease** [comment]
Yikes, good catch. I'll upload the correct source and .smx with the next push! 👍

**Comment by Electr0** [comment]
thanks
