### ISSUE TITLE
[BUG] chmatch doesn't reset previous config convars properly.

### ISSUE THREAD

**Issue by SirPlease** [SirPlease/L4D2-Competitive-Rework#706]
**Describe the bug**
When you use `chmatch` to change the config, the convars aren't reset properly.
This leads to possibly undesired changes to the matchmode.

**To Reproduce**
1. Load a matchmode that has way different settings than config2
2. Use !chmatch to load the other config.
3. See the changes from the old config still active in config2.

**Additional context**
The behaviour of `!chmatch` could be added to `!match` to make it less confusing for players, as suggested by sheo (I agree!)

**Comment by blueblur0730** [comment]
The issue with `chmatch` I think is that we ran too fast between the function `RM_Match_Unload(true);` and `RM_Match_Load();`
This is what console shows after using `chmatch`:

`[SM] The loading lock is no longer in effect.
[SM] All plugins have been unloaded.
Unknown command "reset_static_maps"
Unknown command "sm_resetstringcount"
Unknown command "confogl_resetclientcvars"
Unknown command "confogl_resetcvars"
Unknown command "pred_unload_plugins"
[SM] Loaded plugin left4dhooks.smx successfully.
[SM] Loaded plugin optional/l4d2lib.smx successfully.
[SM] Loaded plugin optional/predictable_unloader.smx successfully.
[SM] Loaded plugin fixes/bequiet.smx successfully.
....`

It means before we finished `RM_Match_Unload(true);`, `RM_Match_Load();` ran ahead ([SM] All plugins have been unloaded.) and unloaded some critical plugins we needed, though confogl_off.cfg got excuted. This causes cvars don't get reset properly, plugin predictable_unloader also did nothing, although all plugins loaded.

There should be a delay timer after we run `RM_Match_Unload(true);`, and after we finish unloading, we do loading.
