### ISSUE TITLE
[BUG] c4m3: Elevator closes and moves up even if not all survivors present

### ISSUE THREAD

**Issue by HadwinOFE** [SirPlease/L4D2-Competitive-Rework#717]
**Describe the bug**
In Chapter 4 Map 3(Hard Rain, c4m3), the elevator could close and move up even not all survivors present, the survivor who was left behind will be automatically disposed upon the arrival of the elevator.
(ZoneMod 2.8.7)

**To Reproduce**
Steps to reproduce the behavior(May be inaccurate):
1. Have the last survivor close to the elevator door but not enter
2. The survivors inside continuously interact with the elevator

**Video**
**https://github.com/SirPlease/L4D2-Competitive-Rework/assets/102217417/ae2cf23e-468b-43b0-badc-ab96139e0692**

or(.MP4 ,1080p 60)
**https://drive.google.com/file/d/1ph0ZbooEOKKk-8MlFZPJkH3z2kYZko94/view?usp=sharing**

or(source of the video[ BiliBili ])
**https://b23.tv/GrnthSa**

**Comment by AidenVii** [comment]
maybe we can put the trigger area to more inside , like this :
![c4m3_elev1](https://github.com/user-attachments/assets/6d7a3409-8a49-4adb-bc48-f45e08465b82)
![c4m3_elev](https://github.com/user-attachments/assets/47dfe604-646f-422d-97d5-4c52d48ba57a)

In theory, in this way, it is not guaranteed to solve the problem 100%, but it can also greatly reduce the possibility of problems.
