### ISSUE TITLE
[Question/Request] Remove l4d2_spec_stays_spec.smx due to l4d2_fix_team_shuffle is loaded

### ISSUE THREAD

**Issue by nikita1824** [SirPlease/L4D2-Competitive-Rework#731]
Hello, should we use [l4d2_spec_stays_spec](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/l4d2_spec_stays_spec.sp) if [l4d2_fix_team_shuffle](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/l4d2_fix_team_shuffle.sp) is loaded? Correct me if I'm wrong but, as I understand, l4d2_fix_team_shuffle should solve everything that l4d2_spec_stays_spec does. Aren't these plugins conflicting with each other?

> https://github.com/search?q=repo%3ASirPlease%2FL4D2-Competitive-Rework%20l4d2_spec_stays_spec&type=code

> https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/cfg/generalfixes.cfg#L59

Upd:
Same goes here, [l4d_stuckzombiemeleefix](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/l4d_stuckzombiemeleefix.sp) might be removed due to [l4d_fix_common_shove](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/l4d_fix_common_shove.sp) is loaded.

> https://github.com/search?q=repo%3ASirPlease%2FL4D2-Competitive-Rework%20l4d_stuckzombiemeleefix&type=code

> https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/cfg/generalfixes.cfg#L64

**Comment by SirPlease** [comment]
Thanks for pointing these out, I will go ahead and archive these plugins 😄
