### ISSUE TITLE
[BUG]The server crashes about 10 seconds after the player enters the game

### ISSUE THREAD

**Issue by ziziguaia** [SirPlease/L4D2-Competitive-Rework#736]
addons/sourcemod/logs/confoglcompmod
errors_20240203.log:
L 02/03/2024 - 15:51:39: [CvarSettings] [c2m1_
![image](https://github.com/SirPlease/L4D2-Competitive-Rework/assets/125074182/104b41bc-a22d-4f3a-ae27-149e4c6741ad)
highway] Could not find CVar specified (confogl_boss_unprohibit)

**Comment by ziziguaia** [comment]
![image](https://github.com/SirPlease/L4D2-Competitive-Rework/assets/125074182/ad35c772-fa0c-4045-95e8-8d56da58011c)
I haven't modified this cvar

**Comment by ziziguaia** [comment]
![Uploading image.png…]()

**Comment by SirPlease** [comment]
Hello @ziziguaia 

This is not related to those errors, you need to update your dedicated server.

**Comment by ziziguaia** [comment]
Okay, thank you, I'm too stupid to find this problem, 😂I'll go back and try to fix it with your solution
