### ISSUE TITLE
[Question] Extra slots

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#74]
You are using L4dtoolz but i don't see sv_force_unreserved "1" in the server config so how do spectators join the server when it is full ?

**Comment by SirPlease** [comment]
We use "**sm_killlobbyres**" in the matchmodes, which simply calls the left4downtown native: "**L4D_LobbyUnreserve**".
This is done in confoglcompmod's "**UnreserveLobby**" module.

**Comment by lunatixxx** [comment]
I want to avoid left4downtown, but at the same sv_force_unreserved from l4dtoolz is causing bugs on my server so i'm in a dead end.
