### ISSUE TITLE
[BUG] l4d2_magnum_incap sometimes does not return deagle to a survivor after being helped to stand up

### ISSUE THREAD

**Issue by BRU7U5** [SirPlease/L4D2-Competitive-Rework#740]
Example: https://clips.twitch.tv/RamshackleMuddyHamburgerSMOrc-XTrfmPHDnjeOcDqk

**Comment by altair-sossai** [comment]
In the video, the player hp when incapacitated starts at 299 and then returns to 300.
Could it be that the player_incapacitated event was triggered twice?
