### ISSUE TITLE
[BUG] When Jockey caps an AI survivor, AI can still resist jockey. However, the human survivor can not resist jockey.

### ISSUE THREAD

**Issue by poplpr** [SirPlease/L4D2-Competitive-Rework#747]
First, sorry for your poor reading experience due to my bad English.

**Describe the bug**
In my server, I use zonemod in this  [CompetitiveWithAnne](https://github.com/fantasylidong/CompetitiveWithAnne) repo. And when Jockey caps survivor, it causes 2 bugs.

1. If the survivor is controlled by AI, AI can still resist Jockey. However, if the survivor is controlled by me(human), I can not resist Jockey.
2. When I control the survivor capped by Jockey, I find that I can not resist, but I can press opposite direction to slow down or press same direction to speed up. The velocity in different situation:
    - Slow down: min 150, max 220. Velocity is unstable, mostly less than 200.
    - Press nothing: about 200
    - Speed up: about 220

**My Question**
I want to know if this bug is caused by [CompetitiveWithAnne](https://github.com/fantasylidong/CompetitiveWithAnne) repo or is caused by this repo? My issue about this bug has been raised in that repo for 3 weeks.

**Comment by SirPlease** [comment]
All that's done in this repo in regards to resisting the Jockey is modifying a game cvar, we don't mess with the jockey's "riding speed" or resistance in any other way.
I'm not going to look through the entire repo you just link, but seeing as there's a lot of AI plugins in there, I'd assume the issue lies there.

If not, then it's a game issue, not a repo issue.

**Comment by jensewe** [comment]
I can't really find out any code of ride speed making difference between AI and human Survivors, but it's true that you can still slow down/speed up the ride by pressing movement keys, which is outside the reach of cvar `z_jockey_control_variance`.

Simplified algorithm of ride speed calculation:
```python
player_speed, jockey_speed, time_since_ride

blend_rate = z_jockey_blend_rate.GetFloat() : 1.0
blend = sin(time_since_ride * blend_rate) : [-1, 1]
variance = z_jockey_control_variance.GetFloat() : 0.7
control_min = z_jockey_control_min.GetFloat() : 0.8

speed_ratio = clamp( control_min + blend * variance / 2, 0.0, 1.0 )

output_speed = (1-speed_ratio)*player_speed + speed_ratio*jockey_speed
```
