### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by L4d2HXF** [SirPlease/L4D2-Competitive-Rework#753]
L 03/27/2024 - 23:19:07: SourceMod error session started
L 03/27/2024 - 23:19:07: Info (map "c2m1_highway") (file "d:\steamcmd\l4d2_sv\left4dead2\addons\sourcemod\logs\errors_20240327.log")
L 03/27/2024 - 23:19:07: [chajian\l4d2_ladder_rambos.smx] [cs_ladders] Failed to validate patch "CTerrorPlayer::OnLadderMount__WeaponHolster_patch"

Windows signature crashes
![300E117F09E24355B707C7E908C51CE3](https://github.com/SirPlease/L4D2-Competitive-Rework/assets/91784242/aba544ec-6b86-4ecb-824a-b10e9350749e)

**Comment by NanakaFathry** [comment]
移除掉 l4d2_ladder_rambos.smx 插件试试

**Comment by A1mDev** [comment]
windows server?

**Comment by jensewe** [comment]
https://github.com/Target5150/MoYu_Server_Stupid_Plugins/commit/0e8a31b5c3e1b2600da7d9e081139519107f38e9

See if this one helps.
