### ISSUE TITLE
[SUG] Reduce an unnecessary loop in frozen_tank_fix

### ISSUE THREAD

**Issue by blueblur0730** [SirPlease/L4D2-Competitive-Rework#777]
The original code:
```Sourcepawn
public Event_PlayerIncap(Handle:event, const String:name[], bool:dontBroadcast)
{
	new client = GetClientOfUserId(GetEventInt(event, "userid"));
	if (client > 0 && IsPlayerTank(client))
	{
		CreateTimer(1.0, KillTank_tCallback);
	}
}

public Action:KillTank_tCallback(Handle:timer)
{
	for (new i = 1; i <= MaxClients; i++)
	{
		if (IsPlayerTank(i) && IsIncapitated(i))
		{
			ForcePlayerSuicide(i);
		}
	}
}
```
Noted that in the timer callback we use a loop to find the tank client, but actually we can just pass the client index on the `CreateTimer` function, like `CreateTimer(1.0, KillTank_tCallback, client);`.
The edited version should be:
```Sourcepawn
public void Event_PlayerIncap(Event event, char[] name, bool dontBroadcast)
{
	int client = GetClientOfUserId(event.GetInt("userid"));
	if (client > 0 && IsPlayerTank(client))
	{
		CreateTimer(1.0, KillTank_tCallback, client);
	}
}

Action KillTank_tCallback(Handle timer, int client)
{
	if (IsPlayerTank(client) && IsIncapitated(client))
	{
		ForcePlayerSuicide(client);
	}

	return Plugin_Handled;
}
```
This method should reduce an unnecessary loop.

**Comment by A1mDev** [comment]
The client's index changes during the game, and how will you track when control of the tank is transferred? It is for this case that such code is needed, since after the transfer of control this bug occurs.

**Comment by blueblur0730** [comment]
> The client's index changes during the game, and how will you track when control of the tank is transferred? It is for this case that such code is needed, since after the transfer of control this bug occurs.

Didn't aware that, apology on this mistake. I think I got confused with userid and client index
