### ISSUE TITLE
[REQ] No ghost cheat source file

### ISSUE THREAD

**Issue by lunatixxx** [SirPlease/L4D2-Competitive-Rework#78]
Is it possible to have .sp file ? And is it possible to use it against spectators too ?

**Comment by SirPlease** [comment]
Good that you mention this plugin, I need to run a few more tests and I'll clean up the code a bit.
While I'm at it, I'll add a convar for specs ( although I'm not quite sure why you'd do that 😄 ).

I'll label this as Soon for now.

**Comment by lunatixxx** [comment]
Spectators could give positions of ghost infecteds by text or vocal. Also i didn't find any cvar to disable the glow of the ghosts when you are in free roam camera, i only found one who works their are on the view of survivors "spec_filter survivor".
