### ISSUE TITLE
It cause crash on my server

### ISSUE THREAD

**Issue by BlacK201** [SirPlease/L4D2-Competitive-Rework#79]
Here are server logs.
```
Client "xxxxxxxx" connected (xx.xx.xx.x:9613).
String Table dictionary for downloadables should be rebuilt, only found 38 of 44 strings in dictionary
String Table dictionary for soundprecache should be rebuilt, only found 9751 of 16426 strings in dictionary
String Table dictionary for Scenes should be rebuilt, only found 6770 of 13181 strings in dictionary
CreateFragmentsFromFile: 'downloads/6039a277.dat' doesn't exist.
CreateFragmentsFromFile: 'downloads/6039a277.dat' doesn't exist.
CreateFragmentsFromFile: 'downloads/6039a277.dat' doesn't exist.
CreateFragmentsFromFile: 'downloads/6039a277.dat' doesn't exist.
SURVIVORBOT (Rochelle, [2698.811523 5809.931641 -767.968750]) will not help incap (Coach,[3036.417236 6000.136719 -763.128540]): UNREACHABLE via NAV
Wrote minidump to: /home/steam/l4d2/left4dead2/addons/sourcemod/data/dumps/e9b8b286-be09-4a7e-e9b37c8b-d415621e.dmp   
/home/steam/l4d2/srcds_run: line 312: 20369 Segmentation fault      $HL_CMD
Add "-debug" to the /home/steam/l4d2/srcds_run command line to generate a debug.log to help with solving this problem
Thu Feb 27 13:18:22 CST 2020: Server restart in 10 seconds
```
And here is Accelerator crash reporting link.
[https://crash.limetech.org/km73ep6jfjzq](https://crash.limetech.org/km73ep6jfjzq)

**Comment by SirPlease** [comment]
What setup are you running? (Linux Distribution & Sourcemod Version)
Also, are you running this on a "clean" server without anything else installed?

**Comment by BlacK201** [comment]
@SirPlease Yes I'm sure I running this on a clean server.
```
$ cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core) 
```
```
sm version
 SourceMod Version Information:
    SourceMod Version: 1.9.0.6281
    SourcePawn Engine: 1.9.0.6281, jit-x86 (build 1.9.0.6281)
    SourcePawn API: v1 = 4, v2 = 12
    Compiled on: May 14 2019 16:03:05
    Built from: https://github.com/alliedmodders/sourcemod/commit/c5efe48
    Build ID: 6281:c5efe48
    http://www.sourcemod.net/
```
```
meta version
 Metamod:Source Version Information
    Metamod:Source version 1.11.0-dev+1127
    Plugin interface version: 16:14
    SourceHook version: 5:5
    Loaded As: Valve Server Plugin
    Compiled on: Jul 31 2018 21:28:22
    Built from: https://github.com/alliedmodders/metamod-source/commit/de33074
    Build ID: 1127:de33074
    http://www.metamodsource.net/
```

**Comment by SirPlease** [comment]
That's odd, does it consistently happen or is this the first time in <amount of time> this has happened?
I'm assuming it's right after setting up the server, as it only shows this specific error twice on accelerator and it's by 2 different owners.

As for your install, everything seems in order, the only thing I run differently is Ubuntu but CentOS should be fine.

**Comment by BlacK201** [comment]
Most of the time it happens when it change levels or maps, sometimes it happens when server is empty and I'm trying to connect in.
And I found [a post](https://forums.alliedmods.net/showthread.php?t=294542).Is it will work for my server?
Thanks for your reply and sorry for my sucks English.

**Comment by SirPlease** [comment]
I doubt it's related to Steamworks itself, rather the way your distribution handles it.
When running this install, you run the additional steamworks extension, you could try not loading it to see if it continues crashing.

If it does, you can try setting the disable cvar as posted in that thread, if it works then great, but I wouldn't call it a solution.

**Comment by BlacK201** [comment]
OK I will try setting the disable cvar and focus on it.Thanks!

**Comment by keyCat** [comment]
@BlacK201 

Hey.
When I was running my servers on CentOS 7, setting cvars as post states
```
sm_cvar steamworks_immediate_upload 0
sm_cvar steamworks_stats_disable 1
```
definitely helped to get rid of these type of crashes. Though, on CentOS 7 I always experienced some type of crashes that didn't happen neither on Ubuntu or Debian. This is all empirical, though, so take it as you will :)

**Comment by SirPlease** [comment]
I'll close this for now, thanks for contributing @keyCat 👍
