### ISSUE TITLE
[BUG] c1m3_mall witch spawns on default route that is blocked

### ISSUE THREAD

**Issue by nikita1824** [SirPlease/L4D2-Competitive-Rework#790]
Hello, correct me if Im wrong but, as I understand, [this](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/9ce828029c3b6f121d47727021bd8d6e55ceddce/cfg/stripper/acemodrv/maps/c1m3_mall.cfg#L31-L47) forces survivors to move on longer path that is not expected by ai-director. It causes witches to spawn on the wrong route, this is not a problem for zonemod (for obvious reasons) but the same stripper-config is used for Acemod Revamped.
I checked legacy configs and found out how it was solved before. [This](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/9ce828029c3b6f121d47727021bd8d6e55ceddce/cfg/stripper/pmelite/maps/c1m3_mall.cfg#L472-L491) should solve the problem.

**Comment by SirPlease** [comment]
Thank you for reporting this issue and providing a fix for it while you're at it! 😄 
I assumed the witch ban range accounted for this particular issue, but forcing the witch to spawn at a valid range would indeed result into the witch spawning in the blocked off room.
I'll get around to it shortly and push the fix in configs affected.

**Comment by nikita1824** [comment]
Hello again,
We tested solution for this problem and it is better (for now) to add [this](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/9ce828029c3b6f121d47727021bd8d6e55ceddce/cfg/stripper/pmelite/maps/c1m3_mall.cfg#L472-L491) changes but remove [this](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/9ce828029c3b6f121d47727021bd8d6e55ceddce/cfg/stripper/pmelite/maps/c1m3_mall.cfg#L478-L483) part to avoid creating several escalators.
[Here](https://github.com/nikita1824/c1m3_mall.cfg/blob/main/c1m3_mall.cfg) is the example of how we resolved this problem.
