### ISSUE TITLE
[BUG] M2 Working on 1v1 ZoneHunters

### ISSUE THREAD

**Issue by V3nilla** [SirPlease/L4D2-Competitive-Rework#792]
**Describe the bug**
So, M2's are now working against hunters.

**To Reproduce**
Just load 1v1 ZoneHunters config on server, and try to M2 flying hunter

**Server Operating System (if applicable):**
Linux/Windows

**Comment by SirPlease** [comment]
I'm unable to reproduce the issue on a fresh repo install.
Also, considering the plugin is loaded in Zonemod and other configs as well, there'd be far more outcry if it was broken 😅

**Comment by V3nilla** [comment]
> I'm unable to reproduce the issue on a fresh repo install. Also, considering the plugin is loaded in Zonemod and other configs as well, there'd be far more outcry if it was broken 😅

Maybe it's an isolated case, I just played on the Russian T1 Server with this config yesterday and found this problem, they said they had already fixed it and the problem was on the side of the repo itself

**Comment by SirPlease** [comment]
If they fixed it, perhaps you could ask them to report what the issue was so it could be looked into?

**Comment by V3nilla** [comment]
> If they fixed it, perhaps you could ask them to report what the issue was so it could be looked into?

I found out the reasons more precisely - 2 versions of the plugin were loaded that are existing on the server, and the wrong one was loaded at all, they thought that the problem was in the repository. I'm closing the issue
