### ISSUE TITLE
[BUG] Multiple escalators on c1m3_mall

### ISSUE THREAD

**Issue by nikita1824** [SirPlease/L4D2-Competitive-Rework#796]
Hello again,
We tested solution for [this](https://github.com/SirPlease/L4D2-Competitive-Rework/issues/790) problem and it is better (for now) to add [this](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/9ce828029c3b6f121d47727021bd8d6e55ceddce/cfg/stripper/pmelite/maps/c1m3_mall.cfg#L472-L491) changes but remove [this](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/9ce828029c3b6f121d47727021bd8d6e55ceddce/cfg/stripper/pmelite/maps/c1m3_mall.cfg#L478-L483) part to avoid creating several escalators.
Here is the example of how we resolved this problem:
```
; --- Force survivors to always take the lower path leading to the event
modify:
{
    match:
    {
        "hammerid" "196210"
    }
    delete:
    {
        "OnTrigger" "compare_minifinaleCompare0.5-1"
        "OnTrigger" "director_queryHowAngry0-1"
    }
    insert:
    {
        "OnTrigger" "relay_hallway_close,Trigger,,0,-1"
    }
}
; make logic_auto pick one path
modify:
{
    match:
    {
        "hammerid" "1310374"
    }
    insert:
    {
        ; force lower route
        "OnMapSpawn" "relay_hallway_closeTrigger0-1"
    }
}
```

I opened another issue because I couldn't reopen the old one and I'm not sure how notifications work on GitHub (Does repository maintainer see notifications about new comments in closed threads?).

**Comment by SirPlease** [comment]
Thanks for being on top of this, I clearly was very sloppy with this 👎 
I did get a notification, but I've been a bit busy over the past few days.
