### ISSUE TITLE
Show the player's contry and quit reason

### ISSUE THREAD

**Issue by zgcfasia** [SirPlease/L4D2-Competitive-Rework#798]
i saw some zonemod server can show player'contry when they joined.  and quit reason . 
i think this plugin is good. so where is？ i want use it. Is this function in your combination package? i cant find it.
please help. thank u！

**Comment by SirPlease** [comment]
It's not a part of the repo, I'm sure there's plugins on Alliedmodders that provide the functionality you're looking for.
For example: [Connect Announce](https://forums.alliedmods.net/showthread.php?t=77306)

From what I recall the player disconnect message isn't very reliable, but I could be wrong 🤷‍♂️
