### ISSUE TITLE
how allow bots to eat pills

### ISSUE THREAD

**Issue by zgcfasia** [SirPlease/L4D2-Competitive-Rework#804]
the bots dont eat pills when they injured
i think i can delete a smx to solve it
please help 
thank u bro 
vy vy vy thank u

**Comment by SirPlease** [comment]
Don't load [this](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/addons/sourcemod/scripting/l4d2_block_bot_pills.sp) plugin
