### ISSUE TITLE
[Question] c10m4_mainstreet horde event 

### ISSUE THREAD

**Issue by jumpymeows1** [SirPlease/L4D2-Competitive-Rework#814]
Hello, 
In the map c10m4_mainstreet, after activating the forklift - should there be a horde?

The config: Zonemod
The cfg files are from this github.

**Comment by SirPlease** [comment]
Yes, there is an endless horde after activating the forklift.

**Comment by jumpymeows1** [comment]
it doesn't get triggered on my server, could you advice where to check?

**Comment by blueblur0730** [comment]
> it doesn't get triggered on my server, could you advice where to check?
> the stripper file & vscript file are installed.
> 
> Horde gets triggered in vanilla (no script)
> 
> however,after I load the stripper file in vanilla - the horde doesn't get triggered.

https://github.com/SirPlease/L4D2-Competitive-Rework/blob/master/cfg%2Fstripper%2Fzonemod%2Fmaps%2Fc10m4_mainstreet.cfg#L17-L20
stripper replaced the vanilla horde event with the vscript file `c10m4_OnSlaught_rework.nut`
if you just have the stripper worked the horde won't trigger.

**Comment by jumpymeows1** [comment]
something wrong with my server binaries. apologies

**Comment by jumpymeows1** [comment]
something wrong with my server binaries. apologies
