### ISSUE TITLE
[BUG] Left4Dhooks 1.151 -> 1.152  C6M2 To next map reset score

### ISSUE THREAD

**Issue by cH1yoi** [SirPlease/L4D2-Competitive-Rework#818]
https://github.com/SirPlease/L4D2-Competitive-Rework/commit/a163425f76738d8c0b2e3b721d367d3f9acc49db

After testing, C6M2 switches to the next map and resets the score when the survivor is complete

please verify

**Comment by SirPlease** [comment]
Appreciate the report, I've reverted the update.
the latest version (v1.153) also has the issue.
