### ISSUE TITLE
I had writed some Matchmodes and plugins, I want contribute them to repo

### ISSUE THREAD

**Issue by csxinsheng1** [SirPlease/L4D2-Competitive-Rework#819]
Dear Competitive Rework dev team.
I have played lots of year spending on L4D2 versus gameplay,and CS, I had designed a few Matchmodes with special plugins.
The important part of this I think is gameplay design, most plugins based on Competitive Rework.
I think I should share with people to let all players have more choice to versus modes.
Contribute to this repository is the first thing I thought since my Matchmodes&plugins based on repo.
So how can I contribute to the repository if I can, or i need contribute somewhere else than here?
How can i contact dev team if I can?
Thanks.

**Comment by fantasylidong** [comment]
You just need create a fork and make you change, then pull your fork to the repo. 
Sir will choose merge or not.
PS: Every plugin need source code.

**Comment by csxinsheng1** [comment]
> You just need create a fork and make you change, then pull your fork to the repo. Sir will choose merge or not. PS: Every plugin need source code.

Thanks.
I will try that.

**Comment by SirPlease** [comment]
If you have a suggestion for a plugin to be used for matchmodes (global or existing config specific) those are typically discussed in the [SirPlease Discord](https://discord.com/invite/tcNw4akhFf)

For configs, I don't really have a problem with accepting PRs for new matchmodes as long as they follow the structure of other configs (EQ, Acemod, Zonemod) in terms of setting convars and loading plugins.

**Comment by csxinsheng1** [comment]
> If you have a suggestion for a plugin to be used for matchmodes (global or existing config specific) those are typically discussed in the [SirPlease Discord](https://discord.com/invite/tcNw4akhFf)
> 
> For configs, I don't really have a problem with accepting PRs for new matchmodes as long as they follow the structure of other configs (EQ, Acemod, Zonemod) in terms of setting convars and loading plugins.

@SirPlease 
Thanks, I will join discord and try to contribute.
