### ISSUE TITLE
l4d2_hybrid_scoremod_zone as library name broke spechud functional

### ISSUE THREAD

**Issue by Electr0** [SirPlease/L4D2-Competitive-Rework#82]
just for known https://github.com/SirPlease/L4D2-Competitive-Rework/blob/a6f4e7982b5b0df77524c3860e83c813cecf8e51/addons/sourcemod/scripting/l4d2_hybrid_scoremod.sp#L70

plugin spechud.sp using check:

public OnAllPluginsLoaded()
{
	hybridScoringAvailable = LibraryExists("l4d2_hybrid_scoremod");
}
public OnLibraryRemoved(const String:name[])
{
	if (StrEqual(name, "l4d2_hybrid_scoremod", true))
	{
		hybridScoringAvailable = false;
	}
}
public OnLibraryAdded(const String:name[])
{
	if (StrEqual(name, "l4d2_hybrid_scoremod", true))
	{
		hybridScoringAvailable = true;
	}
}

and why in this case using l4d2_hybrid_scoremod_zone as library name?

i am check zonemod and eq compiled spechud in both cases they check older library name without "zone" tag, because of that just remove this (_zone) from library name of a l4d2_hybrid_scoremod

**Comment by SirPlease** [comment]
Good call, no clue why I left _zone in there considering I've already modified the l4d2_hybrid_scoremod_zone to use the default library "l4d2_hybrid_scoremod". (Which of course is the one used in Nextmod and Zonemod)
