### ISSUE TITLE
[BUG] ZoneHunters weapon limit doesn't make any sense

### ISSUE THREAD

**Issue by nikita1824** [SirPlease/L4D2-Competitive-Rework#822]
Hello, we recently tested some cases in ZoneHunters config and it seems like there is problem for [2v2](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/b6696f4a32400093ddaf95c37ec8536672c5b61d/cfg/cfgogl/zh2v2/zh2v2.cfg#L31), [3v3](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/b6696f4a32400093ddaf95c37ec8536672c5b61d/cfg/cfgogl/zm3v3/zm3v3.cfg#L32) and [4v4](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/b6696f4a32400093ddaf95c37ec8536672c5b61d/cfg/cfgogl/zonehunters/zonehunters.cfg#L39) modes.
There is option to choose Deagle but it is limited to 1.

**Comment by SirPlease** [comment]
Ah yes, that sounds like a typical mistake I'd make.
I'll sort it out during the weekend along with a change to the weapon system as it's a bit wonky in general. 😅
