### ISSUE TITLE
Unable to open doors in any map. (Safe room doors, normal doors etc)

### ISSUE THREAD

**Issue by SpiritBob** [SirPlease/L4D2-Competitive-Rework#83]
Uhh, I decided to update everything I had with your setup, and the aftermath was the above.

Any idea what might be causing it? I made sure to clean my whole addons folder (after which I dumped your stuff), with the exception of a few configuration files.

**Comment by SpiritBob** [comment]
So apparently the issue was with tickratefixes/rates and tick_door_speed?

For some reason if all my network configuration (along with tick_door_speed) is in a separate config file called confogl_rates, the door glitch appears, but if I move it all into server.cfg, it worked.

So weird.

**Comment by SpiritBob** [comment]
@SirPlease I'm also currently running on 30-tick due to having a very poor network. Should I change tick_door_speed to 1 instead of it staying on 1.3? Or 1.3 is some magic number you ended up defaulting for all configurations. (I've read somewhere that 2.0 is for 60 tick and so on)

**Comment by SpiritBob** [comment]
Okay so the problem just re-appeared. It's really weird. Sometimes all doors work but safe room door doesn't (not the one in the starting safe room)

It happens randomly, and I feel it's connected with the new TickRateFixes.

**Comment by SirPlease** [comment]
When running on 30 tick, don't load the plugin and don't load the tickrate enabler or you'll run into issues like these.

**Comment by SpiritBob** [comment]
Yeah I've reverted to 100 tick, but the issue happened there. I re-downloaded the tickrate fixer from this post, and so far everything is in order. Let me know if the 2 have any differences. https://forums.alliedmods.net/showpost.php?p=2682855&postcount=104

**Comment by SirPlease** [comment]
Using **sm_cvar tick_door_speed 1.3** (as provided with the server.cfg in this repo works without issues with the TickrateFixes provided in this repo as long as you don't have the convar set to different values in multiple files.
The values provided in the thread you linked will make doors extremely fast in comparison to vanilla.

**Comment by SpiritBob** [comment]
Are you using Ubuntu Server 18.06 for your linux servers? For some reason I'm experiencing random lag spikes even when I removed sourcemod + metamod completely, yet my computer is more than able to run 10 servers if necessary.

**Comment by SirPlease** [comment]
Likely to be related to consistency checks being done on clients, if you have a big whitelist.txt file and you're not running **sv_consistency_fix.smx** then it'll force a consistency check on clients every 3 minutes.

**Comment by SpiritBob** [comment]
Every plugin inside the fixes folder is being loaded, so that's running as well.

I'm also running `sv_pure 2`, to make sure everything is as it should be.

**Comment by SirPlease** [comment]
Unrelated to the install, so I'll be closing this now.
As for OS, I've never gone outside of Debian and Ubuntu regarding the installs because they worked, as simple as that. Never going outside of Ubuntu for SRCDS stuff again 👍
