### ISSUE TITLE
[BUG] Plugins' incompatibility with SM 1.11

### ISSUE THREAD

**Issue by StarterX4** [SirPlease/L4D2-Competitive-Rework#838]
**Describe the bug**
As some plugins don't work with 1.11 without recompilation now, I think the support **_for 1.11 and up_** (in readme) should be corrected to just 1.12, or it should be noted that some plugins (or better all of them) should be recompiled under 1.11.

```
L 11/10/2024 - 19:33:31: [SM] Failed to load plugin "fixes/l4d_fix_stagger_dir.smx": Unable to load plugin (unsupported feature set; code is too new).
L 11/10/2024 - 19:33:31: [SM] Failed to load plugin "fixes/l4d2_charge_target_fix.smx": Unable to load plugin (unsupported feature set; code is too new).
L 11/10/2024 - 19:33:31: [SM] Failed to load plugin "fixes/l4d_fix_common_shove.smx": Unable to load plugin (unsupported feature set; code is too new).
L 11/10/2024 - 19:33:31: [SM] Failed to load plugin "fixes/l4d_fix_rotated_physblocker.smx": Unable to load plugin (unsupported feature set; code is too new).
L 11/10/2024 - 19:33:31: [SM] Failed to load plugin "fixes/l4d_tongue_bend_fix.smx": Unable to load plugin (unsupported feature set; code is too new).
```
There were like two more plugins since this repo switched to 1.12, but just recompiled and forgot about them.
Though since the list is growing, I think we should point it out. Compatibility with 1.11 gets lost.

**To Reproduce**
1. Use this repo with SourceMod 1.11 as for your testing server
2. Start your server
3. Check the errors in console or in error logs

**Comment by apples1949** [comment]
Please be patient, or you can commits changes to fix the bug.

**Comment by SirPlease** [comment]
Appreciate the report, I'm not quite giving up on SM 1.11 just yet so I'll keep it as is.
I'll do an entire re-compile of all plugins, run a few tests and then upload em all. 🫤

**Comment by A1mDev** [comment]
I think it's better to remove the sourcemod and metamod from this repository as unnecessary :D

**Comment by A1mDev** [comment]
let everyone download the sourcemod they want or metamod
