### ISSUE TITLE
[BUG] Too much spectating causes inability to respawn tanks

### ISSUE THREAD

**Issue by cH1yoi** [SirPlease/L4D2-Competitive-Rework#848]
**Describe the bug**
After a brief test, too many spectator caused the tank to fail to spawn.
Presumably the total slots are greater than 16
Functions Involved (Tank Spawn Post Forward)
Specific error (Invalid Client Index -1)
Scenario(Spawning Tank)
After verification, lower versions of left4dhook do not have this issue
![a6bb631024da86d681cad5880fde2cc4](https://github.com/user-attachments/assets/d7352522-a288-49c2-9823-ab7432a56f24)
Please verify

`void BS_OnTankSpawnPost_Forward(int iTankClient)
{
	if (!BS_bEnabled || !IsPluginEnabled()) {
		return;
	}

	// Don't touch tanks on finale events
	if (BS_bFinaleStarted) {
		return;
	}

	// Don't track tank spawns on c5m5 or tank can spawn behind other team.
	if (strcmp(BS_sMap, "c5m5_bridge") == 0) {
		return;
	}

	if (GetMapValueInt("tank_z_fix")) {
		FixZDistance(iTankClient); // fix stuck tank spawns, ex c1m1
	}

	// If we reach MAX_TANKS, we don't have any room to store their locations
	if (BS_iTankCount[view_as<int>(!BS_bIsFirstRound)] >= MAX_TANKS) {
		Debug_LogError(BS_MODULE_NAME, "Failed to save a large number of tanks to the array. Count: %d, Max: %d", \
											BS_iTankCount[view_as<int>(!BS_bIsFirstRound)], MAX_TANKS);
		return;
	}

	if (BS_bDebugEnabled || IsDebugEnabled()) {
		LogMessage("[%s] Tracking this tank spawn. Currently, %d tanks", BS_MODULE_NAME, BS_iTankCount[view_as<int>(!BS_bIsFirstRound)]);
	}

	if (BS_bIsFirstRound) {
		GetClientAbsOrigin(iTankClient, BS_fTankSpawn[BS_iTankCount[0]]);
		if (BS_bDebugEnabled || IsDebugEnabled()) {
			LogMessage("[%s] Saving tank at %f %f %f", \
							BS_MODULE_NAME, BS_fTankSpawn[BS_iTankCount[0]][0], BS_fTankSpawn[BS_iTankCount[0]][1], BS_fTankSpawn[BS_iTankCount[0]][2]);
		}

		BS_iTankCount[0]++;
	} else if (BS_iTankCount[0] > BS_iTankCount[1]) {
		TeleportEntity(iTankClient, BS_fTankSpawn[BS_iTankCount[1]], NULL_VECTOR, NULL_VECTOR);

		if (BS_bDebugEnabled || IsDebugEnabled()) {
			LogMessage("[%s] Teleporting tank to tank at %f %f %f", \
							BS_MODULE_NAME, BS_fTankSpawn[BS_iTankCount[1]][0], BS_fTankSpawn[BS_iTankCount[1]][1], BS_fTankSpawn[BS_iTankCount[1]][2]);
		}

		BS_iTankCount[1]++;
	} else if (BS_bDebugEnabled || IsDebugEnabled()) {
		LogMessage("[%s] Not first round and not acceptable tank", BS_MODULE_NAME);
		LogMessage("[%s] IsFirstRound: %d  R1Count: %d R2Count: %d", BS_MODULE_NAME, BS_bIsFirstRound, BS_iTankCount[0], BS_iTankCount[1]);
	}
}
`

**Server Operating System (if applicable):**
 - Linux

**Additional context**
L 11/22/2024 - 21:39:16: SourceMod error session started
L 11/22/2024 - 21:39:16: Info (map "c5m4_quarter") (file "/home/hana/versus/left4dead2/addons/sourcemod/logs/errors_20241122.log")
L 11/22/2024 - 21:39:16: [SM] Exception reported: Client index -1 is invalid
L 11/22/2024 - 21:39:16: [SM] Blaming: optional/l4d2_tank_announce.smx
L 11/22/2024 - 21:39:16: [SM] Call stack trace:
L 11/22/2024 - 21:39:16: [SM]   [0] IsClientInGame
L 11/22/2024 - 21:39:16: [SM]   [1] Line 92, .\l4d2_tank_announce.sp::IsTank
L 11/22/2024 - 21:39:16: [SM]   [2] Line 43, .\l4d2_tank_announce.sp::L4D_OnSpawnTank_Post
L 11/22/2024 - 21:39:16: [SM]   [4] Call_Finish
L 11/22/2024 - 21:39:16: [SM]   [5] Line 1215, l4dd\l4dd_forwards.sp::Spawn_TankWitch_Post
L 11/22/2024 - 21:39:16: [SM]   [6] Line 1174, l4dd\l4dd_forwards.sp::DTR_ZombieManager_SpawnTank_Post
L 11/22/2024 - 21:39:16: [SM] Exception reported: Client index -1 is invalid
L 11/22/2024 - 21:39:16: [SM] Blaming: confoglcompmod.smx
L 11/22/2024 - 21:39:16: [SM] Call stack trace:
L 11/22/2024 - 21:39:16: [SM]   [0] GetClientAbsOrigin
L 11/22/2024 - 21:39:16: [SM]   [1] Line 132, confoglcompmod\BossSpawning.sp::BS_OnTankSpawnPost_Forward
L 11/22/2024 - 21:39:16: [SM]   [2] Line 433, c:\Users\Sir\SourcePawn11\confoglcompmod.sp::L4D_OnSpawnTank_Post
L 11/22/2024 - 21:39:16: [SM]   [4] Call_Finish
L 11/22/2024 - 21:39:16: [SM]   [5] Line 1215, l4dd\l4dd_forwards.sp::Spawn_TankWitch_Post
L 11/22/2024 - 21:39:16: [SM]   [6] Line 1174, l4dd\l4dd_forwards.sp::DTR_ZombieManager_SpawnTank_Post
L 11/22/2024 - 21:39:18: [SM] Exception reported: Client index -1 is invalid
L 11/22/2024 - 21:39:18: [SM] Blaming: optional/l4d2_tank_announce.smx
L 11/22/2024 - 21:39:18: [SM] Call stack trace:
L 11/22/2024 - 21:39:18: [SM]   [0] IsClientInGame
L 11/22/2024 - 21:39:18: [SM]   [1] Line 92, .\l4d2_tank_announce.sp::IsTank
L 11/22/2024 - 21:39:18: [SM]   [2] Line 43, .\l4d2_tank_announce.sp::L4D_OnSpawnTank_Post
L 11/22/2024 - 21:39:18: [SM]   [4] Call_Finish
L 11/22/2024 - 21:39:18: [SM]   [5] Line 1215, l4dd\l4dd_forwards.sp::Spawn_TankWitch_Post
L 11/22/2024 - 21:39:18: [SM]   [6] Line 1174, l4dd\l4dd_forwards.sp::DTR_ZombieManager_SpawnTank_Post
L 11/22/2024 - 21:39:18: [SM] Exception reported: Client index -1 is invalid
L 11/22/2024 - 21:39:18: [SM] Blaming: confoglcompmod.smx
L 11/22/2024 - 21:39:18: [SM] Call stack trace:
L 11/22/2024 - 21:39:18: [SM]   [0] GetClientAbsOrigin
L 11/22/2024 - 21:39:18: [SM]   [1] Line 132, confoglcompmod\BossSpawning.sp::BS_OnTankSpawnPost_Forward
L 11/22/2024 - 21:39:18: [SM]   [2] Line 433, c:\Users\Sir\SourcePawn11\confoglcompmod.sp::L4D_OnSpawnTank_Post
L 11/22/2024 - 21:39:18: [SM]   [4] Call_Finish
L 11/22/2024 - 21:39:18: [SM]   [5] Line 1215, l4dd\l4dd_forwards.sp::Spawn_TankWitch_Post
L 11/22/2024 - 21:39:18: [SM]   [6] Line 1174, l4dd\l4dd_forwards.sp::DTR_ZombieManager_SpawnTank_Post
L 11/22/2024 - 21:39:22: [SM] Exception reported: Client index -1 is invalid
L 11/22/2024 - 21:39:22: [SM] Blaming: optional/l4d2_tank_announce.smx
L 11/22/2024 - 21:39:22: [SM] Call stack trace:
L 11/22/2024 - 21:39:22: [SM]   [0] IsClientInGame
L 11/22/2024 - 21:39:22: [SM]   [1] Line 92, .\l4d2_tank_announce.sp::IsTank
L 11/22/2024 - 21:39:22: [SM]   [2] Line 43, .\l4d2_tank_announce.sp::L4D_OnSpawnTank_Post
L 11/22/2024 - 21:39:22: [SM]   [4] Call_Finish
L 11/22/2024 - 21:39:22: [SM]   [5] Line 1215, l4dd\l4dd_forwards.sp::Spawn_TankWitch_Post
L 11/22/2024 - 21:39:22: [SM]   [6] Line 1174, l4dd\l4dd_forwards.sp::DTR_ZombieManager_SpawnTank_Post
L 11/22/2024 - 21:39:22: [SM] Exception reported: Client index -1 is invalid
L 11/22/2024 - 21:39:22: [SM] Blaming: confoglcompmod.smx
L 11/22/2024 - 21:39:22: [SM] Call stack trace:
L 11/22/2024 - 21:39:22: [SM]   [0] GetClientAbsOrigin
L 11/22/2024 - 21:39:22: [SM]   [1] Line 132, confoglcompmod\BossSpawning.sp::BS_OnTankSpawnPost_Forward
L 11/22/2024 - 21:39:22: [SM]   [2] Line 433, c:\Users\Sir\SourcePawn11\confoglcompmod.sp::L4D_OnSpawnTank_Post
L 11/22/2024 - 21:39:22: [SM]   [4] Call_Finish
L 11/22/2024 - 21:39:22: [SM]   [5] Line 1215, l4dd\l4dd_forwards.sp::Spawn_TankWitch_Post
L 11/22/2024 - 21:39:22: [SM]   [6] Line 1174, l4dd\l4dd_forwards.sp::DTR_ZombieManager_SpawnTank_Post
L 11/22/2024 - 21:39:34: [SM] Exception reported: Client index -1 is invalid
L 11/22/2024 - 21:39:34: [SM] Blaming: optional/l4d2_tank_announce.smx
L 11/22/2024 - 21:39:34: [SM] Call stack trace:
L 11/22/2024 - 21:39:34: [SM]   [0] IsClientInGame
L 11/22/2024 - 21:39:34: [SM]   [1] Line 92, .\l4d2_tank_announce.sp::IsTank
L 11/22/2024 - 21:39:34: [SM]   [2] Line 43, .\l4d2_tank_announce.sp::L4D_OnSpawnTank_Post
L 11/22/2024 - 21:39:34: [SM]   [4] Call_Finish
L 11/22/2024 - 21:39:34: [SM]   [5] Line 1215, l4dd\l4dd_forwards.sp::Spawn_TankWitch_Post
L 11/22/2024 - 21:39:34: [SM]   [6] Line 1174, l4dd\l4dd_forwards.sp::DTR_ZombieManager_SpawnTank_Post
L 11/22/2024 - 21:39:34: [SM] Exception reported: Client index -1 is invalid
L 11/22/2024 - 21:39:34: [SM] Blaming: confoglcompmod.smx
L 11/22/2024 - 21:39:34: [SM] Call stack trace:
L 11/22/2024 - 21:39:34: [SM]   [0] GetClientAbsOrigin
L 11/22/2024 - 21:39:34: [SM]   [1] Line 132, confoglcompmod\BossSpawning.sp::BS_OnTankSpawnPost_Forward
L 11/22/2024 - 21:39:34: [SM]   [2] Line 433, c:\Users\Sir\SourcePawn11\confoglcompmod.sp::L4D_OnSpawnTank_Post
L 11/22/2024 - 21:39:34: [SM]   [4] Call_Finish
L 11/22/2024 - 21:39:34: [SM]   [5] Line 1215, l4dd\l4dd_forwards.sp::Spawn_TankWitch_Post
L 11/22/2024 - 21:39:34: [SM]   [6] Line 1174, l4dd\l4dd_forwards.sp::DTR_ZombieManager_SpawnTank_Post
L 11/22/2024 - 21:39:38: [SM] Exception reported: Client index -1 is invalid
L 11/22/2024 - 21:39:38: [SM] Blaming: optional/l4d2_tank_announce.smx
L 11/22/2024 - 21:39:38: [SM] Call stack trace:
L 11/22/2024 - 21:39:38: [SM]   [0] IsClientInGame
L 11/22/2024 - 21:39:38: [SM]   [1] Line 92, .\l4d2_tank_announce.sp::IsTank
L 11/22/2024 - 21:39:38: [SM]   [2] Line 43, .\l4d2_tank_announce.sp::L4D_OnSpawnTank_Post
L 11/22/2024 - 21:39:38: [SM]   [4] Call_Finish
L 11/22/2024 - 21:39:38: [SM]   [5] Line 1215, l4dd\l4dd_forwards.sp::Spawn_TankWitch_Post
L 11/22/2024 - 21:39:38: [SM]   [6] Line 1174, l4dd\l4dd_forwards.sp::DTR_ZombieManager_SpawnTank_Post
L 11/22/2024 - 21:39:38: [SM] Exception reported: Client index -1 is invalid
L 11/22/2024 - 21:39:38: [SM] Blaming: confoglcompmod.smx
L 11/22/2024 - 21:39:38: [SM] Call stack trace:
L 11/22/2024 - 21:39:38: [SM]   [0] GetClientAbsOrigin
L 11/22/2024 - 21:39:38: [SM]   [1] Line 132, confoglcompmod\BossSpawning.sp::BS_OnTankSpawnPost_Forward
L 11/22/2024 - 21:39:38: [SM]   [2] Line 433, c:\Users\Sir\SourcePawn11\confoglcompmod.sp::L4D_OnSpawnTank_Post
L 11/22/2024 - 21:39:38: [SM]   [4] Call_Finish
L 11/22/2024 - 21:39:38: [SM]   [5] Line 1215, l4dd\l4dd_forwards.sp::Spawn_TankWitch_Post
L 11/22/2024 - 21:39:38: [SM]   [6] Line 1174, l4dd\l4dd_forwards.sp::DTR_ZombieManager_SpawnTank_Post
L 11/22/2024 - 21:39:43: [SM] Exception reported: Client index -1 is invalid
L 11/22/2024 - 21:39:43: [SM] Blaming: optional/l4d2_tank_announce.smx
L 11/22/2024 - 21:39:43: [SM] Call stack trace:
L 11/22/2024 - 21:39:43: [SM]   [0] IsClientInGame
L 11/22/2024 - 21:39:43: [SM]   [1] Line 92, .\l4d2_tank_announce.sp::IsTank
L 11/22/2024 - 21:39:43: [SM]   [2] Line 43, .\l4d2_tank_announce.sp::L4D_OnSpawnTank_Post
L 11/22/2024 - 21:39:43: [SM]   [4] Call_Finish
L 11/22/2024 - 21:39:43: [SM]   [5] Line 1215, l4dd\l4dd_forwards.sp::Spawn_TankWitch_Post
L 11/22/2024 - 21:39:43: [SM]   [6] Line 1174, l4dd\l4dd_forwards.sp::DTR_ZombieManager_SpawnTank_Post
L 11/22/2024 - 21:39:43: [SM] Exception reported: Client index -1 is invalid
L 11/22/2024 - 21:39:43: [SM] Blaming: confoglcompmod.smx
L 11/22/2024 - 21:39:43: [SM] Call stack trace:
L 11/22/2024 - 21:39:43: [SM]   [0] GetClientAbsOrigin
L 11/22/2024 - 21:39:43: [SM]   [1] Line 132, confoglcompmod\BossSpawning.sp::BS_OnTankSpawnPost_Forward
L 11/22/2024 - 21:39:43: [SM]   [2] Line 433, c:\Users\Sir\SourcePawn11\confoglcompmod.sp::L4D_OnSpawnTank_Post
L 11/22/2024 - 21:39:43: [SM]   [4] Call_Finish
L 11/22/2024 - 21:39:43: [SM]   [5] Line 1215, l4dd\l4dd_forwards.sp::Spawn_TankWitch_Post
L 11/22/2024 - 21:39:43: [SM]   [6] Line 1174, l4dd\l4dd_forwards.sp::DTR_ZombieManager_SpawnTank_Post
L 11/22/2024 - 21:39:48: [SM] Exception reported: Client index -1 is invalid
L 11/22/2024 - 21:39:48: [SM] Blaming: optional/l4d2_tank_announce.smx
L 11/22/2024 - 21:39:48: [SM] Call stack trace:
L 11/22/2024 - 21:39:48: [SM]   [0] IsClientInGame
L 11/22/2024 - 21:39:48: [SM]   [1] Line 92, .\l4d2_tank_announce.sp::IsTank
L 11/22/2024 - 21:39:48: [SM]   [2] Line 43, .\l4d2_tank_announce.sp::L4D_OnSpawnTank_Post
L 11/22/2024 - 21:39:48: [SM]   [4] Call_Finish
L 11/22/2024 - 21:39:48: [SM]   [5] Line 1215, l4dd\l4dd_forwards.sp::Spawn_TankWitch_Post
L 11/22/2024 - 21:39:48: [SM]   [6] Line 1174, l4dd\l4dd_forwards.sp::DTR_ZombieManager_SpawnTank_Post
L 11/22/2024 - 21:39:48: [SM] Exception reported: Client index -1 is invalid
L 11/22/2024 - 21:39:48: [SM] Blaming: confoglcompmod.smx
L 11/22/2024 - 21:39:48: [SM] Call stack trace:
L 11/22/2024 - 21:39:48: [SM]   [0] GetClientAbsOrigin
L 11/22/2024 - 21:39:48: [SM]   [1] Line 132, confoglcompmod\BossSpawning.sp::BS_OnTankSpawnPost_Forward
L 11/22/2024 - 21:39:48: [SM]   [2] Line 433, c:\Users\Sir\SourcePawn11\confoglcompmod.sp::L4D_OnSpawnTank_Post
L 11/22/2024 - 21:39:48: [SM]   [4] Call_Finish
L 11/22/2024 - 21:39:48: [SM]   [5] Line 1215, l4dd\l4dd_forwards.sp::Spawn_TankWitch_Post
L 11/22/2024 - 21:39:48: [SM]   [6] Line 1174, l4dd\l4dd_forwards.sp::DTR_ZombieManager_SpawnTank_Post

**Comment by cH1yoi** [comment]
This issue uses left4dhooks version 1.151

**Comment by SirPlease** [comment]
You didn't specify how many spectators (or even better, total clients) you had, but I'm assuming you simply went to the maximum (32 total clients)
This is not an issue caused by left4dhooks

**Comment by cH1yoi** [comment]
> You didn't specify how many spectators (or even better, total clients) you had, but I'm assuming you simply went to the maximum (32 total clients) This is not an issue caused by left4dhooks

Yes, it was verified that sourcetv was causing it

**Comment by A1mDev** [comment]
Slot 32 is not available in the game - https://github.com/ValveSoftware/Source-1-Games/issues/3387
