### ISSUE TITLE
Config elite hc_bridge_car_damage is 400.0

### ISSUE THREAD

**Issue by Electr0** [SirPlease/L4D2-Competitive-Rework#9]
because in cvars you set confogl_addcvar hc_bridge_car_damage 100.0
BUT in sources l4d2_hittable_control.sp:

```
if (bIsBridge)
{
	damage = GetConVarFloat(hBridgeCarDamage) * 4.0;
	inflictor = 0;
}
```
damage  multiply by 4.0

i am know 100 or 400 is death damage but you understand what i am mean (use fixed version..)

**Comment by SirPlease** [comment]
Thanks for the report,

Appears that this is a different cvar on EQ, PME and Zonemod/Apex.
I'll unify them in next push.
