### ISSUE TITLE
 Jockey teleports with the survivor into the skybox

### ISSUE THREAD

**Issue by C0REX** [SirPlease/L4D2-Competitive-Rework#91]
It happens sporadically and there is nothing to suggest that it is happening now. It is very strange. Sometimes it happens and sometimes it doesn't.

Which plugins can be used for this problem? I would like to narrow it down.

**Comment by SirPlease** [comment]
This is not caused by one of the plugins in this repository.

**Comment by CanadianJeff** [comment]
I see this happen on valves official servers all the time I think its part of aimware tool
