### ISSUE TITLE
these plugins lead to a compromised server

### ISSUE THREAD

**Issue by CanadianJeff** [SirPlease/L4D2-Competitive-Rework#93]
please provide sourcecode for ALL plugins in this repo so we can investigate which plugin is responsible for the backdoor compromise that was found on 9 of my servers using these and only these plugins

would be nice to remove all plugins not providing the source code so that users can review the code and PR #16 can go ahead

**Comment by SirPlease** [comment]
Must suck having your servers attacked after going after competitive servers yourself, hm?

Regardless, specify what exactly you're referring to and I'll take a look.
